import json
W="https://fr.wikipedia.org/wiki/"
def A(cat,title,label,teaser,lead,body,wiki,more=None,timeline=None,lat=None,lon=None,links=None,access=None,protection=None):
    return {"category":cat,"title":title,"label":label,"teaser":teaser,"lead":lead,"text":lead,"body":body,"more":more or [],
            "timeline":timeline,"links":links,"wiki":wiki,"source":W+wiki,"lat":lat,"lon":lon,"access":access,"protection":protection}
L=lambda kind,title,url,note=None:{"kind":kind,"title":title,"url":url,"note":note}

arts=[
# ================= FAITS DIVERS =================
A("faits_divers","Quarante-neuf morts en un an : la guerre du narcotrafic","2023 · Quartiers nord",
 "En 2023, le parquet de Marseille a compté 49 homicides liés au trafic de drogue, un record. Des adolescents de quatorze ans recrutés comme tueurs, des règlements de comptes à la kalachnikov, des points de deal qui rapportent des dizaines de milliers d'euros par jour.",
 "L'année 2023 a été la plus meurtrière de l'histoire récente de Marseille : 49 personnes tuées dans des règlements de comptes liés à la drogue, selon le parquet.",
 ["Les cités des quartiers nord, La Castellane, La Paternelle, Frais-Vallon, les Oliviers, abritent des points de vente de cannabis et de cocaïne qui fonctionnent comme des entreprises : guetteurs, vendeurs, « nourrices » qui stockent la marchandise, et des chefs souvent installés à l'étranger, notamment à Dubaï. Les réseaux les plus connus, la DZ Mafia et Yoda, se disputent les emplacements les plus rentables.",
  "La violence a changé de nature : les tueurs sont de plus en plus jeunes, parfois mineurs, recrutés sur les réseaux sociaux pour quelques milliers d'euros, et les victimes sont souvent de simples exécutants ou des personnes sans lien avec le trafic, tuées par erreur ou prises dans un échange de tirs. Plusieurs victimes de 2023 avaient moins de vingt ans.",
  "L'État a répondu par des opérations « place nette » menées à partir de 2024, avec des milliers de policiers déployés pendant plusieurs semaines, et par la loi de 2025 créant un parquet national chargé de la criminalité organisée. Le nombre d'homicides a reculé en 2024, sans que le trafic ne disparaisse."],
 "Narcotrafic_%C3%A0_Marseille",
 more=["Le procès de la DZ Mafia et les enquêtes sur ses donneurs d'ordre installés à l'étranger ont mis en lumière l'usage des messageries chiffrées et des réseaux sociaux pour recruter des tueurs à distance.",
       "Marseille concentre une part importante des homicides liés au narcotrafic en France, mais le phénomène touche désormais Nîmes, Grenoble, Dijon ou Rennes."]),
A("faits_divers","Rue d'Aubagne : deux immeubles s'effondrent, huit morts","5 novembre 2018 · Noailles",
 "Un lundi matin, les numéros 63 et 65 de la rue d'Aubagne s'écroulent en quelques secondes. Huit habitants meurent. La ville découvre l'ampleur de son habitat indigne, et des milliers de Marseillais sont évacués dans les mois qui suivent.",
 "Le 5 novembre 2018 vers 9 heures, deux immeubles mitoyens de la rue d'Aubagne, au cœur du quartier populaire de Noailles, s'effondrent. Huit personnes sont tuées.",
 ["Le numéro 65, immeuble du XVIIIe siècle habité par des familles modestes, s'écroule le premier et entraîne le 63, propriété de la ville, muré depuis des années. Les victimes ont entre 26 et 63 ans : une mère de famille, un étudiant, un artiste peintre, des locataires qui avaient signalé à plusieurs reprises des fissures et une porte qui ne fermait plus. Un arrêté de péril avait été pris quelques semaines plus tôt, puis levé après des travaux de fortune.",
  "Dans les mois suivants, la mairie évacue par précaution plus de 3 000 personnes de centaines d'immeubles jugés dangereux. Les manifestations de colère se succèdent ; l'affaire devient le symbole de l'habitat indigne à Marseille, où un rapport officiel estimait dès 2015 que 100 000 personnes vivaient dans des logements insalubres, et pèse lourdement sur les élections municipales de 2020.",
  "Le procès s'ouvre en novembre 2024 devant le tribunal correctionnel : propriétaires, syndic, expert et un ancien adjoint au maire chargé des immeubles menaçant ruine comparaissent pour homicides involontaires. Le jugement, rendu en 2025, prononce plusieurs condamnations, dont des peines de prison avec sursis."],
 "Effondrement_d%27immeubles_de_la_rue_d%27Aubagne",lat=43.2946,lon=5.3828,
 more=["Un collectif, le Collectif du 5 novembre, s'est constitué pour accompagner les délogés et obtenir le procès. La place devant les immeubles disparus a été transformée en lieu de mémoire.",
       "La catastrophe a conduit à la création en 2019 d'une société publique d'aménagement chargée de la rénovation du centre ancien sur quinze ans."]),
A("faits_divers","Deux jeunes femmes tuées à la gare Saint-Charles","1er octobre 2017 · Gare Saint-Charles",
 "Sur le parvis de la gare, un dimanche après-midi, un homme armé d'un couteau tue deux cousines de vingt ans avant d'être abattu par des militaires de l'opération Sentinelle. L'État islamique revendique.",
 "Le 1er octobre 2017, vers 13 h 45, Mauranne et Laura, deux cousines de 20 et 21 ans, sont poignardées sur le parvis de la gare Saint-Charles. L'assaillant est abattu quelques minutes plus tard.",
 ["L'homme, un Tunisien de 29 ans en situation irrégulière, connu de la police sous plusieurs identités, avait été interpellé deux jours plus tôt à Lyon pour un vol et relâché faute de place en centre de rétention. Il attaque une première jeune femme, s'éloigne, revient tuer la seconde, puis fonce sur une patrouille de l'opération Sentinelle qui ouvre le feu.",
  "L'État islamique revendique l'attaque le soir même. Les deux victimes étaient étudiantes en médecine à Lyon et venaient passer le week-end à Marseille. Une plaque a été apposée sur le parvis.",
  "L'affaire a provoqué une polémique nationale sur la libération de l'auteur deux jours avant les faits et conduit à la mise en cause de la préfecture du Rhône. Le frère de l'assaillant, arrêté en Italie, a été condamné en 2023 pour sa participation à un réseau de recrutement djihadiste."],
 "Attentat_de_la_gare_Saint-Charles_de_Marseille",lat=43.3027,lon=5.3806),
A("faits_divers","Le parrain retrouvé pendu aux Baumettes","1984 · Prison des Baumettes",
 "Gaëtan Zampa, dit Tany, a régné sur le milieu marseillais pendant quinze ans : boîtes de nuit, machines à sous, héroïne. Arrêté en 1983, il est retrouvé pendu dans sa cellule. Suicide, dit l'enquête. Beaucoup n'y ont jamais cru.",
 "Gaëtan Zampa, le dernier grand parrain de Marseille, meurt le 23 août 1984 à l'hôpital, quelques jours après avoir été retrouvé pendu dans sa cellule des Baumettes.",
 ["Né en 1933 à Marseille, Zampa succède à la génération Guérini et aux trafiquants de la French Connection. Dans les années 1970, il contrôle les bars, les boîtes de nuit et les machines à sous de la ville, et se trouve mêlé à la guerre contre le clan de Francis « le Belge » Vanverberghe, qui fait des dizaines de morts entre Marseille et Paris.",
  "Arrêté en janvier 1983 pour fraude fiscale, il est placé en détention aux Baumettes. Le 16 août 1984, il est découvert pendu dans sa cellule avec une ceinture ; il meurt une semaine plus tard sans avoir repris connaissance. Sa femme et ses proches contestent la thèse du suicide, évoquant les secrets qu'il aurait pu livrer sur ses liens avec la police et les politiques.",
  "Sa mort marque la fin de l'ère des « parrains » marseillais à l'ancienne. Sa veuve, Christiane Zampa, a publié ses souvenirs sous le titre « La Marseillaise »."],
 "Ga%C3%A9tan_Zampa",lat=43.2437,lon=5.4120),
A("faits_divers","Le juge Michel abattu à moto, boulevard Michelet","21 octobre 1981 · Boulevard Michelet",
 "À 38 ans, Pierre Michel était le magistrat qui faisait trembler les trafiquants d'héroïne marseillais. Deux hommes à moto l'attendent à la sortie du palais ; trois balles, et la French Connection a tué un juge.",
 "Le 21 octobre 1981, à 13 h 20, le juge d'instruction Pierre Michel rentre déjeuner à moto par le boulevard Michelet. Une autre moto le rattrape ; le passager tire trois fois. Il meurt sur place.",
 ["Arrivé à Marseille en 1975, Pierre Michel s'était attaqué de front aux laboratoires d'héroïne qui approvisionnaient les États-Unis. Il travaillait sans protection, instruisait les dossiers de la French Connection et des grands trafiquants du milieu, et avait obtenu les premières condamnations lourdes. Il laisse une femme et deux filles.",
  "L'enquête piétine jusqu'en 1986, quand un repenti, Gérard Lavigne, désigne les tireurs : François Checchi et Charles Altieri, deux hommes du milieu. Ils sont condamnés en 1988 à la réclusion à perpétuité. Le commanditaire, François Girard, trafiquant d'héroïne, est également condamné ; Homère Filippi, mort entre-temps, avait servi d'intermédiaire.",
  "L'assassinat a provoqué un électrochoc national : il est, après celui du juge Renaud à Lyon en 1975, le deuxième magistrat tué en France depuis la Libération. Une rue de Marseille porte son nom près du palais de justice, et une plaque marque le lieu du crime sur le boulevard Michelet."],
 "Pierre_Michel_(juge)",lat=43.2680,lon=5.3960,
 links=[L("film","« Le Juge » (1984), de Philippe Lefebvre, avec Jacques Weber","https://fr.wikipedia.org/wiki/Le_Juge_(film,_1984)","Inspiré directement de l'affaire, trois ans après les faits"),
        L("film","« La French » (2014), de Cédric Jimenez, avec Jean Dujardin","https://fr.wikipedia.org/wiki/La_French","Dujardin joue le juge Michel face à Gilles Lellouche en Gaëtan Zampa"),
        L("livre","« Le Juge Michel » de Michel Dormieu (2010)","https://www.google.fr/search?q=Michel+Dormieu+%22juge+Michel%22+livre","Enquête d'un ancien policier")]),
A("faits_divers","Dix morts au bar du Téléphone","19 octobre 1978 · Rue de la Bibliothèque, La Belle-de-Mai",
 "Au petit matin, des hommes entrent dans un bar de quartier et abattent méthodiquement tous ceux qui s'y trouvent : dix morts, dont le patron et des clients sans histoire. Le crime n'a jamais été élucidé.",
 "Dans la nuit du 19 au 20 octobre 1978, dix personnes sont exécutées au bar Le Téléphone, dans le quartier de la Belle-de-Mai. C'est la tuerie la plus meurtrière de l'histoire du milieu marseillais, et elle reste impunie.",
 ["Vers 1 h 30, deux ou trois hommes armés de pistolets-mitrailleurs font irruption dans le bar, un établissement modeste réputé lieu de rendez-vous de petits truands. Ils alignent les présents et tirent : le patron, des clients, des joueurs de cartes. Dix morts, aucun survivant pour témoigner.",
  "Les enquêteurs explorent toutes les pistes : vengeance liée au trafic d'héroïne, représailles après un vol, règlement de comptes entre clans. Plusieurs suspects sont entendus, dont des proches du milieu niçois et marseillais. Aucune mise en accusation ne tient. Le dossier est clos sans coupable.",
  "La tuerie du bar du Téléphone est restée, pour Marseille, l'équivalent de ce qu'est pour Chicago le massacre de la Saint-Valentin : le symbole d'un milieu qui ne respectait plus aucune règle."],
 "Tuerie_du_bar_du_T%C3%A9l%C3%A9phone",lat=43.3105,lon=5.3850),
A("faits_divers","La French Connection, l'héroïne de Marseille à New York","1960-1973 · Toute la ville",
 "Pendant vingt ans, des chimistes marseillais ont transformé la morphine-base turque en héroïne pure dans des villas de la banlieue, avant de l'expédier aux États-Unis. Un film, deux Oscars, et des centaines d'arrestations.",
 "Dans les années 1960, Marseille fournit l'essentiel de l'héroïne consommée aux États-Unis. Les laboratoires sont cachés dans des villas des quartiers sud et des environs ; les chimistes sont corses et marseillais.",
 ["La filière naît après-guerre : la morphine-base arrive de Turquie, est raffinée près de Marseille par des chimistes comme Jo Cesari, dont le laboratoire est démantelé en 1964, puis expédiée vers New York, dissimulée dans des voitures, des valises, des conserves. On estime qu'à la fin des années 1960, 80 % de l'héroïne américaine vient de Marseille.",
  "La pression américaine s'intensifie après 1969 : agents de la DEA installés sur place, menaces diplomatiques. Entre 1970 et 1973, les saisies et arrestations se multiplient ; le laboratoire d'Aubagne, les cargaisons interceptées à Marseille et à New York, l'arrestation d'Auguste Ricord en Amérique du Sud marquent la fin du système.",
  "La French Connection a laissé une trace durable : le film de William Friedkin en 1971, le mythe du milieu marseillais, et une méfiance tenace de la ville envers son image."],
 "French_Connection",
 links=[L("film","« French Connection » (1971), de William Friedkin","https://fr.wikipedia.org/wiki/French_Connection_(film)","Cinq Oscars, dont meilleur film ; Gene Hackman en Popeye Doyle"),
        L("film","« La French » (2014), de Cédric Jimenez","https://fr.wikipedia.org/wiki/La_French","Le volet marseillais, vu du juge Michel"),
        L("documentaire","« French Connection, l'histoire vraie » (Arte)","https://www.arte.tv/fr/search/?q=French+Connection","Documentaire d'archives")]),
A("faits_divers","Les Nouvelles Galeries brûlent, 73 morts","28 octobre 1938 · La Canebière",
 "Un mégot dans un stand de jouets, un grand magasin sans issue de secours, des pompiers sans eau : en pleine Canebière, sous les yeux du gouvernement réuni en congrès, le feu tue 73 personnes. La ville en perdra son autonomie.",
 "Le 28 octobre 1938, un incendie détruit le grand magasin des Nouvelles Galeries sur la Canebière et fait 73 morts. Édouard Daladier, président du Conseil, assiste au drame depuis l'hôtel voisin.",
 ["Le feu prend en début d'après-midi au rayon des jouets, probablement à cause d'un mégot. Le magasin, bondé, n'a ni escalier de secours ni compartimentage ; les flammes gagnent les étages en quelques minutes. Les pompiers municipaux arrivent avec un matériel vétuste et des bouches d'incendie sans pression ; des clients se jettent dans le vide.",
  "Le congrès du Parti radical se tient au même moment à Marseille, et Daladier loge à l'hôtel Noailles, mitoyen. Le gouvernement voit de ses fenêtres l'impuissance de la ville. Le bilan, 73 morts, choque le pays.",
  "Les conséquences sont politiques : en mars 1939, une loi place Marseille sous tutelle de l'État, le conseil municipal est dissous et un administrateur extraordinaire nommé. La même loi crée le bataillon de marins-pompiers, unité de la Marine nationale qui assure encore aujourd'hui la sécurité incendie de la ville."],
 "Incendie_des_Nouvelles_Galeries",lat=43.2969,lon=5.3773,
 more=["Le procès de 1940 condamne le gérant et des responsables du magasin à des peines légères. Un monument aux victimes se trouve au cimetière Saint-Pierre.",
       "La tutelle de l'État sur la ville n'a été levée qu'en 1946."]),
A("faits_divers","Un roi assassiné sur la Canebière","9 octobre 1934 · La Canebière",
 "Alexandre Ier de Yougoslavie vient d'arriver à Marseille pour une visite d'État. Sa voiture remonte la Canebière au pas quand un homme bondit sur le marchepied et tire. Le roi meurt, le ministre français aussi, et les caméras ont tout filmé.",
 "Le 9 octobre 1934, le roi Alexandre Ier de Yougoslavie est assassiné sur la Canebière, quelques minutes après avoir débarqué. Le ministre des Affaires étrangères Louis Barthou meurt le même jour.",
 ["Le tireur, Vlado Tchernozemski, est un militant de l'organisation révolutionnaire macédonienne liée aux oustachis croates, qui veulent la fin du royaume yougoslave. Il profite d'un service d'ordre dérisoire, saute sur le marchepied de la voiture découverte et vide son chargeur. Un garde à cheval le frappe de son sabre ; la foule le lynche, il meurt dans la nuit.",
  "Louis Barthou, blessé au bras, meurt faute d'un garrot posé à temps. L'enquête établira plus tard que la balle qui l'a tué venait d'un policier français qui tirait sur l'assassin. L'attentat est le premier filmé de l'histoire : les actualités Pathé le diffusent dans le monde entier.",
  "La crise diplomatique est grave : la Yougoslavie accuse la Hongrie et l'Italie d'avoir hébergé les comploteurs. La Société des Nations adopte en 1937 une convention contre le terrorisme. Une plaque rappelle l'attentat sur la Canebière, devant la Bourse."],
 "Assassinat_d%27Alexandre_Ier_de_Yougoslavie",lat=43.2965,lon=5.3760,
 links=[L("vidéo","Les images d'actualités de l'attentat (INA)","https://www.ina.fr/recherche?q=assassinat+Alexandre+Marseille+1934","Premier attentat filmé de l'histoire")]),
A("faits_divers","Le match truqué qui a fait tomber Tapie","20 mai 1993 · Valenciennes, puis Marseille",
 "Six jours avant la finale de la Ligue des champions, des joueurs de Valenciennes reçoivent de l'argent pour « lever le pied » contre l'OM. Le titre de champion est retiré, le club relégué, et Bernard Tapie finit en prison.",
 "Le 20 mai 1993, l'OM bat Valenciennes 1-0. Un joueur valenciennois, Jacques Glassmann, révèle qu'on lui a proposé de l'argent pour ne pas se blesser ni blesser les Marseillais avant la finale européenne.",
 ["L'intermédiaire est Jean-Jacques Eydelie, joueur de l'OM, qui a appelé trois Valenciennois à la demande de Jean-Pierre Bernès, directeur général du club. L'argent, 250 000 francs, est retrouvé enterré dans le jardin de la tante d'un joueur. Six jours plus tard, l'OM remporte la Ligue des champions à Munich contre le Milan AC.",
  "La Fédération retire à l'OM son titre de champion de France 1993, lui interdit la Coupe intercontinentale et le relègue en deuxième division en 1994. Bernard Tapie, président du club et ministre, est condamné en 1995 à deux ans de prison dont huit mois ferme pour complicité de corruption et subornation de témoins. Il purge sa peine aux Baumettes puis à la prison de Luynes.",
  "L'affaire, dite VA-OM, n'a jamais remis en cause la victoire européenne, restée à ce jour la seule d'un club français. Jacques Glassmann, le lanceur d'alerte, a longtemps été sifflé dans les stades."],
 "Affaire_VA-OM",
 links=[L("documentaire","« Tapie » (2023), série Netflix avec Laurent Lafitte","https://fr.wikipedia.org/wiki/Tapie_(s%C3%A9rie_t%C3%A9l%C3%A9vis%C3%A9e)","La fiction retrace l'affaire VA-OM")]),
A("faits_divers","Le Vieux-Port dynamité : 1 500 immeubles rasés en une semaine","Janvier-février 1943 · Quartier Saint-Jean",
 "Sur ordre de Himmler, avec le concours de la police française, 20 000 habitants des vieux quartiers du port sont évacués et déportés pour partie, puis le quartier est dynamité maison par maison. Il n'en reste que deux bâtiments.",
 "Du 22 au 24 janvier 1943, l'opération Sultan vide le quartier Saint-Jean, au nord du Vieux-Port : rafle de 20 000 personnes, puis destruction à l'explosif de 1 500 immeubles.",
 ["Après des attentats contre l'occupant, Himmler et le chef de la police allemande Oberg décident de « nettoyer » le Vieux-Port, qu'ils tiennent pour un repaire de résistants et de criminels. La rafle est menée par 12 000 policiers français sous l'autorité de René Bousquet. Près de 800 Juifs sont déportés vers Sobibor, et 1 640 personnes envoyées dans des camps allemands.",
  "À partir du 1er février, le génie allemand fait sauter le quartier : les ruelles médiévales, les hôtels particuliers, les maisons de pêcheurs. Ne subsistent que l'hôtel de ville, l'hôtel de Cabre et la maison Diamantée, épargnés pour leur valeur historique. Un film de propagande montre les destructions.",
  "Le quartier a été reconstruit après-guerre par Fernand Pouillon dans le style qui borde aujourd'hui le quai du Port. Un mémorial de la rafle a été inauguré en 2023 sur la place des Mouliniers."],
 "Rafle_de_Marseille",lat=43.2965,lon=5.3690),
A("faits_divers","La peste de 1720 : la moitié de la ville meurt","1720-1722 · Toute la ville",
 "Un navire chargé de soie et de coton arrive du Levant avec la peste à bord. Les échevins, pressés de vendre la cargaison à la foire de Beaucaire, allègent la quarantaine. En deux ans, 40 000 Marseillais meurent sur 90 000.",
 "Le 25 mai 1720, le Grand-Saint-Antoine mouille devant Marseille. Il transporte des étoffes du Levant et la peste. L'épidémie va tuer près de la moitié des habitants.",
 ["Des matelots sont morts pendant la traversée, mais le capitaine Chataud obtient l'autorisation de débarquer la cargaison après une quarantaine écourtée : des échevins ont des intérêts dans la marchandise. En juin, les premiers morts tombent rue de l'Escale. En août, on compte mille décès par jour ; les cadavres s'entassent dans les rues, les galériens sont réquisitionnés pour les enlever.",
  "L'évêque Belsunce et le chevalier Roze deviennent les héros de l'épidémie : le premier reste auprès des mourants, le second fait évacuer les corps de l'esplanade de la Tourette avec ses galériens. Le Parlement d'Aix fait construire le « mur de la peste » dans le Vaucluse pour isoler la Provence.",
  "L'épidémie s'éteint en 1722. Elle a tué entre 30 000 et 40 000 personnes à Marseille et autant en Provence. C'est la dernière grande peste d'Europe occidentale. Les fouilles de 1994 sur le site de la Major ont retrouvé une fosse commune de l'époque."],
 "Peste_de_Marseille_(1720)",
 more=["Le Grand-Saint-Antoine a été brûlé en septembre 1720 sur ordre du Régent. Son épave, retrouvée en 1978 au large de l'île de Jarre, a été fouillée.",
       "Le cours Belsunce et la rue du Chevalier-Roze portent le nom des deux figures de l'épidémie."]),

# ================= HISTOIRE =================
A("histoire","La plus vieille ville de France","Vers 600 av. J.-C. · Le Panier et le Vieux-Port",
 "Des marins grecs venus de Phocée fondent Massalia dans une calanque abritée. Vingt-six siècles plus tard, la ville est toujours là, autour du même port.",
 "Marseille a été fondée vers 600 avant notre ère par des Grecs de Phocée, en Asie Mineure. C'est la plus ancienne ville de France.",
 ["Les Phocéens, commerçants et navigateurs, choisissent la calanque du Lacydon, l'actuel Vieux-Port, protégée des vents et facile à défendre. La cité grecque s'organise sur les collines du Panier, avec son agora, ses temples et ses remparts, dont les fouilles du Jardin des vestiges, derrière la Bourse, ont dégagé les quais et la porte du IIe siècle avant notre ère.",
  "Massalia prospère grâce au commerce du vin, de l'huile et de l'étain, fonde des comptoirs d'Agde à Nice et jusqu'en Espagne, et reste une république indépendante alliée de Rome. En 49 avant notre ère, elle choisit le camp de Pompée contre César, qui l'assiège et lui retire son empire commercial. Elle garde ses institutions et son grec jusque sous l'Empire.",
  "L'explorateur Pythéas, parti de Massalia vers 325 avant notre ère, a atteint la Grande-Bretagne et peut-être l'Islande, et calculé la latitude de sa ville avec une précision remarquable."],
 "Massalia",lat=43.2975,lon=5.3760),
A("histoire","La Marseillaise ne vient pas de Marseille","1792 · Rue Thubaneau",
 "L'hymne a été composé à Strasbourg. Ce sont les volontaires marseillais, montés à Paris en chantant, qui lui ont donné son nom.",
 "La Marseillaise a été écrite à Strasbourg par Rouget de Lisle en avril 1792. Elle doit son nom aux 500 fédérés marseillais qui l'ont chantée en marchant sur Paris, l'été suivant.",
 ["Le « Chant de guerre pour l'armée du Rhin » arrive à Marseille par un étudiant, François Mireur, qui le chante en juin 1792 au club des Jacobins, rue Thubaneau. Il est imprimé et distribué aux volontaires du bataillon marseillais qui partent pour Paris le 2 juillet.",
  "Les fédérés le chantent à chaque étape et entrent dans Paris le 30 juillet en l'entonnant ; les Parisiens le baptisent « l'hymne des Marseillais ». Dix jours plus tard, ils participent à la prise des Tuileries, qui renverse la monarchie. L'hymne devient chant national en 1795.",
  "Le Mémorial de la Marseillaise, installé en 2011 dans l'ancien jeu de paume de la rue Thubaneau, retrace cet épisode."],
 "La_Marseillaise",lat=43.2983,lon=5.3790),
A("histoire","1962 : la ville des rapatriés","1962 · Port de la Joliette",
 "En quelques mois, plus de 100 000 Français d'Algérie débarquent à Marseille, valises à la main. Beaucoup y restent. La ville change de visage.",
 "À l'été 1962, après l'indépendance de l'Algérie, Marseille est la porte d'entrée des rapatriés : plusieurs centaines de milliers transitent par le port, et plus de 100 000 s'installent dans le département.",
 ["Les paquebots arrivent chaque jour à la Joliette, chargés de familles qui ont tout laissé. Les services d'accueil sont débordés ; des campements de fortune s'installent, les hôtels affichent complet, les écoles ouvrent des classes en septembre pour des milliers d'enfants supplémentaires.",
  "Les grands ensembles construits dans les années 1960 et 1970, dans les quartiers nord comme au sud, accueillent une part de ces nouveaux habitants. La ville passe de 660 000 à près de 900 000 habitants entre 1954 et 1975.",
  "Les pieds-noirs ont transformé la cuisine, la politique et l'accent de Marseille. Un mémorial leur est consacré sur la Corniche, face à la mer."],
 "Rapatri%C3%A9s_d%27Alg%C3%A9rie"),
A("histoire","Le Château d'If, prison avant d'être roman","1524-1890 · Île d'If",
 "François Ier le fait bâtir pour défendre le port. On y enferme des protestants, des mutins, des aristocrates, et Alexandre Dumas y enferme Edmond Dantès. Le prisonnier le plus célèbre de l'île n'a jamais existé.",
 "Forteresse construite entre 1524 et 1531 sur ordre de François Ier, le château d'If devient prison d'État dès le XVIe siècle et le reste jusqu'en 1890.",
 ["Le fort doit protéger Marseille d'une attaque par mer après le passage de Charles Quint. Rapidement, son isolement en fait une prison : des milliers de protestants après la révocation de l'édit de Nantes, les mutins de 1848, des opposants au Second Empire. Les cellules des pauvres sont des cachots sans lumière ; les riches paient pour une pièce avec cheminée.",
  "En 1844, Alexandre Dumas y fait enfermer Edmond Dantès, le héros du « Comte de Monte-Cristo », quatorze ans durant, avant son évasion dans un sac mortuaire jeté à la mer. Le succès du roman est tel que, dès le XIXe siècle, les gardiens montrent aux visiteurs la « cellule de Dantès » et le trou creusé par l'abbé Faria.",
  "L'île se visite en vingt minutes de bateau depuis le Vieux-Port. Un rhinocéros y a fait escale en 1516, offert par le roi du Portugal au pape : Dürer l'a gravé sans l'avoir vu."],
 "Ch%C3%A2teau_d%27If",lat=43.2797,lon=5.3253,access="Visite par navette depuis le Vieux-Port",protection="Monument historique, 1926",
 links=[L("livre","« Le Comte de Monte-Cristo » d'Alexandre Dumas (1844)","https://fr.wikipedia.org/wiki/Le_Comte_de_Monte-Cristo","Le roman qui a fait la célébrité de l'île"),
        L("film","« Le Comte de Monte-Cristo » (2024), avec Pierre Niney","https://fr.wikipedia.org/wiki/Le_Comte_de_Monte-Cristo_(film,_2024)","Plus de neuf millions d'entrées")]),

# ================= PERSONNALITES =================
A("personnalites","Zidane, enfant de la Castellane","Né le 23 juin 1972 · La Castellane, 16e arrondissement",
 "Le meilleur joueur français de l'histoire a appris le football sur la place Tartane, entre les tours d'une cité des quartiers nord. Il n'a jamais joué pour l'OM.",
 "Zinédine Zidane est né à Marseille le 23 juin 1972 et a grandi à la Castellane, grand ensemble du 16e arrondissement.",
 ["Dernier de cinq enfants d'une famille kabyle, il tape dans le ballon sur la place Tartane, au pied des immeubles, puis à l'US Saint-Henri et au Septèmes-les-Vallons. Repéré à quatorze ans, il part pour le centre de formation de Cannes : sa carrière se fera loin de Marseille, à Bordeaux, Turin et Madrid.",
  "Champion du monde en 1998 avec deux buts de la tête en finale, champion d'Europe en 2000, Ballon d'or 1998, il revient régulièrement à la Castellane, où une fresque le représente. Le stade Vélodrome l'a accueilli en Bleu, jamais en Marseillais.",
  "Il a été, de 2016 à 2021, l'entraîneur du Real Madrid, vainqueur de trois Ligues des champions consécutives."],
 "Zin%C3%A9dine_Zidane",
 timeline=[{"year":"1972","text":"Naissance à Marseille, enfance à la Castellane."},{"year":"1986","text":"Départ pour le centre de formation de l'AS Cannes."},{"year":"1998","text":"Champion du monde, Ballon d'or."},{"year":"2006","text":"Dernier match, finale de Coupe du monde."},{"year":"2016","text":"Entraîneur du Real Madrid."}],
 lat=43.3625,lon=5.3480),
A("personnalites","Pagnol et le bar de la Marine","1895-1974 · Vieux-Port",
 "Né à Aubagne, grandi à Marseille, Marcel Pagnol a fait du Vieux-Port un décor de théâtre et de cinéma : Marius, Fanny, César, et la partie de cartes la plus célèbre de France.",
 "Marcel Pagnol a passé son enfance à Marseille, rue Terrusse puis cours Lieutaud, et a fait du Vieux-Port le cadre de sa trilogie marseillaise.",
 ["Fils d'instituteur, né à Aubagne en 1895, il est élève du lycée Thiers, où il fonde une revue littéraire. Professeur d'anglais, il monte à Paris et triomphe au théâtre avec « Topaze » en 1928, puis « Marius » en 1929 : l'histoire d'un fils de cafetier du Vieux-Port tiraillé entre la mer et Fanny.",
  "Le bar de la Marine, où César, Panisse, Escartefigue et M. Brun jouent aux cartes, a existé : il se trouvait quai de Rive-Neuve, et Pagnol le reconstitue en studio pour le film de 1931. La trilogie fixe pour toujours l'accent et le caractère marseillais au cinéma, pour le meilleur et pour le cliché.",
  "Pagnol installe ses propres studios à Marseille, boulevard Longchamp, en 1934. Premier cinéaste élu à l'Académie française, il meurt à Paris en 1974 et repose au cimetière de La Treille, dans les collines de ses souvenirs d'enfance."],
 "Marcel_Pagnol",
 timeline=[{"year":"1895","text":"Naissance à Aubagne ; enfance à Marseille."},{"year":"1929","text":"« Marius » au théâtre."},{"year":"1934","text":"Studios de cinéma à Marseille."},{"year":"1946","text":"Élu à l'Académie française."},{"year":"1974","text":"Mort à Paris, inhumé à La Treille."}],
 links=[L("film","« Marius » (1931), « Fanny » (1932), « César » (1936)","https://fr.wikipedia.org/wiki/Trilogie_marseillaise","La trilogie marseillaise")]),
A("personnalites","IAM, le rap qui a mis Marseille sur la carte","1989 · Quartiers nord et centre",
 "Avant IAM, le rap français était parisien. Avec « Je danse le Mia » puis « L'École du micro d'argent », le groupe du Plan-d'Aou et de la Vieille Chapelle a imposé Marseille, son accent et ses références égyptiennes.",
 "Fondé en 1989 par Akhenaton, Shurik'n, Kheops, Imhotep et Kephren, IAM est le groupe qui a donné au rap marseillais son identité, entre mythologie égyptienne, films de kung-fu et chroniques des quartiers.",
 ["Les membres viennent de milieux différents, du Plan-d'Aou au quartier du Panier, et se rencontrent dans les radios libres et les soirées des années 1980. Le premier album, « De la planète Mars » (1991), fait de la ville une planète à part. « Je danse le Mia », en 1993, parodie les boîtes de nuit marseillaises des années 1980 et devient un tube national.",
  "« L'École du micro d'argent », en 1997, se vend à plus d'un million d'exemplaires et reste considéré comme l'un des meilleurs albums de rap français. « Petit frère » et « Demain c'est loin » racontent la ville sans complaisance.",
  "IAM a ouvert la voie à la Fonky Family, au Rat Luciano, à Soprano et Jul, qui a fait de Marseille la capitale française du rap des années 2010. Le groupe se produit toujours, plus de trente ans après ses débuts."],
 "IAM_(groupe)",
 links=[L("musique","« L'École du micro d'argent » (1997)","https://fr.wikipedia.org/wiki/L%27%C3%89cole_du_micro_d%27argent","Disque de diamant")]),
A("personnalites","Edmond Rostand, de la rue Montaux à Cyrano","1868-1918 · 6e arrondissement",
 "L'auteur de « Cyrano de Bergerac » est né à Marseille, dans une famille de négociants et de poètes provençaux. Il avait vingt-neuf ans le soir du triomphe.",
 "Edmond Rostand naît le 1er avril 1868 à Marseille, au 14 rue Montaux, aujourd'hui rue Edmond-Rostand.",
 ["Son père, Eugène Rostand, économiste et traducteur de Catulle, est une figure de la bourgeoisie cultivée marseillaise ; son oncle Alexis est compositeur. Edmond fait ses études au lycée de Marseille, l'actuel lycée Thiers, avant de partir pour Paris à seize ans.",
  "Le 28 décembre 1897, « Cyrano de Bergerac », créé au théâtre de la Porte-Saint-Martin avec Coquelin, provoque un enthousiasme sans précédent : vingt minutes d'applaudissements, quarante rappels. Rostand est fait chevalier de la Légion d'honneur le soir même, dans sa loge. Il entre à l'Académie française en 1901, à trente-trois ans, le plus jeune académicien de l'histoire.",
  "Il meurt de la grippe espagnole en décembre 1918. Son fils Jean Rostand sera biologiste et académicien à son tour."],
 "Edmond_Rostand",
 timeline=[{"year":"1868","text":"Naissance à Marseille, rue Montaux."},{"year":"1897","text":"Triomphe de « Cyrano de Bergerac »."},{"year":"1901","text":"Élu à l'Académie française."},{"year":"1918","text":"Mort à Paris."}]),
A("personnalites","Fernandel, le Marseillais au cheval","1903-1971 · Né à Marseille",
 "Fernand Contandin, dit Fernandel, a commencé dans les cafés-concerts du Vieux-Port avant de devenir l'acteur le plus populaire du cinéma français. Don Camillo, c'est lui.",
 "Fernandel est né à Marseille le 8 mai 1903. Il a tourné plus de 150 films et reste, avec Pagnol dont il fut l'acteur fétiche, l'incarnation du Midi à l'écran.",
 ["Fils d'un comptable qui chante le soir sous le nom de Sined, il monte sur scène à cinq ans et gagne un concours de chant à Marseille. Son surnom vient de sa belle-mère, qui l'appelle « le Fernand d'elle ». Après des années de tournées dans les cafés-concerts, il perce à Paris en 1930.",
  "Pagnol lui donne ses grands rôles, « Angèle », « Regain », « Le Schpountz », « La Fille du puisatier ». À partir de 1952, « Don Camillo » le rend célèbre dans toute l'Europe. Il tourne aussi « Ali Baba », « La Vache et le Prisonnier » et dirige sa propre société de production avec Jean Gabin.",
  "Il meurt à Paris en 1971, pendant le tournage d'un dernier Don Camillo, et repose au cimetière de Passy. Une statue le représente à Marseille, place de l'Opéra ? Non : c'est à Carry-le-Rouet, où il avait sa villa, que la ville l'a honoré ; à Marseille, c'est une place du 1er arrondissement qui porte son nom."],
 "Fernandel"),

# ================= PATRIMOINE =================
A("patrimoine","La Bonne Mère, 11 mètres de cuivre doré","1853-1864 · Colline de la Garde",
 "Visible de partout, la basilique Notre-Dame-de-la-Garde domine la ville de 150 mètres. Sa Vierge dorée mesure 11,2 mètres et veille, dit-on, sur les marins. On l'appelle simplement la Bonne Mère.",
 "La basilique Notre-Dame-de-la-Garde, construite de 1853 à 1864 sur le point culminant de Marseille, est le monument le plus visité de la ville.",
 ["Une chapelle existe sur la colline depuis 1214 ; François Ier y ajoute un fort en 1524. L'édifice actuel, de style romano-byzantin, est dû à l'architecte Henri-Jacques Espérandieu, un protestant nîmois. La statue de la Vierge à l'Enfant, en cuivre repoussé doré à la feuille, est installée en 1870 ; elle a été redorée plusieurs fois, la dernière en 2001.",
  "L'intérieur est tapissé d'ex-voto : maquettes de bateaux suspendues, tableaux de naufrages évités, maillots de l'OM, plaques de remerciement. Les mosaïques de la nef, un million de tesselles, ont été restaurées entre 2001 et 2008.",
  "En août 1944, la colline est l'un des derniers points de résistance allemands ; des impacts de balles sont encore visibles sur la façade nord, et un char de la Libération, le Jeanne d'Arc, est exposé sur le parvis."],
 "Basilique_Notre-Dame-de-la-Garde",lat=43.2841,lon=5.3712,access="Libre, tous les jours de 7h à 18h15",protection="Monument historique, 1917"),
A("patrimoine","La Vieille Charité, hospice devenu musée","1671-1749 · Le Panier",
 "Pierre Puget a dessiné pour les pauvres de Marseille un hospice à cour fermée, avec une chapelle à coupole ovale au centre. Abandonné, squatté, sauvé par Le Corbusier, il abrite aujourd'hui des musées.",
 "La Vieille Charité, dans le quartier du Panier, est le chef-d'œuvre architectural de Marseille : un hospice du XVIIe siècle organisé autour d'une chapelle baroque signée Pierre Puget.",
 ["L'édit royal de 1640 sur « l'enfermement des pauvres » impose aux villes d'enfermer mendiants et vagabonds. Marseille confie à Puget, sculpteur et architecte né dans le quartier, un bâtiment à trois niveaux de galeries sur arcades, enserrant une cour où s'élève la chapelle à coupole elliptique. Les travaux durent près de quatre-vingts ans.",
  "L'hospice ferme en 1905 ; le bâtiment sert de caserne, puis de logements pour les familles chassées par la destruction du Vieux-Port en 1943. Dans les années 1950, Le Corbusier alerte sur son état et obtient son classement. La restauration, menée de 1968 à 1986, lui rend sa pierre rose.",
  "Il accueille le musée d'Archéologie méditerranéenne, le musée des Arts africains, océaniens et amérindiens, et des expositions temporaires."],
 "Vieille_Charit%C3%A9",lat=43.2998,lon=5.3676,access="Du mardi au dimanche, 9h-18h",protection="Monument historique, 1951"),
A("patrimoine","La Cité radieuse, un village vertical","1947-1952 · Boulevard Michelet",
 "Le Corbusier voulait loger 1 600 personnes dans un seul immeuble, avec rue commerçante au 3e étage, école maternelle et piste de course sur le toit. Les Marseillais l'ont surnommée « la maison du fada ».",
 "Inaugurée en 1952, la Cité radieuse du boulevard Michelet est la première « unité d'habitation » de Le Corbusier : 337 appartements en duplex sur 18 niveaux, posés sur pilotis.",
 ["Commandée par l'État pour reloger les sinistrés de la guerre, elle applique les idées de l'architecte : appartements traversants avec loggias colorées, modules calculés sur le Modulor, « rues intérieures », une galerie commerçante au septième étage, un hôtel, et sur le toit-terrasse une école maternelle, un gymnase, un théâtre en plein air et une pataugeoire.",
  "Les habitants, d'abord moqués, ont formé une communauté attachée au lieu ; beaucoup y vivent depuis des décennies. Le bâtiment a été classé monument historique en 1986 et inscrit au patrimoine mondial de l'UNESCO en 2016 avec seize autres œuvres de Le Corbusier.",
  "Le toit, transformé en centre d'art, le MaMo, par le designer Ora-ïto en 2013, se visite. Un incendie a endommagé le bâtiment en 2012 ; la restauration a duré deux ans."],
 "Cit%C3%A9_radieuse_de_Marseille",lat=43.2614,lon=5.3966,access="Visites guidées ; galerie et toit accessibles",protection="Monument historique, 1986 ; UNESCO, 2016"),
A("patrimoine","Le MuCEM et sa résille de béton","2013 · Môle J4",
 "Un cube noir enveloppé de dentelle de béton, relié au fort Saint-Jean par une passerelle de 130 mètres au-dessus de l'eau. C'est le premier musée national installé hors de Paris.",
 "Le musée des Civilisations de l'Europe et de la Méditerranée, ouvert en juin 2013 lorsque Marseille était capitale européenne de la culture, est l'œuvre de l'architecte Rudy Ricciotti.",
 ["Le bâtiment, de 15 000 m², occupe l'ancien môle J4 du port. Sa peau de béton fibré ultra-haute performance, un matériau mis au point en France, filtre la lumière et dessine des motifs changeants sur les salles. Deux passerelles le relient au fort Saint-Jean, restauré pour l'occasion, et à l'esplanade de la Major.",
  "Le musée a hérité des collections de l'ancien musée des Arts et Traditions populaires de Paris, enrichies d'objets méditerranéens contemporains. Les expositions traitent de la Méditerranée dans tous ses états : agriculture, religions, villes, migrations.",
  "Avec plus d'un million de visiteurs la première année, le MuCEM a changé l'image de Marseille et le front de mer de la Joliette, où les anciens docks ont été transformés en bureaux et commerces."],
 "Mus%C3%A9e_des_Civilisations_de_l%27Europe_et_de_la_M%C3%A9diterran%C3%A9e",lat=43.2965,lon=5.3610,access="Fermé le mardi"),
A("patrimoine","Saint-Victor, les cryptes des premiers chrétiens","Ve siècle · Rive sud du Vieux-Port",
 "Sous l'église fortifiée se cachent des cryptes du Ve siècle, des sarcophages paléochrétiens et la mémoire d'une des plus anciennes abbayes de Gaule, fondée par Jean Cassien.",
 "L'abbaye Saint-Victor, fondée vers 415 sur la rive sud du Vieux-Port, est l'un des plus anciens lieux de culte chrétiens de France.",
 ["Jean Cassien, moine venu d'Orient, installe une communauté près d'une carrière où l'on vénérait des martyrs, dont saint Victor, soldat romain exécuté vers 290. Les cryptes conservent des sarcophages des IVe et Ve siècles, une chapelle rupestre et la « Vierge noire » de Notre-Dame-de-Confession, en noyer, du XIIIe siècle.",
  "L'église haute, reconstruite aux XIIe et XIVe siècles, ressemble à une forteresse : murs épais, tours crénelées, pour résister aux attaques venues de la mer. L'abbaye, très puissante au Moyen Âge, a possédé des terres jusqu'en Espagne et en Sardaigne.",
  "Chaque 2 février, pour la Chandeleur, la Vierge noire est portée en procession jusqu'au Four des Navettes, où l'archevêque bénit les navettes, biscuits en forme de barque."],
 "Abbaye_Saint-Victor_de_Marseille",lat=43.2900,lon=5.3657,access="Libre, tous les jours ; cryptes payantes",protection="Monument historique, 1840"),
A("patrimoine","Le palais Longchamp, un monument à l'eau","1862-1869 · 4e arrondissement",
 "Ce n'est ni un palais ni une résidence : c'est un château d'eau. Marseille a mis quinze ans à faire venir l'eau de la Durance par un canal de 80 kilomètres, et l'a célébrée avec des taureaux, des fontaines et deux musées.",
 "Le palais Longchamp, inauguré en 1869, commémore l'arrivée de l'eau de la Durance à Marseille par le canal creusé de 1839 à 1854.",
 ["Jusqu'au milieu du XIXe siècle, Marseille manque d'eau et subit les épidémies de choléra. L'ingénieur Franz Mayor de Montricher construit un canal de 80 kilomètres depuis la Durance, avec l'aqueduc de Roquefavour, le plus haut pont-aqueduc du monde à l'époque. Le château d'eau, au débouché du canal, devait être un simple réservoir.",
  "L'architecte Espérandieu, celui de Notre-Dame-de-la-Garde, en fait un monument : une colonnade en arc de cercle, une cascade monumentale encadrée de taureaux de pierre et de figures allégoriques, et deux ailes abritant le musée des Beaux-Arts et le muséum d'Histoire naturelle.",
  "Le parc, derrière le palais, a abrité un jardin zoologique jusqu'en 1987 ; les cages sont devenues des aires de jeu. L'observatoire astronomique, déplacé en 1864, est au fond du parc."],
 "Palais_Longchamp",lat=43.3045,lon=5.3950,access="Parc libre ; musées fermés le lundi",protection="Monument historique, 1997"),

# ================= SPORT =================
A("sport","La seule Ligue des champions française","26 mai 1993 · Munich, puis le Vieux-Port",
 "Une tête de Basile Boli à la 43e minute contre le grand Milan AC, et l'Olympique de Marseille devient le seul club français à avoir gagné la Coupe d'Europe. Il l'est toujours.",
 "Le 26 mai 1993, à Munich, l'OM bat le Milan AC 1-0 en finale de la Ligue des champions. Trente ans plus tard, aucun autre club français n'a soulevé le trophée.",
 ["Bernard Tapie a construit en six ans une équipe de stars : Papin, Waddle, Boli, Deschamps, Barthez, Desailly, Völler, et le but marseillais vient sur un corner d'Abedi Pelé repris de la tête par Basile Boli. Le Milan de Van Basten, Baresi et Maldini, invaincu en championnat, ne revient pas.",
  "La fête sur le Vieux-Port dure toute la nuit. Deux semaines plus tard, l'affaire VA-OM éclate : le club perd son titre de champion de France, est relégué et privé de Coupe intercontinentale, mais la victoire européenne n'est pas remise en cause.",
  "Le stade Vélodrome, agrandi pour l'Euro 2016, accueille 67 000 spectateurs, le plus grand stade de club de France. Le « jamais sans mon OM » et la ferveur du virage sud sont réputés dans toute l'Europe."],
 "Olympique_de_Marseille",lat=43.2697,lon=5.3957,
 links=[L("documentaire","« À jamais les premiers » (2023)","https://fr.wikipedia.org/wiki/Olympique_de_Marseille","Film sur la saison 1992-1993")]),
A("sport","Le Vélodrome, 67 000 places et un vrai vélodrome","1937 · Boulevard Michelet",
 "Le stade a été construit en 1937 avec une piste cyclable autour de la pelouse, d'où son nom. La piste a disparu, le nom est resté, et le toit ondulé de 2014 se voit depuis les collines.",
 "Le stade Vélodrome, inauguré le 13 juin 1937, est le plus grand stade de club de France avec 67 394 places.",
 ["Il est construit pour la Coupe du monde 1938, avec une piste cyclable de 500 mètres ceinturant le terrain : des Six Jours de Marseille s'y disputent dans les années 1940 et 1950. La piste est supprimée en 1985 pour rapprocher les tribunes de la pelouse.",
  "Agrandi pour la Coupe du monde 1998 et couvert pour l'Euro 2016 par un toit en voile ondulée de 65 000 m², il a accueilli des finales de Coupe de France, des matchs de rugby du XV de France, les demi-finales de la Coupe du monde de rugby 2023 et le tournoi olympique de football en 2024.",
  "Son record d'affluence, 65 894 spectateurs, date d'un OM-PSG en 2022 ? Le record officiel reste celui du match contre le PSG en février 2022 ; la rivalité entre les deux clubs, née dans les années 1990, est le « classique » du football français."],
 "Stade_V%C3%A9lodrome",lat=43.2697,lon=5.3957),

# ================= GASTRONOMIE =================
A("gastronomie","La bouillabaisse et sa charte","1980 · Vieux-Port et calanques",
 "Soupe de pêcheurs faite des poissons invendables, la bouillabaisse est devenue le plat le plus cher de la ville. Onze restaurateurs ont signé en 1980 une charte pour fixer ce qui a le droit de porter ce nom.",
 "La bouillabaisse, plat emblématique de Marseille, est encadrée depuis 1980 par une charte signée par des restaurateurs du Vieux-Port, excédés des contrefaçons.",
 ["À l'origine, les pêcheurs faisaient bouillir les poissons de roche abîmés ou trop petits pour la vente, avec de l'huile d'olive, de l'ail, du safran et des tomates. « Quand ça bout, tu baisses » : le nom viendrait du geste. Le plat se sert en deux temps, le bouillon sur des croûtons frottés d'ail et tartinés de rouille, puis les poissons découpés devant le client.",
  "La charte impose au moins quatre poissons parmi rascasse, vive, galinette, saint-pierre, baudroie, congre, et interdit les coquillages. Le prix, de 60 à 90 euros par personne dans les maisons signataires, s'explique par la rareté des poissons de roche.",
  "On la mange au Vieux-Port, au vallon des Auffes ou dans les restaurants des calanques ; les Marseillais eux-mêmes la réservent aux grandes occasions."],
 "Bouillabaisse"),
A("gastronomie","Le pastis, né d'une interdiction","1932 · Toute la ville",
 "L'absinthe interdite en 1915, Paul Ricard invente en 1932 un anisé à 45 degrés qu'il baptise « le vrai pastis de Marseille ». Un siècle plus tard, il se boit à l'apéritif dans toute la France, avec cinq volumes d'eau.",
 "Le pastis tel qu'on le connaît naît à Marseille en 1932, quand Paul Ricard, fils de négociant en vins, met au point une recette d'anis, réglisse et plantes de Provence.",
 ["Après l'interdiction de l'absinthe, les anisés sont tolérés à condition de ne pas dépasser 40 degrés. En 1932, la limite passe à 45, et Ricard, qui fabriquait son produit en douce, lance sa marque avec un sens aigu de la publicité : carafes, cendriers, voitures peintes, et le slogan du « vrai pastis de Marseille ». Son concurrent Pernod, parisien, répond avec le 51.",
  "Le mot vient du provençal « pastis », mélange. On le sert avec de l'eau fraîche, jamais glacée, un volume pour cinq, et le liquide se trouble, c'est le louchissement. Les Marseillais commandent un « jaune » et le boivent le plus souvent sur le Vieux-Port, au soleil.",
  "Paul Ricard a ensuite acheté les îles de Bendor et des Embiez, et fondé le circuit automobile qui porte son nom au Castellet."],
 "Pastis"),
A("gastronomie","Les navettes de la Chandeleur","Depuis 1781 · Rue Sainte, Four des Navettes",
 "Un biscuit sec à la fleur d'oranger, en forme de barque, cuit dans le plus vieux four de la ville depuis 1781. Chaque 2 février, l'archevêque vient le bénir.",
 "La navette est le biscuit marseillais par excellence : une pâte dure parfumée à la fleur d'oranger, modelée en forme de petite barque, vendue à la douzaine au Four des Navettes, rue Sainte, depuis 1781.",
 ["Sa forme rappellerait la barque des saintes Maries, Marie Jacobé et Marie Salomé, accostées en Camargue selon la légende provençale, ou la Vierge noire de Saint-Victor. Elle se conserve des mois et se trempe dans le café.",
  "Le 2 février, jour de la Chandeleur, la procession de l'abbaye Saint-Victor descend jusqu'au four, où l'archevêque bénit les navettes et le feu de l'année. Les Marseillais en achètent par dizaines ce jour-là.",
  "La boulangerie, toujours en activité, fabrique les navettes au feu de bois selon une recette tenue secrète, et vend aussi pompes à l'huile et oreillettes."],
 "Navette_(biscuit)",lat=43.2910,lon=5.3665),

# ================= LEGENDE =================
A("legende","Gyptis et Protis, le mariage fondateur","Vers 600 av. J.-C. · Vieux-Port",
 "Le jour où les Grecs débarquent, le roi des Ségobriges marie sa fille. Elle doit choisir un époux en tendant une coupe : elle la tend à l'étranger. Marseille est née d'un coup de foudre, dit la légende.",
 "Selon le récit rapporté par Justin et Aristote, Marseille serait née du mariage de Gyptis, fille du roi ligure Nann, et de Protis, chef des navigateurs phocéens.",
 ["Les Phocéens, dit la légende, abordent la côte le jour où le roi Nann marie sa fille selon la coutume : la jeune femme offre une coupe d'eau à celui qu'elle choisit parmi les prétendants réunis au banquet. Gyptis la tend à Protis, l'étranger invité par courtoisie. Le roi accepte et offre aux Grecs la calanque où ils fondent Massalia.",
  "L'histoire a été reprise par Thucydide, Justin et Aristote dans des versions proches ; les historiens y voient le souvenir d'une alliance entre colons et indigènes, scellée par un mariage, comme souvent dans la colonisation grecque.",
  "Gyptis et Protis sont partout à Marseille : un ferry-boat du Vieux-Port, des rues, un centre commercial, et une fresque de l'hôtel de ville."],
 "Gyptis_et_Protis"),
A("legende","Le ferry-boat, 283 mètres de traversée","Depuis 1880 · Vieux-Port",
 "C'est la ligne maritime la plus courte du monde, dit-on : 283 mètres entre la place aux Huiles et l'hôtel de ville. Pagnol lui a donné son accent : « le fériboîte ».",
 "Le ferry-boat du Vieux-Port relie les deux rives depuis 1880. César, dans « Marius », en fait l'objet d'une dispute mémorable sur la façon de prononcer son nom.",
 ["Le premier bateau, à vapeur, est mis en service par la ville pour éviter aux Marseillais le tour du port à pied. Plusieurs générations se succèdent ; le ferry-boat « César », de 1953, a été restauré et sert encore pour les grandes occasions. Depuis 2010, un bateau électrique solaire assure la navette, gratuite.",
  "Dans « Marius », le capitaine Escartefigue commande le ferry-boat et refuse la lettre de change pour cause de mal de mer, cinq fois par jour sur 283 mètres. La scène a fixé l'image du marin d'eau douce marseillais.",
  "La traversée dure trois minutes. Pour les enfants de la ville, c'est le premier bateau."],
 "Ferry-boat_de_Marseille",lat=43.2957,lon=5.3720),

# ================= NATURE =================
A("nature","Les calanques, premier parc national de ville","2012 · Du Pharo à Cassis",
 "Vingt kilomètres de falaises blanches plongeant dans une eau turquoise, à vingt minutes du centre : les calanques forment le premier parc national d'Europe à toucher une grande ville. Un million de visiteurs par an, des réservations obligatoires l'été à Sugiton.",
 "Le parc national des Calanques, créé en 2012, s'étend sur 8 500 hectares de terre et 43 500 hectares de mer entre Marseille, Cassis et La Ciotat.",
 ["Les calanques sont d'anciennes vallées creusées dans le calcaire urgonien pendant les glaciations, puis envahies par la mer. Sormiou, Morgiou, Sugiton, En-Vau, Port-Pin : chacune a son caractère, ses cabanons de pêcheurs, ses voies d'escalade et son sentier d'accès. La grotte Cosquer, à Morgiou, abrite des peintures de 27 000 ans accessibles seulement par un siphon sous-marin.",
  "Le massif est fermé en été dès que le vent et la sécheresse rendent le risque d'incendie élevé ; depuis 2022, l'accès à Sugiton est soumis à réservation gratuite pour limiter l'érosion. Le parc protège le mérou, le puffin et l'aigle de Bonelli.",
  "On y accède en bus depuis le centre, à pied depuis Luminy ou Callelongue, ou en bateau depuis le Vieux-Port. Les Marseillais y pique-niquent, y pêchent et y nagent toute l'année."],
 "Parc_national_des_Calanques",lat=43.2120,lon=5.4450),
A("nature","Le mistral, cent jours par an","Toute l'année · Toute la ville",
 "Il descend la vallée du Rhône, dégage le ciel et fait claquer les volets. Les Marseillais lui attribuent les maux de tête, le bleu du ciel et leur mauvaise humeur.",
 "Le mistral, vent du nord-ouest, souffle sur Marseille une centaine de jours par an, avec des rafales dépassant régulièrement 100 km/h.",
 ["Il naît d'une différence de pression entre l'anticyclone de l'Atlantique et une dépression sur le golfe de Gênes ; l'air s'engouffre dans le couloir rhodanien et accélère entre les Alpes et le Massif central. Marseille, à la sortie du couloir, le reçoit de plein fouet. Il dure, dit le dicton, trois, six ou neuf jours.",
  "C'est lui qui donne au ciel marseillais sa pureté et aux calanques leur lumière ; il assèche aussi la garrigue et attise les incendies. Le record mesuré à Marignane, 137 km/h, date de 1947 ? Les rafales supérieures à 130 km/h sont rares mais régulièrement enregistrées.",
  "Les maisons de pêcheurs tournent le dos au nord, les platanes du cours Mirabeau à Aix penchent vers le sud, et les cabanons des calanques ont des volets épais : tout le paysage est dessiné par ce vent."],
 "Mistral_(vent)"),
]
# Nettoyage de deux phrases hésitantes glissées dans le brouillon
for a in arts:
    a["body"]=[p.replace("Une statue le représente à Marseille, place de l'Opéra ? Non : c'est à Carry-le-Rouet, où il avait sa villa, que la ville l'a honoré ; à Marseille, c'est une place du 1er arrondissement qui porte son nom.","Une place du 1er arrondissement porte son nom à Marseille, et une statue le représente à Carry-le-Rouet, où il possédait une villa.")
               .replace("Son record d'affluence, 65 894 spectateurs, date d'un OM-PSG en 2022 ? Le record officiel reste celui du match contre le PSG en février 2022 ; la rivalité entre les deux clubs, née dans les années 1990, est le « classique » du football français.","Son record d'affluence a été établi lors d'un match contre le PSG ; la rivalité entre les deux clubs, née dans les années 1990, est le « classique » du football français.")
               .replace("Le record mesuré à Marignane, 137 km/h, date de 1947 ? Les rafales supérieures à 130 km/h sont rares mais régulièrement enregistrées.","Les rafales supérieures à 130 km/h sont rares mais régulièrement enregistrées à Marignane.") for p in a["body"]]
place={"id":"marseille-13055","insee":"13055","name":"Marseille","dept":"Bouches-du-Rhône","kind":"commune","lat":43.2965,"lon":5.3698,"anecdotes":arts}
json.dump(place,open("communes/13055.json","w"),ensure_ascii=False,indent=1)
idx=json.load(open("index.json"))
idx["communes"]["13055"]={"name":"Marseille","count":len(arts),"updated":"2026-10-05"}
json.dump(idx,open("index.json","w"),ensure_ascii=False,indent=1)
from collections import Counter
print(len(arts), Counter(a["category"] for a in arts))
