import json, os
W="https://fr.wikipedia.org/wiki/"
def A(cat,title,label,teaser,lead,body,wiki,more=None,timeline=None,lat=None,lon=None,links=None,access=None,protection=None):
    return {"category":cat,"title":title,"label":label,"teaser":teaser,"lead":lead,"text":lead,"body":body,"more":more or [],"timeline":timeline,"links":links,"wiki":wiki,"source":W+wiki,"lat":lat,"lon":lon,"access":access,"protection":protection}
L=lambda kind,title,url,note=None:{"kind":kind,"title":title,"url":url,"note":note}

lyon=[
A("politique","Doucet réélu de 2 762 voix face à Aulas","Mars 2026 · Hôtel de ville",
 "L'ancien patron de l'Olympique lyonnais était donné gagnant par tous les sondages. Le maire écologiste sortant l'emporte au second tour avec 50,7 % des voix, soit moins de 3 000 bulletins d'écart.",
 "Grégory Doucet, maire écologiste de Lyon depuis 2020, a été réélu le 22 mars 2026 avec 50,7 % des voix contre 49,3 % à Jean-Michel Aulas, soit 2 762 voix d'écart.",
 ["Ancien directeur d'une organisation humanitaire, inconnu du grand public avant 2020, Doucet avait pris la ville à la faveur de la vague écologiste et de la division de la droite. Son mandat a été marqué par la zone à faibles émissions, la piétonnisation, la réduction de la place de la voiture et une opposition frontale avec le gouvernement sur la sécurité.",
  "Jean-Michel Aulas, président de l'OL pendant trente-neuf ans, entre en campagne en 2025 avec une notoriété écrasante et jusqu'à quinze points d'avance dans les enquêtes. L'écart fond dans les dernières semaines ; il conteste le résultat et dépose un recours.",
  "Lyon est l'une des trois plus grandes villes de France, avec Paris et Marseille, à être restées à gauche en 2026. Le scrutin s'est tenu pour la première fois selon la nouvelle loi PLM, avec deux bulletins distincts, l'un pour le conseil municipal, l'autre pour les arrondissements."],
 "Gr%C3%A9gory_Doucet",lat=45.7675,lon=4.8336),
A("politique","Collomb, de la mairie au ministère de l'Intérieur","2001-2017 · Hôtel de ville",
 "Seize ans maire, puis ministre de l'Intérieur du premier gouvernement Macron, démissionnaire après l'affaire Benalla, revenu à Lyon pour la perdre en 2020 : la trajectoire de Gérard Collomb résume vingt ans de politique lyonnaise.",
 "Gérard Collomb a été maire de Lyon de 2001 à 2017, puis ministre de l'Intérieur de 2017 à 2018.",
 ["Professeur de lettres classiques, il prend la ville au centriste Raymond Barre en 2001 et la garde seize ans, en construisant un système d'alliances au centre. Il obtient le classement UNESCO en 1998 déjà engagé, lance la Confluence, le Musée des Confluences, les berges du Rhône et, en 2015, la Métropole de Lyon, collectivité unique qui fusionne la ville et le département sur son territoire, cas unique en France.",
  "Premier grand élu socialiste à soutenir Emmanuel Macron, il devient ministre de l'Intérieur en 2017. Il démissionne en octobre 2018 après l'affaire Benalla et des critiques sur sa gestion, revient à la mairie, puis se retire pour la métropole en 2020 : la gauche écologiste remporte les deux.",
  "Il meurt en novembre 2023 à 76 ans. Son successeur à la métropole, Bruno Bernard, puis Grégory Doucet à la ville, ont été réélus en 2026."],
 "G%C3%A9rard_Collomb"),
A("faits_divers","Le procès Barbie, premier pour crimes contre l'humanité","Mai-juillet 1987 · Palais de justice, quai Romain-Rolland",
 "Le chef de la Gestapo de Lyon, extradé de Bolivie en 1983, est jugé dans la ville qu'il a terrorisée. Le procès est filmé, une première en France, et fixe la définition juridique du crime contre l'humanité.",
 "Du 11 mai au 4 juillet 1987, Klaus Barbie, chef de la Gestapo de Lyon de 1942 à 1944, est jugé pour crimes contre l'humanité et condamné à la réclusion criminelle à perpétuité.",
 ["Barbie a dirigé la section IV de la Gestapo, installée à l'hôtel Terminus puis avenue Berthelot. Il est responsable de la torture et de la mort de Jean Moulin, arrêté à Caluire en juin 1943, et de la rafle des enfants juifs d'Izieu en avril 1944, quarante-quatre enfants et sept adultes déportés et gazés. Après la guerre, utilisé par les services américains puis réfugié en Bolivie sous le nom d'Altmann, il est retrouvé par Beate et Serge Klarsfeld et extradé en 1983.",
  "Le procès, présidé par André Cerdini, est le premier en France pour crimes contre l'humanité. Une loi votée en 1985 permet de le filmer intégralement pour les archives historiques ; les 185 heures d'enregistrement sont consultables. Barbie, défendu par Jacques Vergès, quitte la salle après quelques audiences.",
  "La Cour de cassation avait précisé en 1985 que le crime contre l'humanité pouvait viser aussi des résistants, élargissant la définition. Barbie meurt en prison à Lyon en 1991."],
 "Proc%C3%A8s_de_Klaus_Barbie",lat=45.7600,lon=4.8277,
 links=[L("documentaire","Les archives filmées du procès (INA)","https://www.ina.fr/recherche?q=proc%C3%A8s+Barbie","185 heures d'audience enregistrées"),
        L("film","« Hôtel Terminus » de Marcel Ophuls (1988)","https://fr.wikipedia.org/wiki/H%C3%B4tel_Terminus","Oscar du meilleur documentaire")]),
A("histoire","Le premier film de l'histoire, tourné à Montplaisir","19 mars 1895 · Rue du Premier-Film",
 "Cinquante secondes d'ouvriers sortant d'une usine de plaques photographiques. Les frères Lumière viennent d'inventer le cinéma, dans leur propre cour.",
 "« La Sortie de l'usine Lumière à Lyon », tourné le 19 mars 1895 rue Saint-Victor, à Montplaisir, est considéré comme le premier film de l'histoire du cinéma.",
 ["Antoine Lumière et ses fils Auguste et Louis fabriquent des plaques photographiques et emploient plusieurs centaines d'ouvriers. Louis met au point le Cinématographe, appareil qui filme, développe et projette. Le premier essai montre les ouvrières et ouvriers franchissant le portail de l'usine, filmé à hauteur d'homme, en un seul plan de cinquante secondes.",
  "La première projection publique payante a lieu le 28 décembre 1895 au Grand Café, à Paris, mais c'est à Lyon que tout a été conçu et tourné. Les Lumière réaliseront plus de 1 400 vues en quelques années et enverront des opérateurs dans le monde entier.",
  "Le hangar du premier film, seul vestige de l'usine, a été sauvé de la démolition et abrite aujourd'hui l'Institut Lumière, avec la villa familiale. Le festival Lumière, créé en 2009, remet chaque octobre un prix aux grands cinéastes."],
 "La_Sortie_de_l%27usine_Lumi%C3%A8re_%C3%A0_Lyon",lat=45.7450,lon=4.8700),
A("histoire","Les canuts, première révolte ouvrière de l'ère industrielle","1831 et 1834 · Croix-Rousse",
 "« Vivre en travaillant ou mourir en combattant » : les tisserands de la soie prennent Lyon en novembre 1831 pour un tarif garanti. L'armée reprend la ville, et l'Europe découvre la question sociale.",
 "Les révoltes des canuts, en novembre 1831 et avril 1834, sont parmi les premières insurrections ouvrières de l'ère industrielle.",
 ["Les canuts sont les tisserands de la soie de la Croix-Rousse, travailleurs à domicile sur des métiers Jacquard qui exigent des plafonds de quatre mètres. Payés à la pièce par les négociants, les « soyeux », ils obtiennent en octobre 1831 un tarif minimum, aussitôt dénoncé. Le 21 novembre, ils descendent sur la ville aux cris de « vivre en travaillant ou mourir en combattant » et la contrôlent trois jours. L'armée revient avec 20 000 hommes.",
  "En avril 1834, une seconde révolte, plus politique, dure six jours, la « sanglante semaine » : plus de 300 morts. La répression est sévère ; les procès se tiennent à Paris.",
  "Les canuts ont laissé les traboules, passages à travers les immeubles qui permettaient de transporter les pièces de soie à l'abri de la pluie, et que la Résistance utilisera un siècle plus tard."],
 "R%C3%A9volte_des_canuts",lat=45.7745,lon=4.8320),
A("patrimoine","Le Vieux Lyon sauvé d'une autoroute","1964 · Saint-Jean, Saint-Paul, Saint-Georges",
 "Dans les années 1950, un projet de voie rapide devait traverser le quartier Renaissance, jugé insalubre. Il est devenu en 1964 le premier secteur sauvegardé de France.",
 "Le Vieux Lyon, l'un des plus vastes ensembles Renaissance d'Europe, a été classé premier secteur sauvegardé de France en 1964, en application de la loi Malraux.",
 ["Après-guerre, le quartier est un taudis : immeubles surpeuplés, sans confort, que la municipalité envisage de raser en partie pour une pénétrante automobile le long de la Saône. Des associations, dont la Renaissance du Vieux Lyon, obtiennent qu'André Malraux, ministre des Affaires culturelles, applique ici sa loi de 1962 sur les secteurs sauvegardés.",
  "Les 24 hectares protégés regroupent des hôtels du XVe et du XVIe siècle bâtis par les banquiers et marchands florentins installés à Lyon pour les foires : galeries à l'italienne, tours d'escalier, cours intérieures comme celle de la Tour rose. Les traboules relient les rues parallèles à travers les immeubles.",
  "Le classement UNESCO de 1998 a étendu la protection à la Croix-Rousse, à la presqu'île et à Fourvière, soit 500 hectares."],
 "Vieux_Lyon",lat=45.7627,lon=4.8275),
A("gastronomie","Les mères lyonnaises, cuisinières des grandes maisons","XIXe-XXe siècle · Toute la ville",
 "Cuisinières des familles bourgeoises, elles ouvrent leurs propres restaurants quand leurs patrons les licencient. La mère Brazier sera la première femme trois étoiles, et le maître de Paul Bocuse.",
 "Les « mères lyonnaises », cuisinières devenues restauratrices entre la fin du XIXe siècle et les années 1960, ont fondé la réputation gastronomique de Lyon.",
 ["Employées dans les maisons bourgeoises, elles se mettent à leur compte lors des crises économiques, dans de petits établissements de quartier : la mère Guy, la mère Fillioux, la mère Brazier, la mère Bourgeois. Leur cuisine est celle du produit et de la cuisson juste : volaille de Bresse demi-deuil, quenelles, gratin de cardons.",
  "Eugénie Brazier obtient en 1933 trois étoiles au Michelin pour deux établissements à la fois, exploit inégalé à l'époque et première femme à y parvenir. Paul Bocuse, apprenti chez elle, dira avoir tout appris dans sa cuisine.",
  "Les bouchons, ces petits restaurants aux nappes à carreaux servant tablier de sapeur, andouillette et cervelle de canut, perpétuent cette tradition populaire ; une association labellise les authentiques."],
 "M%C3%A8res_lyonnaises"),
]

toulouse=[
A("politique","Moudenc, la droite qui tient le Capitole","Depuis 2014 · Place du Capitole",
 "Battu en 2008, revenu en 2014, réélu en 2020 puis en 2026 avec 53,8 % face à une alliance LFI-PS : Jean-Luc Moudenc a quitté Les Républicains en 2022 en dénonçant leur droitisation.",
 "Jean-Luc Moudenc est maire de Toulouse depuis 2014, après un premier mandat de 2004 à 2008.",
 ["Successeur de Philippe Douste-Blazy en 2004, il est battu en 2008 par le socialiste Pierre Cohen, puis reprend la ville en 2014. Ses mandats sont marqués par la troisième ligne de métro, le téléphérique urbain Téléo, et une politique de sécurité qui lui vaut des critiques de la gauche sur la vidéosurveillance.",
  "En novembre 2022, il quitte Les Républicains en regrettant publiquement la « droitisation » du parti, et se présente depuis sans étiquette, soutenu au centre droit.",
  "Le 22 mars 2026, il est réélu avec 53,8 % des voix face à l'alliance de gauche et de La France insoumise menée par le député François Piquemal. Toulouse reste l'une des rares grandes villes tenues par la droite."],
 "Jean-Luc_Moudenc",lat=43.6045,lon=1.4440),
A("faits_divers","AZF : 31 morts et une ville soufflée","21 septembre 2001 · Route d'Espagne",
 "Dix jours après le 11-Septembre, 300 tonnes de nitrate d'ammonium explosent dans un hangar. Un cratère de 70 mètres, 31 morts, 30 000 logements endommagés, et vingt ans de procédures.",
 "Le 21 septembre 2001 à 10 h 17, l'usine chimique AZF, au sud de Toulouse, explose. Le bilan est de 31 morts et plus de 2 500 blessés.",
 ["Le stock de nitrate d'ammonium déclassé entreposé dans le hangar 221 détone, creusant un cratère de 70 mètres de diamètre et 7 de profondeur. L'onde de choc, perçue à des dizaines de kilomètres, souffle les vitres de la moitié de la ville, endommage 30 000 logements, des écoles, des hôpitaux. Dix jours après les attentats du 11 septembre, l'hypothèse terroriste circule immédiatement.",
  "L'enquête conclut à un accident : le mélange accidentel de nitrate avec un produit chloré. La thèse est contestée par des associations et par Total, propriétaire via Grande Paroisse. Après une relaxe en première instance en 2009, la cour d'appel de Toulouse condamne en 2012, la Cassation annule, et en 2017 une nouvelle cour d'appel condamne Grande Paroisse et l'ancien directeur ; la Cour de cassation confirme en 2019, dix-huit ans après les faits.",
  "Le site est devenu le Cancéropôle et un mémorial. La catastrophe a donné la loi Bachelot de 2003 sur les risques technologiques et les plans de prévention autour des sites Seveso."],
 "Explosion_de_l%27usine_AZF_de_Toulouse",lat=43.5700,lon=1.4150,
 links=[L("documentaire","Documentaires et archives sur AZF","https://www.ina.fr/recherche?q=AZF+Toulouse","Archives INA")]),
A("histoire","Le pastel, l'or bleu qui a bâti les hôtels roses","XVe-XVIe siècle · Centre-ville",
 "Pendant un siècle, le bleu tiré d'une plante du Lauragais a enrichi Toulouse au point que ses marchands se sont fait construire des palais. L'indigo des Indes a tout emporté en vingt ans.",
 "Entre 1460 et 1560, le commerce du pastel, plante tinctoriale produisant un bleu profond, a fait la fortune de Toulouse et du Lauragais.",
 ["Les feuilles d'isatis tinctoria sont broyées et roulées en boules, les « coques », d'où le nom de « pays de cocagne » donné à la région. Vendu dans toute l'Europe, le pastel enrichit des marchands qui se font bâtir des hôtels particuliers en brique et pierre : hôtel d'Assézat, hôtel de Bernuy, hôtel Delfau, dont les tours d'escalier rivalisent de hauteur.",
  "L'arrivée massive de l'indigo des Indes, dix fois plus concentré, ruine la filière en quelques décennies ; les guerres de Religion achèvent le déclin. Jean de Bernuy, qui avait servi de caution à la rançon de François Ier, meurt ruiné.",
  "Le pastel est réapparu depuis les années 1990 en production artisanale, pour la teinture et les cosmétiques. L'hôtel d'Assézat abrite la fondation Bemberg."],
 "Pastel_des_teinturiers",lat=43.6000,lon=1.4420),
A("insolite","Airbus, l'A380 et les convois de nuit","Depuis 1970 · Blagnac et routes du Gers",
 "Les tronçons de l'A380 arrivaient par bateau à Bordeaux, puis par convois routiers géants qui traversaient les villages du Gers la nuit, à 25 km/h, sur des routes élargies exprès.",
 "Toulouse est la capitale européenne de l'aéronautique : Airbus y assemble ses avions depuis 1970, dans la continuité de Latécoère et de l'Aéropostale.",
 ["L'histoire commence avec Pierre-Georges Latécoère, qui construit des avions à Montaudran dès 1917 et lance les lignes postales vers l'Afrique et l'Amérique du Sud, avec Mermoz, Guillaumet et Saint-Exupéry. Sud-Aviation y fabrique la Caravelle, puis Concorde, dont le premier vol a lieu à Toulouse le 2 mars 1969.",
  "Pour l'A380, dont les tronçons sont fabriqués en Allemagne, en Espagne et au Royaume-Uni, un « itinéraire à grand gabarit » a été aménagé : arrivée par barge à Langon, puis 240 kilomètres de route de nuit à travers le Gers, avec des villages dont les ronds-points et les lignes électriques ont été modifiés. Les convois attiraient des centaines de curieux.",
  "La production de l'A380 s'est arrêtée en 2021 ; l'itinéraire sert encore pour d'autres programmes. La piste de Montaudran est devenue un parc et la Halle de La Machine."],
 "Airbus_A380",lat=43.6290,lon=1.3650),
A("patrimoine","Saint-Sernin, la plus grande église romane d'Europe","XIe-XIIe siècle · Place Saint-Sernin",
 "115 mètres de long, un clocher à cinq étages, et des reliques qui en faisaient une étape majeure du chemin de Saint-Jacques. Viollet-le-Duc l'a restaurée ; on a défait une partie de son travail au XXe siècle.",
 "La basilique Saint-Sernin, construite à partir de 1080, est la plus grande église romane conservée d'Europe.",
 ["Elle abrite le tombeau de saint Saturnin, premier évêque de Toulouse martyrisé en 250 en étant traîné par un taureau, et un ensemble de reliques offert par Charlemagne qui en fit un but de pèlerinage majeur sur la via Tolosana vers Compostelle. Le chevet à chapelles rayonnantes et le clocher octogonal à cinq étages de baies sont caractéristiques du roman méridional.",
  "Viollet-le-Duc la restaure au XIXe siècle en ajoutant des toitures aiguës et des décors qu'il croyait fidèles. Entre 1980 et 1990, une « dé-restauration » controversée a supprimé une partie de ces ajouts pour revenir à l'état antérieur, au prix d'un débat vif chez les historiens de l'art.",
  "La basilique est inscrite au patrimoine mondial au titre des chemins de Saint-Jacques depuis 1998."],
 "Basilique_Saint-Sernin_de_Toulouse",lat=43.6082,lon=1.4418,access="Libre, tous les jours",protection="Monument historique, 1840 ; UNESCO, 1998"),
]

lille=[
A("politique","Deslandes succède à Aubry après vingt-trois ans","2025-2026 · Hôtel de ville",
 "Martine Aubry a quitté la mairie en 2025 au profit de son premier adjoint, qui a ensuite remporté le scrutin de 2026. Lille n'a pas changé de bord depuis Pierre Mauroy, en 1973.",
 "Arnaud Deslandes est maire de Lille depuis mars 2025, après la démission de Martine Aubry, et a été élu dans les urnes en mars 2026.",
 ["Martine Aubry, ministre du Travail des 35 heures et première secrétaire du Parti socialiste, avait pris la mairie en 2001 à la suite de Pierre Mauroy, maire pendant vingt-huit ans et Premier ministre de Mitterrand. Elle y est restée vingt-trois ans, marquée par Lille 2004 capitale européenne de la culture, la rénovation de Wazemmes et de Fives, et une opposition constante à l'aile droite de son parti.",
  "En mars 2025, à 74 ans, elle démissionne et laisse la place à son premier adjoint Arnaud Deslandes, qui doit affronter un an plus tard le scrutin municipal.",
  "Le 22 mars 2026, il conserve la mairie avec une avance confortable face à la liste de La France insoumise. Lille est socialiste sans interruption depuis 1973."],
 "Arnaud_Deslandes",lat=50.6366,lon=3.0635),
A("histoire","La braderie, deux millions de visiteurs et des tas de moules","Depuis le Moyen Âge · Tout le centre",
 "Le premier week-end de septembre, cent kilomètres d'étals et des restaurants qui empilent leurs coquilles de moules sur le trottoir pour voir qui aura le plus gros tas.",
 "La braderie de Lille, qui se tient le premier week-end de septembre, est l'un des plus grands marchés aux puces d'Europe, avec environ deux millions de visiteurs.",
 ["Son origine remonte au Moyen Âge : les domestiques avaient le droit, une fois l'an, de vendre les vieux vêtements de leurs maîtres. La tradition se maintient et devient au XIXe siècle un déballage général, où chacun peut vendre sans autorisation ni taxe pendant trente-trois heures, de 14 heures le samedi à 23 heures le dimanche.",
  "Les moules-frites sont le plat obligatoire, et les restaurants entassent leurs coquilles vides devant leur porte : le concours du plus haut tas est officieux mais sérieusement disputé. Le semi-marathon ouvre la braderie le samedi matin.",
  "L'édition 2016 a été annulée pour raisons de sécurité après les attentats, et celles de 2020 et 2021 à cause du Covid ; le retour en 2022 a été suivi par plus d'un million de personnes."],
 "Braderie_de_Lille",lat=50.6366,lon=3.0635),
A("personnalites","De Gaulle est né rue Princesse","1890 · 9, rue Princesse",
 "Il est né chez sa grand-mère maternelle, dans une maison bourgeoise du Vieux-Lille, et y revenait chaque été. Sa famille était issue de la bourgeoisie industrielle du Nord.",
 "Charles de Gaulle est né le 22 novembre 1890 au 9, rue Princesse, à Lille, dans la maison de ses grands-parents maternels.",
 ["Son père, Henri de Gaulle, professeur, vivait à Paris, mais sa mère Jeanne Maillot revenait accoucher dans sa famille lilloise, propriétaire d'une fabrique de tulle à Fives. L'enfant passe ses vacances dans le Nord jusqu'à l'adolescence.",
  "La maison, achetée en 1983 par une fondation, est devenue un musée qui conserve le berceau, la robe de baptême, et la DS criblée de balles de l'attentat du Petit-Clamart en 1962.",
  "La ville lui a donné le nom de sa place principale, l'ancienne Grand-Place, rebaptisée place du Général-de-Gaulle en 1944, que les Lillois continuent d'appeler la Grand-Place."],
 "Maison_natale_de_Charles_de_Gaulle",lat=50.6430,lon=3.0616,access="Fermé le lundi et le mardi"),
A("histoire","Le siège de 1792 et le boulet de la Grand-Place","Septembre-octobre 1792 · Grand-Place",
 "Pendant neuf jours, les Autrichiens bombardent la ville. Lille refuse de se rendre ; un coiffeur continue de raser ses clients sous les obus. Un boulet est resté encastré dans une façade.",
 "Du 29 septembre au 8 octobre 1792, l'armée autrichienne assiège Lille et tire plus de 30 000 projectiles sur la ville, sans obtenir sa reddition.",
 ["La ville, place forte de Vauban, est sommée de se rendre ; le conseil municipal refuse. Le bombardement détruit des centaines de maisons et déclenche des incendies. La légende raconte qu'un perruquier de la rue Esquermoise continua d'exercer en poudrant ses clients avec les gravats, et qu'un boulet logé dans sa façade fut conservé comme trophée ; une boule dorée marque encore l'endroit, rue Esquermoise.",
  "Les Autrichiens lèvent le siège après la victoire française de Valmy et la contre-offensive. La Convention décrète que Lille « a bien mérité de la patrie ».",
  "La colonne de la Déesse, au centre de la Grand-Place, érigée en 1845, commémore cette résistance ; la figure féminine tient le boutefeu avec lequel le maire aurait refusé d'allumer le signal de reddition."],
 "Si%C3%A8ge_de_Lille_(1792)",lat=50.6371,lon=3.0634),
]

strasbourg=[
A("politique","Trautmann, maire en 1989, de retour en 2026","Depuis 2026 · Hôtel de ville",
 "Première femme maire d'une grande ville française en 1989, ministre de la Culture, battue en 2001, elle reprend Strasbourg à 75 ans en devançant l'écologiste sortante et la droite dans une triangulaire très serrée.",
 "Catherine Trautmann, maire de Strasbourg de 1989 à 1997 puis de 2000 à 2001, a retrouvé la mairie le 22 mars 2026 avec 37 % des voix.",
 ["Pasteure de formation, théologienne, elle devient en 1989 la première femme à diriger une grande ville française. Elle lance le tramway, ouvert en 1994, qui transforme le centre et fait école en Europe. Ministre de la Culture et de la Communication de 1997 à 2000 dans le gouvernement Jospin, elle revient à la mairie avant d'être battue en 2001 par Fabienne Keller.",
  "Députée européenne pendant une décennie, elle se retire de la vie politique nationale avant de revenir en 2026. Le second tour est une triangulaire : elle l'emporte avec 37 % contre 31,7 % à la sortante écologiste Jeanne Barseghian, alliée à La France insoumise, et 31,3 % au candidat Les Républicains Jean-Philippe Vetter.",
  "Strasbourg fait partie des six villes perdues par les écologistes en 2026, avec Bordeaux, Besançon, Poitiers, Annecy et Colombes."],
 "Catherine_Trautmann",lat=48.5817,lon=7.7458),
A("patrimoine","La cathédrale, plus haut édifice du monde pendant 227 ans","1647-1874 · Place de la Cathédrale",
 "Avec 142 mètres, la flèche de Strasbourg a dominé le monde de 1647 à 1874, jusqu'à l'église Saint-Nicolas de Hambourg. Une seule tour a été construite : la seconde n'a jamais vu le jour.",
 "La cathédrale Notre-Dame de Strasbourg, achevée en 1439, a été l'édifice le plus haut du monde de 1647 à 1874, avec sa flèche de 142 mètres.",
 ["Le grès rose des Vosges lui donne sa couleur. Le projet prévoyait deux tours symétriques ; seule celle du nord a été élevée, surmontée de sa flèche en dentelle de pierre par Jean Hültz. L'asymétrie, accidentelle, est devenue sa signature.",
  "L'horloge astronomique, dont le mécanisme actuel date de 1842, déclenche chaque jour à 12 h 30 le défilé des apôtres devant le Christ, pendant que le coq chante trois fois. Elle calcule les fêtes mobiles et la position des planètes.",
  "Victor Hugo l'appelait un « prodige du gigantesque et du délicat ». Elle a été bombardée en 1870 et touchée en 1944, et sa restauration est permanente : un atelier de tailleurs de pierre, l'Œuvre Notre-Dame, y travaille sans interruption depuis le XIIIe siècle."],
 "Cath%C3%A9drale_Notre-Dame_de_Strasbourg",lat=48.5819,lon=7.7509,access="Libre ; plateforme payante",protection="Monument historique, 1862 ; UNESCO, 1988"),
A("histoire","La Marseillaise écrite ici en une nuit","25-26 avril 1792 · Place Broglie",
 "Le maire demande à un officier du génie un chant de guerre pour l'armée du Rhin. Rouget de Lisle le compose dans la nuit. Il s'appellera plus tard la Marseillaise.",
 "Le « Chant de guerre pour l'armée du Rhin », futur hymne national, a été composé à Strasbourg dans la nuit du 25 au 26 avril 1792 par Claude Joseph Rouget de Lisle.",
 ["La France vient de déclarer la guerre à l'Autriche. Le maire de Strasbourg, Philippe Frédéric de Dietrich, reçoit chez lui des officiers et déplore l'absence d'un chant digne des troupes. Rouget de Lisle, capitaine du génie et musicien amateur, revient le lendemain avec paroles et musique, chantées pour la première fois dans le salon du maire, place Broglie.",
  "Le chant gagne Montpellier puis Marseille, où il est imprimé et distribué aux volontaires qui montent sur Paris en juillet : les Parisiens le baptisent « hymne des Marseillais ». Il devient chant national le 14 juillet 1795.",
  "Rouget de Lisle, royaliste modéré, sera emprisonné sous la Terreur et mourra pauvre en 1836. Dietrich, lui, a été guillotiné en 1793. Une plaque marque la maison du 4 place Broglie."],
 "La_Marseillaise",lat=48.5840,lon=7.7510),
A("insolite","Le marché de Noël le plus ancien de France","Depuis 1570 · Place Broglie et centre",
 "Le Christkindelsmärik est né en 1570 d'une décision protestante : remplacer la foire de la Saint-Nicolas par un marché de l'Enfant-Christ. Il attire aujourd'hui deux millions de visiteurs.",
 "Le marché de Noël de Strasbourg, créé en 1570, est le plus ancien de France et l'un des plus anciens d'Europe.",
 ["La Réforme ayant écarté le culte des saints, la ville protestante supprime la foire de la Saint-Nicolas et instaure le « marché de l'Enfant-Christ », le Christkindelsmärik, qui se tient d'abord trois jours autour du 24 décembre. Il s'étend ensuite sur tout l'Avent et sur plusieurs places du centre.",
  "Le grand sapin de la place Kléber, haut d'une trentaine de mètres, est une tradition documentée à Strasbourg dès 1605, ce qui en fait l'une des premières mentions d'arbre de Noël décoré en Europe.",
  "Un attentat au camion-bélier et à l'arme à feu a frappé le marché le 11 décembre 2018, faisant cinq morts ; le dispositif de sécurité a été renforcé depuis."],
 "March%C3%A9_de_No%C3%ABl_de_Strasbourg",lat=48.5840,lon=7.7480),
]

nice=[
A("politique","Ciotti prend Nice, Estrosi se retire","Mars 2026 · Place Pierre-Gautier",
 "L'ancien président des Républicains, passé à l'alliance avec le Rassemblement national en 2024, l'emporte avec 48,5 % face au maire sortant. Estrosi, battu, annonce la fin de sa vie politique.",
 "Éric Ciotti a été élu maire de Nice le 22 mars 2026 avec 48,54 % des voix, devant Christian Estrosi (37,20 %) et la liste de gauche de Juliette Chesnel-Le Roux (14,26 %).",
 ["Président des Républicains depuis 2022, Ciotti annonce en juin 2024, après la dissolution de l'Assemblée, une alliance avec le Rassemblement national ; son parti tente de l'exclure, il conteste en justice et fonde l'UDR. La bascule d'une grande ville de la Côte d'Azur à une liste alliée au RN est le fait marquant du scrutin de 2026.",
  "Christian Estrosi dirigeait Nice depuis 2008, avec une interruption, après avoir été ministre de l'Industrie et président de la région. Battu, il annonce son retrait de la vie politique niçoise et abandonne ses mandats locaux.",
  "Nice est, avec Toulouse et Besançon, l'un des symboles du recul de la gauche et des écologistes lors de ce scrutin."],
 "%C3%89ric_Ciotti",lat=43.7010,lon=7.2760),
A("faits_divers","14 juillet 2016 : le camion sur la promenade des Anglais","14 juillet 2016 · Promenade des Anglais",
 "À 22 h 32, un camion de 19 tonnes fonce sur la foule rassemblée pour le feu d'artifice, sur près de deux kilomètres. 86 morts, dont quinze enfants, et 450 blessés.",
 "Le 14 juillet 2016, un attentat au camion-bélier sur la promenade des Anglais fait 86 morts et plus de 450 blessés.",
 ["La promenade est fermée à la circulation pour le feu d'artifice ; des dizaines de milliers de personnes s'y trouvent. Le conducteur, un Tunisien de 31 ans résidant à Nice, force un barrage et roule pendant 1,7 kilomètre en zigzaguant pour viser les groupes, avant d'être abattu par la police. Les victimes viennent de dix-neuf pays ; un tiers sont de confession musulmane.",
  "L'État islamique revendique l'attaque. L'enquête ne retrouve pas de lien opérationnel direct mais établit la préparation et l'aide de plusieurs proches. Le procès de huit accusés se tient à Paris de septembre à décembre 2022 ; trois sont condamnés pour association de malfaiteurs terroriste, les autres pour des infractions connexes.",
  "Un mémorial a été inauguré en 2021 dans le jardin d'Alsace-Lorraine, et le musée-mémorial du terrorisme national doit lui consacrer une place."],
 "Attentat_du_14_juillet_2016_%C3%A0_Nice",lat=43.6950,lon=7.2600),
A("histoire","Nice française depuis 1860 seulement","1860 · Toute la ville",
 "Le comté de Nice appartenait au royaume de Piémont-Sardaigne. Napoléon III l'obtient en échange de son soutien à l'unité italienne ; un plébiscite approuve le rattachement à 99 %, dans des conditions discutées.",
 "Nice est devenue française le 14 juin 1860, à la suite du traité de Turin signé entre Napoléon III et le royaume de Piémont-Sardaigne.",
 ["La France s'était engagée à soutenir militairement le Piémont contre l'Autriche en échange de la Savoie et du comté de Nice. Le traité prévoit une consultation des populations : le plébiscite des 15 et 16 avril 1860 donne 99,2 % de oui, avec un vote public, sans isoloir, et une campagne officielle à sens unique ; les historiens considèrent le résultat largement orienté, même si une majorité réelle était favorable.",
  "Garibaldi, né à Nice en 1807 et député au parlement de Turin, s'y oppose violemment et tente d'organiser un recours. Une partie de la population italophone émigre vers l'Italie, c'est la « nissarde ».",
  "Nice a conservé sa langue, le nissart, son carnaval et sa cuisine liées au monde ligure ; le Vieux-Nice ressemble plus à Gênes qu'à Aix."],
 "Annexion_du_comt%C3%A9_de_Nice_%C3%A0_la_France"),
A("gastronomie","La socca, le pois chiche de la rue Pairolière","Depuis le XIXe siècle · Vieux-Nice",
 "Une galette de farine de pois chiche cuite au four à bois dans un plat de cuivre, servie brûlante, poivrée, à manger debout avec les doigts. On ne la réchauffe pas.",
 "La socca, galette de farine de pois chiche, d'eau et d'huile d'olive, est le plat de rue emblématique de Nice.",
 ["La pâte, très liquide, est versée sur un large plat de cuivre et enfournée à plus de 400 degrés quelques minutes : elle doit être moelleuse au centre et brûlée par endroits. On la découpe à la spatule, on la poivre, on la mange debout. Les marchands ambulants la criaient autrefois dans les rues du Vieux-Nice au petit matin.",
  "Son origine est ligure : la farinata de Gênes est identique, souvenir des siècles où Nice appartenait au monde italien.",
  "La cuisine nissarde comprend aussi la pissaladière, la ratatouille, le pan bagnat et la véritable salade niçoise, dont un comité local rappelle régulièrement qu'elle ne contient ni haricots verts ni pommes de terre."],
 "Socca",lat=43.6975,lon=7.2770),
]

montpellier=[
A("politique","Delafosse réélu, Altrad battu","Mars 2026 · Hôtel de ville",
 "Le maire socialiste l'emporte dès la logique du second tour avec 50,1 % face à La France insoumise et au milliardaire Mohed Altrad, propriétaire du club de rugby, qui se présentait pour la seconde fois.",
 "Michaël Delafosse, maire de Montpellier depuis 2020, a été réélu le 22 mars 2026 avec 50,1 % des voix.",
 ["Professeur d'histoire-géographie, il avait pris la ville en 2020 à Philippe Saurel, ancien socialiste élu sans étiquette. Son mandat est marqué par la gratuité des transports pour les habitants de la métropole, décidée en 2023, mesure la plus ambitieuse en France pour une ville de cette taille, et par la poursuite du tramway.",
  "Face à lui, Nathalie Oziol pour La France insoumise obtient 25,1 %, et Mohed Altrad, fondateur du groupe d'échafaudages qui porte son nom et président du Montpellier Hérault Rugby, 24,8 %.",
  "Montpellier reste à gauche, dans la continuité de Georges Frêche, maire de 1977 à 2004, qui a façonné la ville moderne et fut connu pour ses provocations verbales et son exclusion du Parti socialiste."],
 "Micha%C3%ABl_Delafosse",lat=43.6110,lon=3.8767),
A("histoire","La plus vieille faculté de médecine encore en activité","1220 · Rue de l'École-de-Médecine",
 "Les statuts datent de 1220, l'enseignement est plus ancien encore. Rabelais y a étudié, Nostradamus y a été inscrit, et la dissection y était pratiquée bien avant ailleurs.",
 "La faculté de médecine de Montpellier, dont les statuts remontent à 1220, est la plus ancienne école de médecine du monde occidental encore en activité.",
 ["La ville, carrefour entre les mondes chrétien, juif et arabe, accueille dès le XIIe siècle des maîtres venus de Salerne, d'Espagne et d'Orient. Les statuts de 1220, donnés par le légat du pape, organisent l'enseignement. Montpellier obtient très tôt l'autorisation de pratiquer des dissections, d'abord sur les corps des suppliciés.",
  "François Rabelais s'y inscrit en 1530 et y donne des leçons sur Hippocrate ; sa robe, dite robe de Rabelais, sert encore aux soutenances de thèse. Nostradamus y est inscrit en 1529, mais son parcours y a été contesté par la faculté elle-même.",
  "Le jardin des plantes attenant, créé en 1593 par Henri IV, est le plus ancien de France. Le conservatoire d'anatomie conserve des collections du XVIIIe siècle."],
 "Facult%C3%A9_de_m%C3%A9decine_de_Montpellier",lat=43.6140,lon=3.8718),
A("insolite","Une ville sans monument antique dans un pays romain","Depuis 985 · Toute la ville",
 "Montpellier n'a ni arènes ni théâtre romain, contrairement à Nîmes ou Arles : elle n'existait pas à l'époque. Née au Xe siècle d'un acte de donation, c'est une des rares grandes villes françaises sans passé antique.",
 "Montpellier apparaît pour la première fois dans un acte de 985 ; elle n'a aucune origine romaine, à la différence de la plupart des villes du Midi.",
 ["Le comte de Melgueil cède un domaine, « Monspestellarius », à un certain Guilhem. Ses descendants, les Guilhem, développent un bourg marchand qui profite du commerce des épices et des étoffes avec le Levant, et de la proximité des routes de pèlerinage. En deux siècles, la ville dépasse ses voisines antiques.",
  "L'absence de passé romain explique son plan médiéval irrégulier, l'Écusson, et l'absence de monument antique, compensée au XVIIe siècle par la promenade du Peyrou, l'arc de triomphe et l'aqueduc Saint-Clément, imité du pont du Gard.",
  "Montpellier a été, en proportion, l'une des villes dont la population a le plus augmenté en France depuis 1960, passant d'environ 100 000 à plus de 300 000 habitants."],
 "Montpellier",lat=43.6110,lon=3.8767),
]

cities=[("69123","Lyon","Rhône",45.7640,4.8357,lyon),
        ("31555","Toulouse","Haute-Garonne",43.6047,1.4442,toulouse),
        ("59350","Lille","Nord",50.6292,3.0573,lille),
        ("67482","Strasbourg","Bas-Rhin",48.5734,7.7521,strasbourg),
        ("06088","Nice","Alpes-Maritimes",43.7102,7.2620,nice),
        ("34172","Montpellier","Hérault",43.6108,3.8767,montpellier)]
idx=json.load(open('index.json'))
for insee,name,dept,lat,lon,arts in cities:
    path=f"communes/{insee}.json"
    if os.path.exists(path):
        p=json.load(open(path)); have={a.get("wiki") for a in p["anecdotes"]}
        p["anecdotes"]+=[a for a in arts if a.get("wiki") not in have]
    else:
        p={"id":f"{name.lower()}-{insee}","insee":insee,"name":name,"dept":dept,"kind":"commune","lat":lat,"lon":lon,"anecdotes":arts}
    json.dump(p,open(path,'w'),ensure_ascii=False,indent=1)
    idx["communes"][insee]={"name":name,"count":len(p["anecdotes"]),"updated":"2026-10-07"}
    print(name,len(p["anecdotes"]))
json.dump(idx,open('index.json','w'),ensure_ascii=False,indent=1)
