import json, os
W="https://fr.wikipedia.org/wiki/"
def A(cat,title,label,teaser,lead,body,wiki,more=None,timeline=None,lat=None,lon=None,links=None,access=None,protection=None):
    return {"category":cat,"title":title,"label":label,"teaser":teaser,"lead":lead,"text":lead,"body":body,"more":more or [],"timeline":timeline,"links":links,"wiki":wiki,"source":W+wiki,"lat":lat,"lon":lon,"access":access,"protection":protection}
L=lambda kind,title,url,note=None:{"kind":kind,"title":title,"url":url,"note":note}

brest=[
A("politique","Brest bascule à droite après un demi-siècle","Mars 2026 · Hôtel de ville",
 "François Cuillandre, maire depuis 2001, est battu par Stéphane Roudaut avec 57,4 % contre 38,3 %. C'est la fin d'un quasi-demi-siècle de gauche sur la ville.",
 "Stéphane Roudaut est maire de Brest depuis mars 2026, après avoir largement battu le sortant socialiste François Cuillandre.",
 ["Cuillandre dirigeait Brest depuis 2001, après Pierre Maille ; la ville était à gauche sans interruption depuis les années 1970. Son dernier mandat a été critiqué sur la propreté, le commerce du centre et la gestion du projet de téléphérique urbain, le premier de France à franchir la Penfeld, ouvert en 2016.",
  "Au second tour, la liste de droite de Stéphane Roudaut, maire de Plougastel-Daoulas, obtient 57,4 % des suffrages contre 38,3 % à la gauche unie et 4,3 % au Rassemblement national. L'écart, près de vingt points, est l'un des plus nets de France parmi les grandes villes.",
  "Brest figure, avec Clermont-Ferrand, Pau, Avignon et Tulle, parmi les maires sortants battus en 2026, dans un scrutin marqué par un record d'abstention hors période sanitaire."],
 "Brest",lat=48.3904,lon=-4.4861),
A("histoire","Rasée à 90 %, reconstruite en béton","1944 · Tout le centre",
 "Quarante-cinq jours de siège, 165 bombardements, et une ville effacée. Le centre a été rebâti au cordeau par Jean-Baptiste Mathon, et les Brestois en débattent encore.",
 "Brest, base des sous-marins allemands, a été détruite à près de 90 % entre 1940 et 1944 ; le siège final, en août-septembre 1944, a duré quarante-trois jours.",
 ["La base sous-marine, construite par l'organisation Todt avec des toits de béton de plusieurs mètres, est indestructible ; les bombardements alliés visent le port et manquent largement leur cible, détruisant la ville autour. Lors du siège d'août 1944, les Américains du général Middleton affrontent la garnison du général Ramcke, qui capitule le 19 septembre : il ne reste presque rien debout.",
  "La reconstruction, confiée à Jean-Baptiste Mathon, suit un plan orthogonal avec des immeubles en béton de hauteur uniforme le long de la rue de Siam. Rapide et fonctionnelle, elle est longtemps jugée austère, avant d'être réévaluée comme un ensemble cohérent des années 1950 et partiellement labellisée patrimoine du XXe siècle.",
  "Il subsiste du Brest ancien le château, occupé par la Marine depuis dix-sept siècles, et la tour Tanguy, qui abrite un musée où des dioramas montrent la ville d'avant."],
 "Brest",lat=48.3830,lon=-4.4950),
A("insolite","Le plus vieux château encore en service d'Europe","IIIe siècle · Embouchure de la Penfeld",
 "Castellum romain devenu forteresse médiévale puis arsenal, le château de Brest est occupé sans interruption depuis dix-sept siècles. Il abrite aujourd'hui la préfecture maritime.",
 "Le château de Brest, dont les premières murailles datent du IIIe siècle, est le plus ancien château du monde encore utilisé pour sa fonction d'origine.",
 ["Les Romains y établissent un castellum pour surveiller la rade. Les comtes bretons, les Anglais pendant la guerre de Succession, puis les rois de France l'agrandissent ; Vauban le transforme au XVIIe siècle lorsque Colbert fait de Brest le grand arsenal de l'Atlantique.",
  "Il a résisté aux bombardements de 1944 qui ont rasé la ville autour. Il accueille aujourd'hui la préfecture maritime de l'Atlantique et le musée national de la Marine.",
  "La rade de Brest, vaste de 180 km², est l'une des plus grandes rades fermées du monde ; elle abrite la force océanique stratégique française à l'île Longue."],
 "Ch%C3%A2teau_de_Brest",lat=48.3800,lon=-4.4950,access="Musée national de la Marine ; horaires saisonniers",protection="Monument historique, 1923"),
]

lehavre=[
A("politique","Édouard Philippe, maire et candidat déclaré à l'Élysée","Depuis 2020 · Hôtel de ville",
 "Premier ministre de 2017 à 2020, il est revenu au Havre le lendemain de son départ de Matignon, a été réélu en 2026, et prépare ouvertement la présidentielle de 2027.",
 "Édouard Philippe est maire du Havre depuis 2020, après un premier mandat de 2010 à 2017, et a été réélu en mars 2026.",
 ["Élu une première fois en 2010 à la suite d'Antoine Rufenacht, il quitte la mairie en 2017 pour Matignon. Nommé par Emmanuel Macron, il dirige le gouvernement pendant trois ans et deux mois, traversant les gilets jaunes, la réforme des retraites et le premier confinement, avant de démissionner en juillet 2020 et de se représenter aussitôt au Havre, où il l'emporte.",
  "Il fonde en 2021 son propre parti, Horizons, et annonce en septembre 2023 sa candidature à l'élection présidentielle de 2027. Sa réélection en 2026 est présentée comme une étape de cette stratégie.",
  "Le Havre est l'une des villes conservées par le camp présidentiel en 2026, avec Reims et Angers."],
 "%C3%89douard_Philippe",lat=49.4944,lon=0.1079),
A("patrimoine","Le centre d'Auguste Perret classé par l'UNESCO","1945-1964 · Tout le centre",
 "Détruite à 80 %, la ville a été reconstruite en béton armé selon un plan unique, autour d'une trame de 6,24 mètres. C'est le seul centre-ville du XXe siècle inscrit au patrimoine mondial en Europe.",
 "Le centre reconstruit du Havre, œuvre d'Auguste Perret et de son atelier entre 1945 et 1964, est inscrit au patrimoine mondial de l'UNESCO depuis 2005.",
 ["Les bombardements de septembre 1944, parmi les plus meurtriers de France avec environ 5 000 morts, rasent 150 hectares. Perret, théoricien du béton armé, obtient de reconstruire sur une dalle, avec une trame modulaire de 6,24 mètres qui régit tous les immeubles, et un béton laissé apparent, bouchardé pour révéler les agrégats.",
  "Les Havrais ont longtemps détesté cette ville grise ; l'appartement témoin, meublé des années 1950, montre pourtant des logements lumineux, traversants et très en avance par leur confort. L'église Saint-Joseph et sa tour-lanterne de 107 mètres, achevée après la mort de Perret, sert de repère aux marins.",
  "Le classement UNESCO en 2005 a renversé le regard ; la ville a ajouté des couleurs sur le port, dont l'œuvre « Catène de containers » de Vincent Ganivet, installée pour les 500 ans de la ville en 2017."],
 "Centre-ville_reconstruit_du_Havre",lat=49.4938,lon=0.1077,protection="UNESCO, 2005"),
A("faits_divers","Septembre 1944 : la ville rasée par ses alliés","5-11 septembre 1944 · Centre-ville",
 "Les Allemands refusent d'évacuer les civils ; la Royal Air Force bombarde quand même pendant six jours. Environ 5 000 morts, 80 000 sinistrés, et une polémique jamais éteinte.",
 "Du 5 au 11 septembre 1944, les bombardements alliés sur Le Havre font environ 5 000 morts civils et détruisent le centre de la ville.",
 ["La garnison allemande, retranchée, refuse les offres de reddition et interdit l'évacuation de la population. Le commandement britannique décide néanmoins l'opération Astonia : plus de 10 000 tonnes de bombes en six jours sur une ville où se trouvent des dizaines de milliers de civils. Le centre est anéanti ; la garnison, abritée dans ses bunkers, capitule le 12 septembre avec peu de pertes.",
  "C'est l'un des bilans civils les plus lourds d'un bombardement allié en France. Le débat sur la proportionnalité de l'opération est resté vif, en France comme au Royaume-Uni, et des historiens britanniques l'ont qualifiée d'erreur militaire.",
  "Un mémorial et des cérémonies annuelles rappellent les victimes. La reconstruction par Perret a commencé l'année suivante."],
 "Bombardements_du_Havre"),
]

rouen=[
A("faits_divers","Lubrizol : un incendie, un nuage noir sur la Normandie","26 septembre 2019 · Usine Lubrizol",
 "Un panache de fumée de vingt kilomètres, 9 500 tonnes de produits chimiques brûlés, des récoltes détruites, et des habitants qui attendent encore de savoir ce qu'ils ont respiré.",
 "Le 26 septembre 2019 à 2 h 40, un incendie se déclare dans l'usine chimique Lubrizol, classée Seveso seuil haut, à Rouen. Il faut douze heures pour le maîtriser.",
 ["Près de 9 500 tonnes de produits, surtout des additifs pour lubrifiants, brûlent ; le panache de fumée noire s'étend sur plus de vingt kilomètres et retombe en suies sur des dizaines de communes. Les écoles ferment, les récoltes et le lait sont consignés sur 112 communes, et la préfecture est critiquée pour la lenteur et le flou de sa communication.",
  "Aucun décès immédiat n'est à déplorer, mais les riverains signalent des nausées, des maux de tête et de l'angoisse ; une commission d'enquête parlementaire pointe en 2020 des lacunes dans la prévention et l'information. Le suivi sanitaire de long terme a été mis en place par Santé publique France.",
  "L'enquête judiciaire, toujours en cours des années après, porte sur l'origine du feu, apparue du côté d'un entrepôt voisin, Normandie Logistique. Lubrizol a été autorisé à redémarrer en décembre 2019."],
 "Incendie_de_l%27usine_Lubrizol_de_Rouen",lat=49.4300,lon=1.0600),
A("histoire","Jeanne d'Arc brûlée place du Vieux-Marché","30 mai 1431 · Place du Vieux-Marché",
 "À dix-neuf ans, condamnée par un tribunal d'Église présidé par Pierre Cauchon, elle est brûlée vive sur la place du marché. Ses cendres sont jetées dans la Seine pour éviter les reliques.",
 "Jeanne d'Arc a été brûlée vive à Rouen le 30 mai 1431, après un procès en hérésie mené par l'évêque de Beauvais Pierre Cauchon au service des Anglais.",
 ["Capturée à Compiègne en 1430 et vendue aux Anglais, elle est détenue au château de Rouen. Le procès, de janvier à mai 1431, porte sur ses voix, son habit d'homme et sa soumission à l'Église. Elle abjure brièvement, puis reprend l'habit masculin : relapse, elle est livrée au bras séculier.",
  "L'exécution a lieu sur le bûcher dressé place du Vieux-Marché, devant une foule nombreuse. Ses cendres sont jetées en Seine. Un procès en nullité, ouvert à la demande de sa mère, la réhabilite en 1456 ; elle est canonisée en 1920.",
  "L'église Sainte-Jeanne-d'Arc, construite en 1979 sur la place, a la forme d'une coque de bateau renversée et abrite des vitraux Renaissance sauvés d'une église détruite en 1944. Une croix marque l'emplacement du bûcher."],
 "Proc%C3%A8s_de_Jeanne_d%27Arc",lat=49.4432,lon=1.0881),
A("patrimoine","Le Gros-Horloge et la cathédrale peinte trente fois","XIVe-XVIe siècle · Rue du Gros-Horloge",
 "Une horloge sans aiguille des heures sous une arche Renaissance, et une cathédrale que Monet a peinte trente fois pour montrer la lumière plutôt que la pierre.",
 "Rouen conserve deux monuments emblématiques : le Gros-Horloge, mécanisme de 1389, et la cathédrale Notre-Dame, dont la façade a inspiré à Claude Monet une série de trente toiles.",
 ["Le Gros-Horloge, l'un des plus anciens mécanismes d'Europe, n'a qu'une aiguille, celle des heures ; la phase lunaire et le jour de la semaine s'affichent séparément. Il a été déplacé en 1529 sur l'arche Renaissance qui enjambe la rue, pour être mieux visible des habitants.",
  "La cathédrale, dont la flèche de fonte culmine à 151 mètres, fut le plus haut édifice du monde de 1876 à 1880. Monet loue en 1892 et 1893 une chambre face à la façade et peint la même vue à différentes heures : la série, exposée en 1895, est un sommet de l'impressionnisme.",
  "Le centre a brûlé en 1944 ; la cathédrale a été touchée par sept bombes et restaurée pendant des décennies."],
 "Cath%C3%A9drale_Notre-Dame_de_Rouen",lat=49.4404,lon=1.0950),
]

reims=[
A("histoire","Trente-trois rois sacrés dans la même cathédrale","496-1825 · Cathédrale Notre-Dame",
 "Depuis le baptême de Clovis, les rois de France viennent se faire sacrer à Reims. Charles VII y est conduit par Jeanne d'Arc en 1429 ; Charles X y clôt la série en 1825.",
 "La cathédrale de Reims a accueilli le sacre de trente-trois rois de France, de Louis le Pieux en 816 à Charles X en 1825.",
 ["La tradition remonte au baptême de Clovis par saint Remi, vers 496, et à la légende de la Sainte Ampoule apportée par une colombe, dont l'huile servit à oindre tous les rois. La cathédrale gothique actuelle, commencée en 1211, est conçue comme un décor de sacre : nef immense pour la procession, galerie des rois en façade, 2 300 statues.",
  "Le 17 juillet 1429, Charles VII y est sacré en présence de Jeanne d'Arc, qui en avait fait l'objectif de sa campagne : le sacre légitime le roi face aux Anglais. La Sainte Ampoule est brisée publiquement en 1793 ; un fragment conservé servira pour Charles X.",
  "Bombardée dès septembre 1914 et incendiée, la cathédrale devient le symbole du « vandalisme allemand » dans la propagande de guerre. Sa restauration, financée en partie par John D. Rockefeller, s'achève en 1938."],
 "Cath%C3%A9drale_Notre-Dame_de_Reims",lat=49.2537,lon=4.0340,protection="UNESCO, 1991"),
A("histoire","La capitulation allemande signée dans une école","7 mai 1945 · Collège moderne et technique",
 "Eisenhower avait installé son quartier général dans un lycée de Reims. C'est là, à 2 h 41 du matin, que l'Allemagne a signé sa reddition sans condition.",
 "L'acte de capitulation sans condition de l'Allemagne a été signé à Reims le 7 mai 1945 à 2 h 41, dans la salle des cartes du quartier général allié installé dans un collège technique.",
 ["Eisenhower, commandant suprême des forces alliées, avait établi son état-major à Reims en février 1945. Le général Jodl signe pour l'Allemagne, Bedell Smith pour les Alliés, Sousloparov pour l'URSS et François Sevez pour la France. Les combats doivent cesser le 8 mai à 23 h 01.",
  "Staline juge la cérémonie insuffisante et exige une seconde signature à Berlin-Karlshorst, le 8 mai, en présence de Joukov : c'est pourquoi la Russie célèbre la victoire le 9 mai.",
  "La salle a été conservée en l'état avec ses cartes murales et constitue le Musée de la Reddition, ouvert au public."],
 "Capitulation_allemande_du_7_mai_1945",lat=49.2590,lon=4.0250,access="Musée de la Reddition, fermé le mardi"),
A("gastronomie","Le champagne et ses caves creusées par les Romains","Depuis le XVIIe siècle · Crayères de la Butte Saint-Nicaise",
 "Les grandes maisons stockent leurs bouteilles dans des puits de craie creusés par les Gallo-Romains, à vingt mètres sous terre, à une température constante de dix degrés.",
 "Les caves de Reims, dites crayères, s'étendent sur des dizaines de kilomètres sous la ville et abritent des millions de bouteilles de champagne.",
 ["Les Gallo-Romains ont extrait la craie en creusant des puits pyramidaux de vingt à trente mètres, larges à la base. Abandonnées, ces cavités sont redécouvertes par les maisons de champagne au XIXe siècle : température stable de 10 à 12 degrés, hygrométrie idéale, et place pour le vieillissement sur lattes.",
  "Pendant la Première Guerre mondiale, alors que la ville est détruite à plus de 80 % par les bombardements, les Rémois vivent dans ces caves : écoles, hôpitaux, ateliers et messes y sont installés pendant plus de trois ans.",
  "Les coteaux, maisons et caves de Champagne sont inscrits au patrimoine mondial depuis 2015 ; plusieurs maisons rémoises se visitent."],
 "Crayère",lat=49.2400,lon=4.0400,protection="UNESCO, 2015"),
]

dijon=[
A("politique","Koenders succède à Rebsamen et conserve Dijon","Depuis 2023 · Hôtel de ville",
 "François Rebsamen, maire pendant vingt-trois ans et ministre du Travail, a laissé la place à sa première adjointe en 2023. Elle a été confirmée dans les urnes en mars 2026.",
 "Nathalie Koenders est maire de Dijon depuis 2023 et a été réélue en mars 2026.",
 ["François Rebsamen avait pris la ville en 2001 au gaulliste Robert Poujade, maire pendant trente ans et premier ministre de l'Environnement de l'histoire française, en 1971. Rebsamen, ministre du Travail de 2014 à 2015, a mené la rénovation du centre, le tramway ouvert en 2012 et le classement UNESCO des climats de Bourgogne.",
  "Il démissionne en 2023 et transmet le mandat à Nathalie Koenders, sa première adjointe, qui remporte ensuite le scrutin municipal de 2026. Dijon reste à gauche.",
  "La ville a obtenu en 2022 l'ouverture de la Cité internationale de la gastronomie et du vin, sur le site de l'ancien hôpital général."],
 "Nathalie_Koenders",lat=47.3220,lon=5.0415),
A("patrimoine","Les tuiles vernissées et le palais des ducs","XIVe-XVIIIe siècle · Place de la Libération",
 "Les toits de tuiles polychromes en losanges sont la signature de la Bourgogne. Le palais des ducs, siège d'un État qui rivalisait avec le royaume de France, abrite aujourd'hui la mairie et le musée des Beaux-Arts.",
 "Le palais des ducs et des États de Bourgogne, au cœur de Dijon, rappelle l'époque où les ducs Valois dominaient un territoire allant de la Bourgogne aux Flandres.",
 ["Philippe le Hardi, Jean sans Peur, Philippe le Bon et Charles le Téméraire ont régné de 1363 à 1477 sur un ensemble plus riche que le royaume de France, nourri par les draps flamands. La tour Philippe le Bon, haute de 46 mètres, se gravit par 316 marches. Les tombeaux des ducs, chefs-d'œuvre de Claus Sluter, sont au musée des Beaux-Arts, l'un des plus anciens de France.",
  "La place, dessinée par Jules Hardouin-Mansart pour une statue équestre de Louis XIV, a été rendue aux piétons en 2006.",
  "Les toits de tuiles vernissées, en jaune, vert, rouge et noir, apparaissent au XIVe siècle sous influence d'Europe centrale ; l'hôtel-Dieu de Beaune en est l'exemple le plus connu."],
 "Palais_des_ducs_et_des_%C3%89tats_de_Bourgogne",lat=47.3220,lon=5.0415,protection="Monument historique ; UNESCO, 2015"),
A("gastronomie","La moutarde de Dijon ne vient plus de Dijon","Depuis le XIIIe siècle · Toute la ville",
 "« Moutarde de Dijon » désigne une recette, pas une origine. Les graines viennent du Canada depuis des décennies, et une filière locale tente de renaître.",
 "La moutarde de Dijon est une appellation de recette, non protégée géographiquement : elle peut être fabriquée n'importe où, à partir de graines venues d'ailleurs.",
 ["La fabrication remonte au Moyen Âge ; un édit de 1634 accorde aux vinaigriers-moutardiers de Dijon le monopole de la production. Le procédé dijonnais consiste à broyer les graines de moutarde brune avec du verjus, remplacé plus tard par du vin blanc, ce qui donne sa force caractéristique.",
  "Le nom n'ayant jamais été protégé, la culture des graines a quitté la Bourgogne au XXe siècle : plus de 80 % proviennent du Canada, de l'Alberta et du Saskatchewan. La sécheresse canadienne de 2021 a provoqué une pénurie spectaculaire dans les rayons français en 2022.",
  "Une filière bourguignonne a été relancée depuis les années 2000 et une IGP « moutarde de Bourgogne », qui impose graines et vin locaux, existe depuis 2009 ; elle ne concerne qu'une petite partie de la production."],
 "Moutarde_de_Dijon"),
]

grenoble=[
A("politique","Piolle s'en va, la gauche garde Grenoble","Mars 2026 · Hôtel de ville",
 "Premier écologiste élu dans une grande ville en 2014, Éric Piolle ne se représentait pas. Laurence Ruffin, candidate de la gauche, lui succède.",
 "Laurence Ruffin est maire de Grenoble depuis mars 2026, succédant à l'écologiste Éric Piolle, maire de 2014 à 2026.",
 ["Piolle avait été le premier écologiste à conquérir une ville de plus de 150 000 habitants, en 2014, avec une alliance incluant le Parti de gauche. Ses mandats ont été marqués par la piétonnisation, la gratuité partielle, la suppression des panneaux publicitaires remplacés par des arbres, et des conflits avec l'État sur la laïcité et sur le budget.",
  "Il ne se représente pas en 2026. Laurence Ruffin, dirigeante d'une coopérative industrielle, l'emporte avec le soutien d'une large coalition de gauche. Grenoble est l'une des villes conservées par ce camp, avec Lyon et Tours.",
  "La ville a été dirigée de 1965 à 1983 par Hubert Dubedout, pionnier de la démocratie locale et de l'urbanisme participatif, dont le mandat a laissé la Villeneuve, quartier expérimental devenu emblématique des difficultés des grands ensembles."],
 "Grenoble",lat=45.1885,lon=5.7245),
A("insolite","Les Bulles, le premier téléphérique urbain de France","1934 · Vers la Bastille",
 "Des cabines sphériques transparentes montent à 263 mètres au-dessus de l'Isère depuis 1934. C'est le plus ancien téléphérique urbain du monde encore en service.",
 "Le téléphérique de Grenoble-Bastille, mis en service le 29 septembre 1934, relie le centre-ville au fort de la Bastille en cinq minutes.",
 ["Il est le premier téléphérique urbain du monde ; les cabines d'origine, en bois, ont été remplacées en 1976 par des sphères transparentes de quatre places, les « bulles », devenues le symbole de la ville. La dénivellation est de 263 mètres.",
  "Le fort, construit au XIXe siècle par le général Haxo sur des fortifications plus anciennes, offre une vue sur les trois massifs qui encadrent la ville : Vercors, Chartreuse, Belledonne. Stendhal, né à Grenoble, écrivait qu'« au bout de chaque rue, une montagne ».",
  "Grenoble a accueilli les Jeux olympiques d'hiver de 1968, qui ont transformé la ville : autoroute, aéroport, maison de la culture, et la première mascotte olympique de l'histoire, Schuss."],
 "T%C3%A9l%C3%A9ph%C3%A9rique_de_Grenoble-Bastille",lat=45.1950,lon=5.7250),
A("histoire","La journée des Tuiles, avant-première de la Révolution","7 juin 1788 · Rue Jean-Jacques-Rousseau",
 "Un an avant la Bastille, les Grenoblois montent sur les toits et bombardent les troupes du roi avec leurs tuiles pour empêcher l'exil des parlementaires. Des historiens y voient la première journée révolutionnaire.",
 "Le 7 juin 1788, la population de Grenoble se soulève contre l'exil des magistrats du Parlement du Dauphiné, décidé par Louis XVI.",
 ["Le roi veut briser l'opposition des parlements à ses réformes fiscales. À Grenoble, les troupes doivent escorter les magistrats hors de la ville. La foule bloque les rues ; des habitants montent sur les toits et lancent des tuiles sur les soldats. Le gouverneur recule et les parlementaires restent.",
  "Dans la foulée, l'assemblée de Vizille, le 21 juillet 1788, réunit les trois ordres du Dauphiné et réclame la convocation des États généraux avec doublement du tiers état : c'est l'une des origines directes de 1789.",
  "Le château de Vizille abrite aujourd'hui le musée de la Révolution française, le seul consacré à cette période."],
 "Journ%C3%A9e_des_Tuiles",lat=45.1940,lon=5.7290),
]

clermont=[
A("politique","Clermont-Ferrand bascule à droite après trente ans","Mars 2026 · Hôtel de ville",
 "Olivier Bianchi, maire socialiste depuis 2014, est battu par Julien Bony. La ville, à gauche depuis 1944 à de rares exceptions près, change de camp.",
 "Julien Bony, candidat Les Républicains, est maire de Clermont-Ferrand depuis mars 2026, après la défaite du sortant socialiste Olivier Bianchi.",
 ["Clermont-Ferrand était l'un des bastions historiques de la gauche, liée au monde ouvrier de Michelin, dirigée par Roger Quilliot puis Serge Godard et Olivier Bianchi. Ce dernier avait obtenu la candidature de la ville au titre de capitale européenne de la culture 2028, finalement attribuée à Bourges.",
  "Sa défaite fait partie des revers subis par des maires sortants en 2026, avec Brest, Pau, Avignon et Tulle, dans un scrutin marqué par une abstention record.",
  "La ville reste indissociable de Michelin, qui y emploie encore plusieurs milliers de personnes et dont le siège mondial est installé à Cataroux."],
 "Clermont-Ferrand",lat=45.7772,lon=3.0870),
A("histoire","L'appel à la première croisade lancé ici","27 novembre 1095 · Place Delille",
 "Devant une foule réunie en plein air, le pape Urbain II appelle les chevaliers d'Occident à délivrer Jérusalem. La foule répond « Dieu le veut ». La première croisade part l'année suivante.",
 "Le concile de Clermont, convoqué par le pape Urbain II en novembre 1095, s'achève par l'appel à la première croisade.",
 ["Urbain II, pape français, réunit évêques et seigneurs à Clermont. Le 27 novembre, le discours est prononcé hors de la cathédrale, devant une assistance trop nombreuse pour y entrer, à l'emplacement approximatif de l'actuelle place Delille. Les chroniqueurs rapportent, en des versions divergentes, la promesse d'indulgence et le cri « Deus lo vult », Dieu le veut.",
  "La croisade populaire part dès 1096, suivie de l'expédition des barons qui prend Jérusalem en 1099. Les conséquences, en Orient comme pour les communautés juives d'Europe massacrées sur le passage des troupes, sont considérables.",
  "Une statue d'Urbain II, érigée en 1900, se dresse place de la Victoire, près de la cathédrale de lave de Volvic, noire, achevée par Viollet-le-Duc."],
 "Concile_de_Clermont",lat=45.7790,lon=3.0870),
A("insolite","Michelin, le Bibendum et le guide rouge","Depuis 1889 · Cataroux",
 "Deux frères qui fabriquent des machines agricoles inventent le pneu démontable, un bonhomme fait de pneus, et un guide gratuit pour donner envie de rouler. Le guide est devenu l'arbitre mondial de la gastronomie.",
 "Michelin, fondé à Clermont-Ferrand en 1889 par André et Édouard Michelin, a inventé le pneumatique démontable, le Bibendum et le guide rouge.",
 ["Les frères reprennent l'entreprise familiale de caoutchouc et déposent en 1891 le brevet du pneu démontable pour bicyclette, qui permet de réparer une crevaison en quinze minutes au lieu de plusieurs heures. Suivent le pneu auto, puis en 1946 le pneu radial, qui révolutionne l'industrie.",
  "Le Bibendum naît en 1898 d'une pile de pneus aperçue par Édouard, et d'une formule latine, « nunc est bibendum », le pneu Michelin « boit l'obstacle ». Le guide rouge, lancé en 1900 et distribué gratuitement à 35 000 exemplaires, indiquait les garages, les médecins et les hôtels ; il devient payant en 1920, après qu'André eut vu un exemplaire servir à caler un établi.",
  "Les étoiles apparaissent en 1926, la hiérarchie à trois niveaux en 1931. Michelin a façonné Clermont-Ferrand, avec ses cités ouvrières, ses écoles et son stade, berceau de l'ASM rugby."],
 "Michelin",lat=45.7900,lon=3.1140),
]

angers=[
A("politique","Béchu, ministre et maire, conserve Angers","Depuis 2014 · Hôtel de ville",
 "Ministre de la Transition écologique de 2022 à 2024, il a dû quitter la mairie pendant ses fonctions avant de la retrouver, et a été réélu en 2026 pour le camp présidentiel.",
 "Christophe Béchu est maire d'Angers depuis 2014, avec une interruption durant ses fonctions ministérielles, et a été réélu en mars 2026.",
 ["Élu président du conseil général de Maine-et-Loire à 29 ans en 2004, il prend la mairie d'Angers en 2014 à la gauche de Frédéric Béatse. Ministre de la Transition écologique et de la Cohésion des territoires de juillet 2022 à septembre 2024, il laisse la mairie à Jean-Marc Verchère pendant cette période, conformément à la règle de non-cumul, puis la retrouve.",
  "Membre d'Horizons, le parti d'Édouard Philippe, il conserve la ville en 2026 ; Angers fait partie des villes gardées par le camp présidentiel, avec Le Havre et Reims.",
  "La ville figure régulièrement en tête des classements français sur la qualité de vie et les espaces verts."],
 "Christophe_B%C3%A9chu",lat=47.4712,lon=-0.5518),
A("patrimoine","Cent mètres d'Apocalypse tissés au XIVe siècle","1375-1382 · Château d'Angers",
 "La plus grande tenture médiévale conservée au monde a été utilisée comme bâche pour protéger des orangers et bouchon de mur d'écurie avant d'être sauvée au XIXe siècle.",
 "La tenture de l'Apocalypse, tissée entre 1375 et 1382 pour le duc Louis Ier d'Anjou, mesure encore 104 mètres sur 4,5 ; c'est le plus grand ensemble de tapisseries médiévales subsistant.",
 ["Elle illustre l'Apocalypse de saint Jean en soixante-dix scènes, d'après des manuscrits enluminés, et était déployée lors des grandes cérémonies. Offerte à la cathédrale en 1480, elle est jugée démodée après la Révolution, vendue aux enchères sans trouver preneur, puis découpée : des morceaux servent de tapis, de couverture pour des orangers, de bouche-trou dans une écurie.",
  "Un chanoine, Joseph Joubert, entreprend de racheter les fragments à partir de 1848. Environ deux tiers de l'œuvre originale ont été retrouvés et restaurés.",
  "Elle est présentée dans une galerie construite pour elle dans l'enceinte du château des ducs d'Anjou, forteresse aux dix-sept tours de schiste et de calcaire bâtie sous Saint Louis en moins de dix ans."],
 "Tenture_de_l%27Apocalypse",lat=47.4703,lon=-0.5600,access="Château d'Angers, ouvert toute l'année",protection="Monument historique"),
A("faits_divers","Le pont de la Basse-Chaîne s'effondre sous une troupe au pas","16 avril 1850 · Maine",
 "Un bataillon traverse le pont suspendu au pas cadencé sous l'orage. Les câbles cèdent, 226 soldats se noient. Depuis, les militaires rompent le pas sur les ponts.",
 "Le 16 avril 1850, l'effondrement du pont suspendu de la Basse-Chaîne, à Angers, provoque la mort de 226 soldats du 11e léger.",
 ["Le bataillon traverse la Maine par vent violent et pluie. Le pas des hommes, même si l'ordre de rompre le pas aurait été donné, combiné à l'oscillation provoquée par le vent et à la corrosion des câbles d'ancrage, met la structure en résonance. Un câble rompt ; le tablier bascule et précipite les soldats dans la rivière en crue.",
  "C'est l'une des plus graves catastrophes de génie civil du XIXe siècle. Elle met en cause toute une génération de ponts suspendus à câbles de fil de fer et conduit à les remplacer progressivement, ainsi qu'à normaliser la consigne de rompre le pas.",
  "Un monument au cimetière de l'Est et une plaque sur le quai rappellent les victimes. Le pont a été reconstruit en 1858."],
 "Pont_de_la_Basse-Cha%C3%AEne",lat=47.4760,lon=-0.5600),
]

saintetienne=[
A("politique","Saint-Étienne tourne la page après l'affaire Perdriau","Mars 2026 · Hôtel de ville",
 "Le maire Gaël Perdriau, mis en cause en 2022 dans une affaire de chantage à la vidéo intime contre son premier adjoint, a quitté la mairie. En 2026, le socialiste Régis Juanico reprend la ville.",
 "Régis Juanico est maire de Saint-Étienne depuis mars 2026, après le mandat marqué par l'affaire Perdriau et l'intérim de Jean-Pierre Berger.",
 ["En août 2022, Mediapart révèle que des proches du maire Gaël Perdriau ont organisé un chantage contre son premier adjoint Gilles Artigues, filmé à son insu lors d'une soirée privée, pour obtenir son silence politique. Perdriau, mis en examen notamment pour chantage et détournement de fonds publics, refuse de démissionner malgré les appels de son parti, dont il est exclu, et de la quasi-totalité du conseil municipal.",
  "Il finit par céder la mairie en 2024 à Jean-Pierre Berger, resté en fonction jusqu'au scrutin. Le procès de l'affaire a été renvoyé devant le tribunal correctionnel.",
  "En mars 2026, l'ancien député socialiste Régis Juanico l'emporte. La ville, dont la population a reculé de 220 000 à 170 000 habitants depuis les années 1970, mise sur la Cité du design et le label UNESCO de ville créative."],
 "Ga%C3%ABl_Perdriau",lat=45.4397,lon=4.3872),
A("histoire","La Manufacture d'armes et le premier chemin de fer","1764-1827 · Toute la ville",
 "La Manufacture royale d'armes a fait de Saint-Étienne une ville d'ouvriers qualifiés. C'est de là que part, en 1827, la première ligne de chemin de fer de France, pour descendre le charbon vers la Loire.",
 "Saint-Étienne doit son industrialisation à la Manufacture royale d'armes, créée en 1764, au charbon et à la première ligne ferroviaire française, inaugurée en 1827 vers Andrézieux.",
 ["La ville produisait déjà des armes depuis le XVIe siècle ; la manufacture royale structure la filière et fait vivre des milliers d'armuriers à domicile. S'y ajoutent la rubanerie, la quincaillerie, puis le cycle, avec Manufrance et ses catalogues de vente par correspondance.",
  "Le chemin de fer de Saint-Étienne à Andrézieux, long de 18 kilomètres et ouvert le 1er octobre 1827, est le premier de France : il descend le charbon vers la Loire, d'abord par traction animale et par gravité, avant l'arrivée des locomotives.",
  "Le dernier puits de mine a fermé en 1983. Le musée de la Mine, installé au puits Couriot, se visite ; les terrils font partie du paysage urbain."],
 "Chemin_de_fer_de_Saint-%C3%89tienne_%C3%A0_Andr%C3%A9zieux",lat=45.4420,lon=4.3850),
A("sport","Les Verts, la plus grande équipe à n'avoir jamais gagné","1976 · Stade Geoffroy-Guichard",
 "Finale de Coupe d'Europe 1976 à Glasgow : deux tirs stéphanois frappent les poteaux carrés avant que le Bayern ne marque. Les Verts reviennent battus et sont reçus comme des héros par des centaines de milliers de personnes.",
 "L'AS Saint-Étienne, dix fois championne de France, a perdu la finale de la Coupe des clubs champions le 12 mai 1976 contre le Bayern Munich, 1-0.",
 ["L'équipe de Robert Herbin, avec Curkovic, Janvion, Lopez, Bathenay, Larqué et Rocheteau, avait éliminé le Dynamo Kiev et le PSV. En finale, à Hampden Park, deux frappes de Bathenay et Santini heurtent la barre transversale ; les poteaux carrés du stade écossais, qui renvoient le ballon au lieu de l'accompagner, sont entrés dans la légende comme responsables de la défaite.",
  "Le retour à Paris puis à Saint-Étienne rassemble des foules considérables ; les Verts sont reçus à l'Élysée. L'engouement national pour ce club ouvrier reste un phénomène unique dans l'histoire du football français.",
  "Geoffroy-Guichard, le « Chaudron », est l'un des stades les plus bruyants d'Europe. Le club a connu depuis des descentes en deuxième division et une affaire de caisse noire qui l'avait rétrogradé en 1982."],
 "Association_sportive_de_Saint-%C3%89tienne",lat=45.4608,lon=4.3900),
]

tours=[
A("politique","Tours reste aux écologistes","Mars 2026 · Hôtel de ville",
 "Emmanuel Denis, élu en 2020 dans la vague verte, a été réélu en 2026. Avec Lyon et Grenoble, Tours est l'une des rares villes conservées par les écologistes.",
 "Emmanuel Denis est maire de Tours depuis 2020 et a été réélu en mars 2026.",
 ["Il avait pris la ville au centriste Christophe Bouchet, après vingt-cinq ans de mandats de Jean Germain puis de ses successeurs. Jean Germain, maire socialiste de 1995 à 2014 et sénateur, s'est suicidé en avril 2015, la veille de son procès dans l'affaire dite des mariages chinois, où il était poursuivi pour détournement de fonds publics ; le dossier a été clos par son décès et sa veuve a obtenu la reconnaissance d'un acharnement médiatique.",
  "Le mandat d'Emmanuel Denis a porté sur la seconde ligne de tramway, la végétalisation et la limitation de la circulation, sujets de tension avec l'opposition.",
  "Les écologistes conservent Tours, Lyon et Grenoble en 2026, mais perdent six villes gagnées en 2020, dont Bordeaux, Strasbourg et Besançon."],
 "Emmanuel_Denis",lat=47.3941,lon=0.6848),
A("patrimoine","Saint-Martin, le saint qui a coupé son manteau","IVe siècle · Basilique Saint-Martin",
 "Le soldat romain qui partage son manteau avec un pauvre à Amiens devient évêque de Tours et le saint le plus populaire de Gaule. Son tombeau a fait de la ville un pèlerinage majeur, avant d'être rasé à la Révolution.",
 "Saint Martin, évêque de Tours de 371 à 397, est l'un des saints les plus vénérés de France ; son tombeau a fait de Tours un grand lieu de pèlerinage pendant plus de mille ans.",
 ["Officier romain, il partage à Amiens la moitié de son manteau avec un mendiant, épisode mille fois représenté. Devenu moine puis évêque malgré lui, il évangélise les campagnes et fonde Marmoutier. Sa « chapelle », le reliquaire de son manteau, a donné le mot chapelle et chapelain.",
  "L'immense basilique romane bâtie sur son tombeau attire les pèlerins de toute l'Europe, et les rois mérovingiens puis capétiens s'en font les protecteurs. Vendue comme bien national et démolie à partir de 1797, elle ne laisse que deux tours, dont la tour Charlemagne.",
  "La basilique actuelle, néo-byzantine, a été construite en 1902 sur l'emplacement retrouvé du tombeau. Le 11 novembre, jour de la Saint-Martin, reste férié dans plusieurs pays."],
 "Basilique_Saint-Martin_de_Tours",lat=47.3945,lon=0.6830),
A("histoire","Les châteaux de la Loire, une cour qui ne tenait pas en place","XVe-XVIe siècle · Vallée de la Loire",
 "Pendant plus d'un siècle, la France a été gouvernée depuis la Touraine, dans des châteaux bâtis pour la chasse et le prestige. La cour déménageait avec ses meubles, ses tapisseries et ses milliers de chevaux.",
 "Entre le règne de Charles VII et celui d'Henri III, les rois de France ont résidé le plus souvent dans le Val de Loire, autour de Tours, Amboise, Blois et Chambord.",
 ["La guerre de Cent Ans a chassé la cour de Paris ; Charles VII s'installe à Chinon et Loches. Louis XI gouverne depuis Plessis-lès-Tours et développe la soierie tourangelle. François Ier fait construire Chambord, 440 pièces jamais habitées plus de quelques semaines d'affilée, avec son escalier à double révolution que la tradition attribue à Léonard de Vinci, installé au Clos Lucé à Amboise où il meurt en 1519.",
  "La cour est itinérante : elle se déplace avec des milliers de personnes, des coffres de tapisseries et de vaisselle ; les châteaux sont vides entre deux séjours. L'installation définitive à Paris puis à Versailles date du XVIIe siècle.",
  "Le Val de Loire, de Sully-sur-Loire à Chalonnes, est inscrit au patrimoine mondial depuis 2000 au titre de paysage culturel vivant."],
 "Ch%C3%A2teaux_de_la_Loire",lat=47.3941,lon=0.6848,protection="UNESCO, 2000"),
]

cities=[("29019","Brest","Finistère",48.3904,-4.4861,brest),
        ("76351","Le Havre","Seine-Maritime",49.4944,0.1079,lehavre),
        ("76540","Rouen","Seine-Maritime",49.4432,1.0999,rouen),
        ("51454","Reims","Marne",49.2583,4.0317,reims),
        ("21231","Dijon","Côte-d'Or",47.3220,5.0415,dijon),
        ("38185","Grenoble","Isère",45.1885,5.7245,grenoble),
        ("63113","Clermont-Ferrand","Puy-de-Dôme",45.7772,3.0870,clermont),
        ("49007","Angers","Maine-et-Loire",47.4712,-0.5518,angers),
        ("42218","Saint-Étienne","Loire",45.4397,4.3872,saintetienne),
        ("37261","Tours","Indre-et-Loire",47.3941,0.6848,tours)]
idx=json.load(open('index.json'))
for insee,name,dept,lat,lon,arts in cities:
    path=f"communes/{insee}.json"
    if os.path.exists(path):
        p=json.load(open(path)); have={a.get("wiki") for a in p["anecdotes"]}
        p["anecdotes"]+=[a for a in arts if a.get("wiki") not in have]
    else:
        p={"id":f"{insee}","insee":insee,"name":name,"dept":dept,"kind":"commune","lat":lat,"lon":lon,"anecdotes":arts}
    json.dump(p,open(path,'w'),ensure_ascii=False,indent=1)
    idx["communes"][insee]={"name":name,"count":len(p["anecdotes"]),"updated":"2026-10-07"}
    print(name,len(p["anecdotes"]))
json.dump(idx,open('index.json','w'),ensure_ascii=False,indent=1)
print(sum(v["count"] for v in idx["communes"].values()),"articles",len(idx["communes"]),"communes")
