import json, os
from urllib.parse import quote
W="https://fr.wikipedia.org/wiki/"
def wk(t): return quote(t.replace(" ","_"),safe="_(),-.")
def A(cat,title,label,teaser,lead,body,wiki,more=None,timeline=None,lat=None,lon=None,links=None,access=None,protection=None):
    w=wk(wiki)
    return {"category":cat,"title":title,"label":label,"teaser":teaser,"lead":lead,"text":lead,"body":body,"more":more or [],"timeline":timeline,"links":links,"wiki":w,"source":W+w,"lat":lat,"lon":lon,"access":access,"protection":protection}
def L(kind,title,url,note): return {"kind":kind,"title":title,"url":url,"note":note}
def T(*p): return [{"year":y,"text":t} for y,t in p]

# ---------------------------------------------------------------- LA ROCHELLE
larochelle=[
A("politique","Olivier Falorni, tombeur de Ségolène Royal devenu maire","2012-2026 · Hôtel de ville",
 "En 2012, exclu du PS, il bat Ségolène Royal aux législatives. En mars 2026, le député divers gauche conquiert la mairie de La Rochelle avec 43,66 % des voix au second tour.",
 "Olivier Falorni, divers gauche, est maire de La Rochelle depuis les municipales de mars 2026, remportées au second tour avec 43,66 % des voix.",
 ["Ancien premier secrétaire de la fédération socialiste de Charente-Maritime, Olivier Falorni refuse en 2012 de céder la 1re circonscription à Ségolène Royal, investie par le Parti socialiste. Exclu du parti, il maintient sa candidature et l'emporte au second tour, le 17 juin 2012. La campagne devient une affaire nationale lorsque Valérie Trierweiler, compagne du président François Hollande, publie sur Twitter un message de soutien à l'adversaire de l'ex-compagne du chef de l'État.",
  "Réélu député sans interruption depuis, il se présente aux municipales de mars 2026. Au second tour, sa liste devance celle d'union de la gauche conduite par Maryline Simoné (29,99 %), celle de Christophe Batcabe, divers droite (16,42 %), et celle du maire sortant Thibaut Guiraud (9,94 %). Elle obtient 36 des 49 sièges du conseil municipal.",
  "Le scrutin clôt une période instable : Jean-François Fountaine, maire depuis 2014, avait démissionné en juin 2025 et le conseil municipal avait élu le 16 juin son adjoint Thibaut Guiraud, docteur en pharmacologie et ancien directeur de clinique, pour terminer le mandat."],
 "Olivier Falorni"),
A("personnalites","Michel Crépeau, le maire des vélos jaunes","1971-1999 · La Rochelle",
 "Maire pendant vingt-huit ans, candidat à l'Élysée en 1981, trois fois ministre, il a lancé en 1976 à La Rochelle les premiers vélos en libre-service de France.",
 "Michel Crépeau, avocat radical de gauche, a dirigé La Rochelle de 1971 à sa mort en 1999 et fait de la ville un laboratoire de l'écologie urbaine.",
 ["Élu maire en 1971, Michel Crépeau mène une politique alors inhabituelle : secteur piétonnier dans le centre ancien, défense du littoral contre les promoteurs, puis, en 1976, mise à disposition gratuite de vélos peints en jaune. L'expérience, la première du genre en France, préfigure de trente ans les systèmes de vélos partagés des grandes villes.",
  "Président du Mouvement des radicaux de gauche, il se présente à l'élection présidentielle de 1981 et recueille 2,21 % des voix avant de se rallier à François Mitterrand. Il devient ministre de l'Environnement, puis du Commerce et de l'Artisanat, et brièvement garde des Sceaux en 1986.",
  "Député et maire jusqu'au bout, il est victime d'un malaise à l'Assemblée nationale en mars 1999 et meurt quelques jours plus tard. La Rochelle a accueilli en 1997 l'une des premières journées sans voiture organisées en France."],
 "Michel Crépeau",
 timeline=T(("1971","Élu maire de La Rochelle."),("1976","Lancement des vélos jaunes en libre-service."),("1981","Candidat à l'élection présidentielle, puis ministre de l'Environnement."),("1986","Garde des Sceaux dans le dernier gouvernement Fabius."),("1999","Mort en fonctions, après un malaise à l'Assemblée."))),
A("histoire","Le grand siège de La Rochelle par Richelieu","1627-1628 · Digue de Richelieu",
 "Quatorze mois d'encerclement, une digue fermant la baie, une population décimée par la faim : la place forte protestante capitule devant Louis XIII le 28 octobre 1628.",
 "De septembre 1627 à octobre 1628, l'armée de Louis XIII, conduite par Richelieu, assiège La Rochelle, principale place de sûreté des protestants français.",
 ["Depuis l'édit de Nantes, La Rochelle est une république marchande protestante quasi autonome, alliée de l'Angleterre. En juillet 1627, le duc de Buckingham débarque sur l'île de Ré pour soutenir les Rochelais ; son échec devant la citadelle de Saint-Martin laisse la ville seule face à l'armée royale.",
  "Richelieu fait barrer l'entrée de la baie par une digue de près d'un kilomètre et demi, faite de navires coulés, de pieux et de pierres, qui empêche les flottes anglaises de ravitailler la ville. Le maire Jean Guiton, élu en avril 1628, refuse toute reddition. La famine tue la majorité des habitants : la ville, qui en comptait environ 28 000, n'en abrite plus que quelques milliers à la capitulation, le 28 octobre 1628.",
  "Louis XIII entre dans la ville le 1er novembre. Les privilèges municipaux sont abolis, les fortifications côté terre rasées. Un an plus tard, la paix d'Alès retire aux protestants leurs places fortes : la chute de La Rochelle met fin à leur puissance politique et militaire dans le royaume."],
 "Siège de La Rochelle (1627-1628)",
 more=["La table de marbre sur laquelle Jean Guiton aurait planté son poignard en jurant de résister est conservée à l'hôtel de ville."]),
A("histoire","La Rochelle épargnée par un pacte entre deux marins","1944-1945 · Poche de La Rochelle",
 "À l'automne 1944, l'amiral allemand Schirlitz et le capitaine de frégate Hubert Meyer conviennent de ne pas détruire la ville. Elle est libérée intacte le 9 mai 1945.",
 "Pendant huit mois, de l'automne 1944 à mai 1945, La Rochelle reste une poche allemande, préservée grâce à un accord négocié entre l'occupant et un officier de marine français.",
 ["Après le débarquement, la Wehrmacht se retranche dans les ports de l'Atlantique pour priver les Alliés de leurs installations. À La Rochelle, la garnison du vice-amiral Ernst Schirlitz tient la ville, le port de La Pallice et l'île de Ré, encerclés par les Forces françaises de l'intérieur.",
  "Le capitaine de frégate Hubert Meyer négocie avec Schirlitz une convention : les Allemands renoncent à faire sauter le port et la ville, les Français s'engagent à ne pas lancer d'offensive au-delà d'une ligne fixée. Les combats se limitent à la périphérie, et la vieille ville échappe aux destructions qui frappent Royan, rasée par les bombardements alliés de janvier et avril 1945.",
  "La garnison se rend après la capitulation allemande et les troupes françaises entrent dans la ville le 9 mai 1945. La Rochelle est l'une des dernières villes de France libérées, et l'une des rares grandes villes portuaires de l'Atlantique à sortir de la guerre presque intacte."],
 "Poche de La Rochelle"),
A("insolite","Das Boot et Indiana Jones tournés à La Pallice","1941-1981 · Base sous-marine de La Pallice",
 "Le bunker qui abritait les U-Boote de la 3e flottille a servi de décor en 1981 à deux films, « Das Boot » de Wolfgang Petersen et « Les Aventuriers de l'arche perdue ».",
 "La base sous-marine de La Pallice, construite par l'occupant à partir d'avril 1941, est restée debout et a servi de décor à deux grands films de 1981.",
 ["Les travaux commencent en avril 1941 au fond du port de La Pallice, et les premiers sous-marins de la 3e flottille, transférée de Kiel, y arrivent à la fin de l'année. Les équipages logent dans la ville tandis que les bâtiments sont réparés dans les alvéoles, protégés par plusieurs mètres de béton.",
  "En mai 1943, au plus fort de la bataille de l'Atlantique, la base accueille jusqu'à dix-neuf U-Boote en même temps. Le même mois, les Alliés coulent quarante et un sous-marins allemands : c'est le tournant de la guerre sous-marine. Les bombardements visant la base touchent les entrepôts voisins sans entamer le bunker.",
  "Indestructible et trop coûteux à démolir, l'ouvrage reste après la guerre propriété portuaire. Le réalisateur Wolfgang Petersen y tourne les scènes finales de « Das Boot », et Steven Spielberg celles du repaire de sous-marins des « Aventuriers de l'arche perdue », sortis tous deux en 1981."],
 "Base sous-marine de La Rochelle",
 links=[L("film","« Das Boot » (1981), de Wolfgang Petersen","https://fr.wikipedia.org/wiki/Das_Boot","Les scènes du retour au port ont été tournées dans la base"),
        L("film","« Les Aventuriers de l'arche perdue » (1981), de Steven Spielberg","https://fr.wikipedia.org/wiki/Les_Aventuriers_de_l%27arche_perdue","La base sert de repaire aux sous-marins allemands")],
 lat=46.1583,lon=-1.2278,access="Zone portuaire, le bunker ne se visite pas"),
A("patrimoine","La tour de la Lanterne, prison aux graffitis","XVe siècle · Vieux-Port",
 "Phare médiéval à l'entrée du Vieux-Port, la tour de la Lanterne a servi de prison pendant trois siècles. Des marins et des corsaires y ont gravé leurs navires dans la pierre.",
 "Avec les tours Saint-Nicolas et de la Chaîne, la tour de la Lanterne garde l'entrée du Vieux-Port de La Rochelle depuis le XVe siècle.",
 ["Construite au XVe siècle, la tour servait de phare : un fanal allumé au sommet de sa flèche guidait les navires vers le chenal. En face, une chaîne tendue chaque soir entre les tours Saint-Nicolas et de la Chaîne fermait le port, ce qui a donné son nom à la seconde.",
  "Du XVIIe au XIXe siècle, la Lanterne sert de prison militaire. Les détenus, souvent des marins anglais, hollandais ou espagnols capturés en mer, et des corsaires, ont gravé dans les murs des centaines de graffitis : noms, dates et surtout des navires dessinés avec précision, qui forment aujourd'hui une source pour les historiens de la marine.",
  "Les trois tours, épargnées lors du démantèlement des fortifications après le siège de 1628, sont aujourd'hui gérées par le Centre des monuments nationaux."],
 "Tour de la Lanterne",
 lat=46.1557,lon=-1.1567,access="Centre des monuments nationaux, billet commun aux trois tours",protection="Monument historique classé"),
]

# ---------------------------------------------------------------- SAINT-NAZAIRE
saintnazaire=[
A("politique","David Samzun, un siècle de mairie à gauche","1925-2026 · Hôtel de ville",
 "Saint-Nazaire vote à gauche depuis un siècle. En mars 2026, David Samzun a été réélu avec 48,53 % des voix, loin devant l'union de la gauche et le Rassemblement national.",
 "David Samzun, divers gauche, maire depuis 2014, a été réélu en mars 2026 au second tour avec 48,53 % des voix et 37 sièges sur 49.",
 ["La ville ouvrière des chantiers navals a été dirigée près de quarante ans par le socialiste François Blancho, maire de 1925 à 1940 puis de 1945 à 1972 et sous-secrétaire d'État à la Marine dans le gouvernement du Front populaire. Il pilote la reconstruction d'une ville détruite par les bombardements.",
  "Joël Batteux, maire socialiste de 1983 à 2014, engage la reconversion de la base sous-marine et le projet Ville-Port, qui reconnecte le centre au front de mer. David Samzun, son successeur, est réélu en 2020.",
  "Au second tour de mars 2026, sa liste devance celle d'union de la gauche conduite par Violaine Lucas (22,97 %), celle du Rassemblement national menée par Julio Pichon (17,39 %) et celle de Denis Chéreau, divers centre (11,11 %)."],
 "David Samzun"),
A("histoire","Opération Chariot, le raid sur la forme Joubert","28 mars 1942 · Forme Joubert",
 "Bourré d'explosifs, le destroyer HMS Campbeltown éperonne la seule cale sèche de l'Atlantique capable d'accueillir le Tirpitz. Son explosion, des heures plus tard, la met hors service jusqu'à la fin de la guerre.",
 "Dans la nuit du 27 au 28 mars 1942, des commandos britanniques attaquent le port de Saint-Nazaire pour détruire la forme Joubert, seule cale sèche de la façade atlantique capable d'accueillir le cuirassé allemand Tirpitz.",
 ["La forme Joubert a été construite pour le paquebot Normandie. Pour l'Amirauté britannique, la détruire, c'est empêcher le Tirpitz de venir réparer sur l'Atlantique et le contraindre à rester en Norvège, loin des convois alliés.",
  "Le HMS Campbeltown, ancien destroyer américain maquillé en navire allemand, remonte l'estuaire avec une flottille de vedettes. Repéré, il force le passage sous le feu et s'encastre dans la porte de la cale vers 1 h 30. Les commandos détruisent les installations voisines, mais la plupart des vedettes sont coulées : sur environ 600 hommes engagés, 169 sont tués et plus de 200 faits prisonniers.",
  "Le lendemain vers midi, les explosifs dissimulés dans la coque détonent alors que des soldats allemands visitent l'épave : la porte est arrachée et la cale reste inutilisable jusqu'en 1948. Cinq participants reçoivent la Victoria Cross. Les jours suivants, des tirs de panique de l'occupant font des victimes parmi les civils nazairiens."],
 "Opération Chariot"),
A("histoire","Saint-Nazaire rasée, dernière poche libérée","1943-1945 · Poche de Saint-Nazaire",
 "Bombardée pour atteindre une base sous-marine qui résiste, la ville est détruite aux trois quarts. Ses habitants ne sont libérés que le 11 mai 1945, trois jours après la capitulation allemande.",
 "Entre 1942 et 1945, Saint-Nazaire est presque entièrement détruite par les bombardements alliés, puis reste occupée jusqu'au 11 mai 1945, au cœur de la dernière poche allemande de France.",
 ["Les Allemands construisent à partir de 1941 une base sous-marine géante face au bassin. Pour la neutraliser, l'aviation alliée bombarde le port à de nombreuses reprises ; les raids de février 1943, menés en partie avec des bombes incendiaires, détruisent l'essentiel du centre-ville. La base, protégée par une dalle de béton de plusieurs mètres, n'est presque pas touchée. La population est évacuée au printemps 1943.",
  "Après la percée alliée de l'été 1944, près de 30 000 soldats allemands se retranchent autour de Saint-Nazaire, de la Brière à Pornic. Des dizaines de milliers de civils vivent enfermés dans cette poche pendant neuf mois, ravitaillés par des convois de la Croix-Rouge.",
  "La reddition est signée le 8 mai 1945 et la cérémonie officielle a lieu le 11 mai à Bouvron. Saint-Nazaire est ainsi la dernière parcelle du territoire métropolitain libérée. La ville est reconstruite selon un plan en damier qui ne reprend presque rien de l'ancien tracé."],
 "Poche de Saint-Nazaire"),
A("faits_divers","Seize morts sur la passerelle du Queen Mary 2","15 novembre 2003 · Chantiers de l'Atlantique",
 "Lors d'une visite réservée aux familles des ouvriers, une passerelle d'accès au paquebot s'effondre. Seize personnes meurent, quelques semaines avant la livraison du plus grand paquebot de l'époque.",
 "Le 15 novembre 2003, aux Chantiers de l'Atlantique, une passerelle reliant le quai au Queen Mary 2 cède sous le poids des visiteurs : seize personnes sont tuées et une trentaine blessées.",
 ["Pour fêter l'achèvement du Queen Mary 2, commandé par la compagnie Cunard, les chantiers organisent des visites pour les salariés des entreprises sous-traitantes et leurs proches. En fin de matinée, une passerelle provisoire chargée d'une cinquantaine de personnes se décroche et bascule dans la cale, une quinzaine de mètres plus bas.",
  "Les expertises mettent en cause la conception et le montage de la passerelle, installée par un sous-traitant. Le procès, qui s'ouvre à Saint-Nazaire en 2007, aboutit en février 2008 à la condamnation des Chantiers de l'Atlantique et de l'entreprise chargée de la passerelle pour homicides et blessures involontaires, ainsi que de plusieurs cadres à des peines avec sursis.",
  "Le paquebot est livré en décembre 2003 et part pour sa traversée inaugurale en janvier 2004. Un monument rend hommage aux victimes près de l'entrée des chantiers."],
 "Queen Mary 2"),
A("insolite","Monsieur Hulot en vacances à Saint-Marc-sur-Mer","1951-1953 · Plage de Saint-Marc-sur-Mer",
 "Jacques Tati a tourné « Les Vacances de M. Hulot » en 1951 dans ce quartier balnéaire de Saint-Nazaire. L'hôtel du film accueille toujours des clients, et une statue de Hulot regarde la mer.",
 "« Les Vacances de M. Hulot », sorti en 1953, a été tourné par Jacques Tati sur la plage et à l'hôtel de Saint-Marc-sur-Mer, à l'ouest de Saint-Nazaire.",
 ["Tati cherche une station modeste, loin des grandes plages mondaines. Il choisit Saint-Marc-sur-Mer et son hôtel de la Plage, où il tourne pendant l'été 1951 avec des habitants comme figurants. Le film suit un vacancier maladroit qui sème le désordre dans une pension de famille, presque sans dialogues.",
  "Le film obtient le prix Louis-Delluc et lance le personnage de Monsieur Hulot, que Tati reprend dans « Mon oncle » puis « Playtime ». L'hôtel de la Plage, toujours en activité, a conservé son nom, et une statue en bronze du personnage, pipe à la bouche, a été installée face à la mer."],
 "Les Vacances de monsieur Hulot",
 links=[L("film","« Les Vacances de M. Hulot » (1953), de Jacques Tati","https://fr.wikipedia.org/wiki/Les_Vacances_de_monsieur_Hulot","Tourné à Saint-Marc-sur-Mer à l'été 1951")]),
]

# ---------------------------------------------------------------- LORIENT
lorient=[
A("politique","Fabrice Loher, réélu de justesse face à Damien Girard","1981-2026 · Hôtel de ville",
 "Élu en 2020 après près de quarante ans de mairie socialiste, le centriste Fabrice Loher a été réélu en mars 2026 avec 45,29 % des voix, 560 de plus que le député écologiste Damien Girard.",
 "Fabrice Loher, divers centre, maire de Lorient depuis 2020, a été réélu en mars 2026 au second tour avec 45,29 % des voix contre 42,65 % au député Damien Girard.",
 ["De 1981 à 2020, Lorient est dirigée par deux socialistes : Jean-Yves Le Drian jusqu'en 1998, puis Norbert Métairie. En 2020, Fabrice Loher, centriste, l'emporte et met fin à près de quarante ans de mairie socialiste.",
  "En mars 2026, il arrive en tête du premier tour avec 35,4 %. La gauche, divisée au premier tour entre Damien Girard, député écologiste élu en 2024, et Gaëlle Le Stradic, divers gauche, se rassemble derrière Girard au second. Celui-ci obtient 9 046 voix contre 9 606 au maire sortant ; la liste du Rassemblement national de Théo Thomas recueille 12,06 %.",
  "Avec la prime majoritaire, la liste de Fabrice Loher détient 33 des 45 sièges du conseil municipal."],
 "Fabrice Loher"),
A("personnalites","Jean-Yves Le Drian, de Lorient au Quai d'Orsay","1981-2022 · Lorient",
 "Né à Lorient en 1947, maire à 34 ans, il a été ministre de la Défense de François Hollande puis ministre des Affaires étrangères d'Emmanuel Macron pendant cinq ans.",
 "Jean-Yves Le Drian, né à Lorient le 30 juin 1947, a été maire de la ville de 1981 à 1998 avant de devenir l'un des ministres les plus durables de la Ve République.",
 ["Professeur d'histoire, il entre au conseil municipal en 1977 et devient maire en 1981, à 34 ans. Il est secrétaire d'État à la Mer en 1991-1992, puis préside la région Bretagne de 2004 à 2012.",
  "François Hollande le nomme ministre de la Défense en 2012 : il conduit les interventions au Mali et au Sahel et négocie de grands contrats d'armement, dont la vente de Rafale à l'Égypte et à l'Inde. En 2017, il rejoint Emmanuel Macron, qui en fait son ministre de l'Europe et des Affaires étrangères jusqu'en 2022."],
 "Jean-Yves Le Drian",
 timeline=T(("1947","Naissance à Lorient."),("1981","Élu maire de Lorient."),("2004","Président du conseil régional de Bretagne."),("2012","Ministre de la Défense."),("2017","Ministre de l'Europe et des Affaires étrangères, jusqu'en 2022."))),
A("histoire","L'Orient, une ville née de la Compagnie des Indes","1666 · Enclos du port",
 "Lorient doit son nom à un navire, le Soleil d'Orient, construit sur le chantier que la Compagnie des Indes ouvre en 1666 au bord du Scorff.",
 "En 1666, la Compagnie française des Indes orientales, créée par Colbert deux ans plus tôt, installe ses chantiers et ses magasins sur une lande au fond de la rade, à l'origine de la ville de Lorient.",
 ["Colbert veut doter la France d'une compagnie capable de concurrencer les Hollandais et les Anglais dans le commerce des épices, du thé et des cotonnades d'Asie. Port-Louis, à l'entrée de la rade, est trop étroit : la Compagnie obtient un terrain sur la rive du Scorff et y construit ses navires.",
  "L'un des premiers vaisseaux lancés s'appelle le Soleil d'Orient. Le chantier prend le nom de « l'Orient », qui devient celui de la ville. Au XVIIIe siècle, toutes les ventes de marchandises rapportées d'Asie par la Compagnie s'y tiennent, et la population grimpe à plus de 20 000 habitants.",
  "Après la suppression du monopole de la Compagnie en 1769, l'État reprend le port, qui devient un arsenal de la Marine. Les marchandises des Indes se visitent aujourd'hui au musée de la Compagnie des Indes, dans la citadelle de Port-Louis, en face."],
 "Compagnie française des Indes orientales"),
A("histoire","Lorient rasée pour une base restée intacte","1941-1945 · Keroman",
 "Pour frapper la principale base de sous-marins allemande, les Alliés bombardent Lorient début 1943 et détruisent la ville presque entière. Les bunkers de Keroman, eux, résistent.",
 "Entre janvier et février 1943, les bombardements alliés détruisent la quasi-totalité de Lorient, sans parvenir à percer les abris de la base de sous-marins de Keroman.",
 ["L'amiral Dönitz installe dès 1940 son quartier général à Kernevel, face à Lorient, et l'organisation Todt construit à Keroman trois énormes bunkers capables d'abriter une trentaine de sous-marins. Lorient devient la principale base des U-Boote dans l'Atlantique.",
  "Faute de pouvoir détruire les bunkers, couverts de plusieurs mètres de béton, le gouvernement britannique décide début 1943 de raser la ville et ses infrastructures. Les raids de janvier et février 1943, à grand renfort de bombes incendiaires, détruisent près de 90 % de Lorient. La population a été évacuée, mais la base continue de fonctionner.",
  "Encerclée à partir d'août 1944, la poche de Lorient ne se rend que le 10 mai 1945. La Marine nationale occupe ensuite la base jusqu'en 1997 ; elle abrite aujourd'hui la Cité de la voile Éric Tabarly et le sous-marin Flore, ouvert à la visite."],
 "Base de sous-marins de Lorient",
 access="Sous-marin Flore et Cité de la voile ouverts à la visite"),
A("patrimoine","Le Festival interceltique, dix jours chaque août","Depuis 1971 · Centre-ville et port",
 "Depuis 1971, Lorient réunit chaque été les musiques et danses des pays celtes, de l'Irlande à la Galice. Le festival est devenu l'un des plus fréquentés de France.",
 "Le Festival interceltique de Lorient, créé en 1971, accueille chaque mois d'août pendant une dizaine de jours des musiciens et danseurs de Bretagne, d'Écosse, d'Irlande, du pays de Galles, des Asturies ou de Galice.",
 ["Le festival naît de la rencontre entre les fêtes de Lorient et le championnat national des bagadoù, les ensembles de cornemuses, bombardes et percussions, qui s'y installe au tournant des années 1970. Il s'ouvre ensuite aux autres nations celtes et aux diasporas, jusqu'en Acadie et en Australie.",
  "Chaque édition met à l'honneur un pays invité. La Grande Parade des nations celtes, le dimanche, voit défiler des milliers de musiciens dans les rues, et le championnat des bagadoù désigne le meilleur ensemble breton de l'année. La fréquentation se compte en centaines de milliers de visiteurs."],
 "Festival interceltique de Lorient"),
A("sport","FC Lorient, Coupe de France et relégation en 2002","2002 · Stade du Moustoir",
 "Le 11 mai 2002, le FC Lorient bat Bastia 1-0 au Stade de France et remporte la Coupe de France. La même saison, le club est relégué en deuxième division.",
 "Le FC Lorient a remporté la Coupe de France le 11 mai 2002 contre le SC Bastia, l'année même de sa descente en deuxième division.",
 ["Le club des Merlus, longtemps cantonné aux divisions inférieures, est construit dans les années 1980 et 1990 par l'entraîneur Christian Gourcuff, partisan d'un jeu de passes courtes. Il découvre la première division en 1998.",
  "En 2002, en finale au Stade de France, un but de Jean-Claude Darcheville suffit à battre Bastia. Mais le parcours en championnat est raté et Lorient descend, situation rare pour un vainqueur de la Coupe. Revenu en Ligue 1 en 2006 avec Gourcuff, le club installe en 2010 au Moustoir une pelouse synthétique, une première dans l'élite française."],
 "Football Club de Lorient"),
]

# ---------------------------------------------------------------- QUIMPER
quimper=[
A("politique","Isabelle Assih, première femme maire de Quimper","2020-2026 · Hôtel de ville",
 "Élue en 2020, la socialiste Isabelle Assih a été réélue en mars 2026 avec 49,82 % des voix au second tour, face à la droite de Guillaume Menguy.",
 "Isabelle Assih (PS), maire de Quimper depuis 2020, a été réélue en mars 2026 au second tour avec 49,82 % des voix et 37 sièges sur 49.",
 ["Quimper alterne entre gauche et droite depuis trente ans. Le socialiste Bernard Poignant, maire de 1989 à 2001 puis de 2008 à 2014, député européen et proche de François Hollande, dont il devient conseiller à l'Élysée, est battu en 2014 par Ludovic Jolivet, divers droite.",
  "En 2020, Isabelle Assih reprend la ville pour la gauche et devient la première femme à la diriger. En mars 2026, sa liste devance celle de Guillaume Menguy, divers droite (33,40 %), celle du Rassemblement national conduite par Christel Hénaff (8,57 %) et celle d'extrême gauche de Marie Lauwers (8,21 %)."],
 "Isabelle Assih"),
A("legende","Le roi Gradlon et la ville d'Ys engloutie","Légende · Cathédrale Saint-Corentin",
 "Entre les deux flèches de la cathédrale chevauche le roi Gradlon. Selon la légende, il a fui la ville d'Ys engloutie par l'océan et fait de Quimper sa capitale.",
 "Selon la légende bretonne, Gradlon, roi de Cornouaille, régnait sur Ys, une cité protégée de la mer par des digues, avant que la faute de sa fille Dahut ne la livre aux flots.",
 ["Ys est fermée par des portes dont le roi garde la clé. Dahut, fille de Gradlon, la lui dérobe pour un amant, qui ouvre les vannes : l'océan envahit la ville. Gradlon s'enfuit à cheval avec sa fille en croupe ; saint Guénolé lui ordonne de la jeter à l'eau pour échapper aux vagues. Dahut devient une sirène, et Ys demeure sous la mer, quelque part dans la baie de Douarnenez.",
  "Réfugié à Quimper, Gradlon y aurait installé saint Corentin comme premier évêque. Sa statue équestre, placée entre les flèches de la cathédrale, a été abattue sous la Révolution puis refaite au XIXe siècle. La légende a inspiré l'opéra « Le Roi d'Ys » d'Édouard Lalo, créé en 1888."],
 "Gradlon",
 links=[L("musique","« Le Roi d'Ys » (1888), opéra d'Édouard Lalo","https://fr.wikipedia.org/wiki/Le_Roi_d%27Ys","D'après la légende de la ville engloutie")]),
A("patrimoine","Saint-Corentin, la cathédrale au chœur désaxé","XIIIe-XIXe siècles · Place Saint-Corentin",
 "Le chœur de la cathédrale de Quimper n'est pas dans l'axe de la nef. Ses deux flèches ont été payées en 1854-1856 par une souscription d'un sou par an et par fidèle.",
 "La cathédrale Saint-Corentin de Quimper, commencée en 1239, est l'un des grands édifices gothiques de Bretagne, reconnaissable à la déviation de son axe et à ses flèches du XIXe siècle.",
 ["Le chœur est bâti au XIIIe siècle, la nef au XVe. Entre les deux, l'axe dévie nettement vers la gauche. La tradition y voit la tête inclinée du Christ sur la croix ; les historiens penchent plutôt pour des contraintes du terrain et des constructions voisines à l'époque du chantier.",
  "Faute d'argent, les tours de la façade restent sans flèche pendant quatre siècles. En 1854, l'évêque lance le « sou de Saint-Corentin » : chaque diocésain verse un sou par an pendant cinq ans. Les deux flèches de pierre sont achevées en 1856 et culminent à plus de 75 mètres."],
 "Cathédrale Saint-Corentin de Quimper",
 lat=47.9958,lon=-4.1022,access="Entrée libre en dehors des offices",protection="Monument historique classé"),
A("personnalites","Max Jacob, poète de Quimper mort à Drancy","1876-1944 · Quimper",
 "Né à Quimper, ami de Picasso et d'Apollinaire, converti au catholicisme, Max Jacob est arrêté par la Gestapo comme juif en février 1944 et meurt au camp de Drancy le 5 mars.",
 "Max Jacob, né à Quimper le 12 juillet 1876, poète et peintre, figure de Montmartre et du cubisme littéraire, est mort au camp de Drancy le 5 mars 1944.",
 ["Fils d'un tailleur juif de Quimper, il monte à Paris et rencontre en 1901 Pablo Picasso, avec qui il partage la misère du Bateau-Lavoir. Il fréquente Apollinaire, publie « Le Cornet à dés » en 1917 et devient une figure de l'avant-garde.",
  "Après une vision du Christ en 1909, il se convertit au catholicisme et se fait baptiser en 1915, avec Picasso pour parrain. Il se retire à partir de 1921 à Saint-Benoît-sur-Loire, près de l'abbaye.",
  "Arrêté par la Gestapo le 24 février 1944 en raison de ses origines juives, il est transféré au camp de Drancy, où il meurt d'une pneumonie onze jours plus tard. Plusieurs membres de sa famille quimpéroise sont morts en déportation. Le musée des Beaux-Arts de Quimper lui consacre une salle."],
 "Max Jacob",
 timeline=T(("1876","Naissance à Quimper."),("1901","Rencontre avec Picasso à Paris."),("1915","Baptême, Picasso pour parrain."),("1917","Publication du « Cornet à dés »."),("1944","Arrêté par la Gestapo, mort à Drancy le 5 mars."))),
A("personnalites","René Laennec, l'inventeur quimpérois du stéthoscope","1781-1826 · Quimper",
 "Né à Quimper en 1781, le médecin René Laennec invente le stéthoscope en 1816 à l'hôpital Necker, à Paris, avec un simple cahier roulé en tube.",
 "René Laennec, né à Quimper le 17 février 1781, a inventé le stéthoscope et fondé l'auscultation, l'examen qui consiste à écouter les bruits du corps.",
 ["En 1816, à l'hôpital Necker, il doit examiner une jeune patiente et juge inconvenant de poser l'oreille sur sa poitrine. Il roule un cahier en tube et constate qu'il entend les battements du cœur plus nettement. Il met ensuite au point un cylindre de bois, le stéthoscope.",
  "En 1819, il publie son « Traité de l'auscultation médiate », qui décrit les bruits de la respiration et du cœur et les relie aux lésions observées à l'autopsie. Atteint de tuberculose, la maladie qu'il a le mieux décrite, il meurt en Bretagne le 13 août 1826."],
 "René Laennec",
 timeline=T(("1781","Naissance à Quimper."),("1816","Invention du stéthoscope à l'hôpital Necker."),("1819","Traité de l'auscultation médiate."),("1826","Mort de la tuberculose en Bretagne."))),
A("patrimoine","La faïence de Quimper, du Midi au petit Breton","Depuis 1690 · Locmaria",
 "En 1690, le faïencier provençal Jean-Baptiste Bousquet s'installe à Locmaria, quartier de Quimper. Trois siècles plus tard, le décor du petit Breton peint à la main y est toujours produit.",
 "La faïence de Quimper est produite depuis 1690 dans le quartier de Locmaria, où un faïencier venu de Provence a fondé la première manufacture.",
 ["Jean-Baptiste Bousquet arrive de la région de Marseille et trouve à Locmaria l'argile, le bois et la rivière nécessaires. Les premières productions imitent les décors de Moustiers et de Rouen.",
  "Au XIXe siècle, les manufactures, dont celle d'Henriot et celle de la Hubaudière, adoptent les motifs qui feront leur succès : personnages en costume breton, fleurs, oiseaux, peints à main levée. Les deux maisons fusionnent au XXe siècle sous le nom HB-Henriot. Le musée de la Faïence, à Locmaria, retrace cette histoire."],
 "Faïence de Quimper"),
]

# ---------------------------------------------------------------- VANNES
vannes=[
A("politique","David Robo, réélu dès le premier tour en 2026","2001-2026 · Hôtel de ville",
 "Maire de Vannes depuis 2011, David Robo a été réélu le 15 mars 2026 dès le premier tour avec 50,40 % des voix, comme en 2014 et 2020.",
 "David Robo, divers droite, maire de Vannes depuis 2011, a été réélu au premier tour des municipales de mars 2026 avec 50,40 % des voix.",
 ["Il succède en 2011 à François Goulard, maire depuis 2001, ancien secrétaire d'État aux Transports et à la Mer puis ministre délégué à l'Enseignement supérieur et à la Recherche, qui quitte la mairie l'année où il prend la présidence du conseil général du Morbihan.",
  "Ancien membre de l'UMP, rallié à Horizons, le parti d'Édouard Philippe, David Robo préside aussi depuis 2020 l'agglomération Golfe du Morbihan-Vannes. En mars 2026, sa liste devance celle d'Audrey Essola, divers gauche (24,02 %), celle de Charles de Williencourt, divers droite (12,65 %), et celle du Rassemblement national menée par Valentin Legros (7,30 %). Elle obtient 35 sièges sur 45."],
 "David Robo"),
A("personnalites","Raymond Marcellin, ministre de l'Intérieur et maire de Vannes","1965-1977 · Vannes",
 "Ministre de l'Intérieur de 1968 à 1974, il a dirigé Vannes et le Morbihan. Son ministère a été éclaboussé en 1973 par l'affaire des micros du Canard enchaîné.",
 "Raymond Marcellin, maire de Vannes de 1965 à 1977 et président du conseil général du Morbihan pendant plus de trente ans, a été ministre de l'Intérieur de mai 1968 à février 1974.",
 ["Né en 1914 à Sézanne, dans la Marne, il s'implante dans le Morbihan après la guerre et cumule les mandats : député, sénateur, maire de Vannes, président du département de 1964 à 1998. Il occupe de nombreux ministères sous de Gaulle et Pompidou.",
  "Nommé place Beauvau au lendemain de Mai 68, il dissout plusieurs organisations d'extrême gauche et renforce les services de renseignement, ce qui lui vaut le surnom de « Raymond la matraque ».",
  "Le 3 décembre 1973, des agents de la DST sont surpris en train de poser des micros dans les nouveaux locaux du Canard enchaîné. L'affaire, surnommée le « Watergaffe », pèse sur sa fin de carrière ministérielle ; il quitte l'Intérieur en février 1974. Il meurt en 2004."],
 "Raymond Marcellin",
 timeline=T(("1914","Naissance à Sézanne (Marne)."),("1965","Élu maire de Vannes."),("1968","Ministre de l'Intérieur après Mai 68."),("1973","Affaire des micros du Canard enchaîné."),("2004","Mort à Paris."))),
A("histoire","1532, l'union de la Bretagne votée à Vannes","Août 1532 · Vannes",
 "Réunis à Vannes en août 1532, les États de Bretagne demandent à François Ier l'union perpétuelle du duché au royaume de France. Le roi l'accorde dans la foulée.",
 "En août 1532, les États de Bretagne réunis à Vannes adressent au roi François Ier une requête qui aboutit à l'union de la Bretagne à la France.",
 ["Depuis les mariages d'Anne de Bretagne avec Charles VIII puis Louis XII, le duché est lié à la couronne sans y être intégré. Claude de France, fille d'Anne, a épousé François Ier : leur fils aîné est l'héritier du duché comme du royaume.",
  "Le roi veut sceller l'union avant qu'une autre succession ne la remette en cause. Les États de Bretagne, réunis à Vannes, votent une requête demandant l'union, en échange du maintien des droits et libertés du pays : consentement à l'impôt, justice propre, privilèges des Bretons. Le roi, présent dans la région, l'accepte par un édit publié à Nantes, complété en septembre par l'édit du Plessis-Macé.",
  "Le jeune dauphin est couronné duc à Rennes la même année. La Bretagne devient une province du royaume, dotée d'un parlement et d'États qui défendront ces privilèges jusqu'à leur abolition, la nuit du 4 août 1789."],
 "Union de la Bretagne à la France"),
A("faits_divers","Le procès Le Scouarnec à Vannes","2025 · Tribunal judiciaire de Vannes",
 "Du 24 février au 28 mai 2025, l'ancien chirurgien Joël Le Scouarnec est jugé à Vannes pour viols et agressions sexuelles sur 299 patients, majoritairement mineurs. Il est condamné à vingt ans.",
 "Le 28 mai 2025, la cour criminelle du Morbihan, siégeant à Vannes, a condamné l'ancien chirurgien Joël Le Scouarnec à vingt ans de réclusion criminelle pour viols et agressions sexuelles sur 299 personnes.",
 ["Chirurgien digestif, Joël Le Scouarnec a exercé dans plusieurs hôpitaux, dont ceux de Vannes, Lorient, Quimperlé et Jonzac. Il est arrêté en 2017 après la plainte d'une fillette voisine, en Charente-Maritime. Les enquêteurs découvrent des carnets dans lesquels il consignait les abus commis sur ses patients entre 1989 et 2014, souvent pendant leur hospitalisation. Il a déjà été condamné en décembre 2020 à quinze ans de réclusion par la cour d'assises de Charente-Maritime, pour des faits commis sur quatre enfants.",
  "Le procès s'ouvre à Vannes le 24 février 2025. L'accusé reconnaît les faits. L'avocat général Stéphane Kellenberger requiert la peine maximale et une rétention de sûreté. La cour prononce vingt ans de réclusion criminelle avec une période de sûreté des deux tiers, l'interdiction d'exercer la médecine et de tout contact avec des mineurs, mais écarte la rétention de sûreté, ce qui déçoit de nombreuses victimes. Son avocat a annoncé qu'il ne ferait pas appel.",
  "Le procès a mis en lumière des défaillances : condamné dès 2005 par le tribunal correctionnel de Vannes à quatre mois avec sursis pour détention d'images pédopornographiques, il avait pu continuer à opérer des enfants sans que l'Ordre des médecins ni les hôpitaux ne l'en empêchent."],
 "Affaire Le Scouarnec"),
A("patrimoine","Les remparts et les lavoirs de la Garenne","IIIe-XVIIIe siècles · Jardins des remparts",
 "Vannes a conservé une large part de son enceinte, du mur gallo-romain à la tour du Connétable. À ses pieds, des lavoirs du XIXe siècle bordent la rivière au fond des jardins.",
 "Les remparts de Vannes, dont la construction s'étale de l'Antiquité tardive au XVIIe siècle, entourent encore une grande partie de la vieille ville.",
 ["La première enceinte est élevée à la fin du IIIe siècle pour protéger la ville gallo-romaine de Darioritum. Les ducs de Bretagne l'agrandissent aux XIVe et XVe siècles : le duc Jean IV fait bâtir le château de l'Hermine et ses successeurs la tour du Connétable, la plus haute de l'enceinte.",
  "Devenus inutiles, les remparts ne sont pas rasés, contrairement à ceux de nombreuses villes. Le château de l'Hermine est reconstruit au XVIIIe siècle en hôtel particulier. Au pied des murs, les jardins à la française et les lavoirs couverts de la rivière, où les lavandières travaillaient encore au XXe siècle, composent l'un des ensembles les plus visités de la ville."],
 "Remparts de Vannes",
 access="Jardins et promenade des remparts en accès libre",protection="Monument historique"),
A("personnalites","Vincent Ferrier, le prédicateur mort à Vannes","1419 · Cathédrale Saint-Pierre",
 "Venu de Valence, en Espagne, le dominicain Vincent Ferrier prêche dans toute la Bretagne et meurt à Vannes le 5 avril 1419. Ses reliques reposent dans la cathédrale.",
 "Le dominicain espagnol Vincent Ferrier, l'un des prédicateurs les plus célèbres du Moyen Âge, est mort à Vannes le 5 avril 1419 et y est inhumé.",
 ["Né à Valence vers 1350, il parcourt l'Europe en prêchant la pénitence devant des foules immenses. Appelé par le duc Jean V, il arrive en Bretagne en 1418 et prêche de ville en ville dans sa langue valencienne ; ses biographes lui attribuent des miracles dès son vivant.",
  "Épuisé, il meurt à Vannes. Les Espagnols réclament son corps, que les Vannetais conservent dans la cathédrale Saint-Pierre. Canonisé en 1455, il devient le saint patron de la ville et du diocèse."],
 "Vincent Ferrier"),
]

# ---------------------------------------------------------------- SAINT-MALO
saintmalo=[
A("politique","Gilles Lurton, réélu à Saint-Malo en 2026","2020-2026 · Hôtel de ville",
 "Ancien député, maire depuis 2020, Gilles Lurton a été réélu en mars 2026 avec 51,43 % des voix au second tour, très loin devant la gauche et le Rassemblement national.",
 "Gilles Lurton, divers droite, maire de Saint-Malo depuis 2020, a été réélu au second tour des municipales de mars 2026 avec 51,43 % des voix.",
 ["Saint-Malo est dirigée à droite et au centre depuis plus de trente ans. René Couanau, maire de 1989 à 2014 et député, puis Claude Renoult, de 2014 à 2020, ont précédé Gilles Lurton, ancien député Les Républicains de la circonscription de 2012 à 2017.",
  "En mars 2026, il obtient 47,9 % au premier tour, puis 51,43 % au second, devant Carole Le Bechec, divers gauche (21,81 %), Thidalack Abhay, Rassemblement national (15,02 %), et Céline Yadav, union de la gauche (11,74 %). Sa liste détient 33 sièges sur 43."],
 "Gilles Lurton"),
A("histoire","Août 1944, la cité corsaire réduite en cendres","Août 1944 · Intra-muros",
 "Pendant le siège de la ville par les Américains, en août 1944, la cité intra-muros brûle presque entièrement. Elle est reconstruite pierre par pierre pendant vingt-cinq ans.",
 "En août 1944, la garnison allemande du colonel Andreas von Aulock refuse de rendre Saint-Malo aux troupes américaines : les combats et les incendies détruisent environ 80 % de la ville close.",
 ["Hitler a ordonné de tenir les ports de l'Atlantique. Von Aulock se retranche dans la citadelle d'Aleth, à Saint-Servan, et fait détruire les installations portuaires. Les Américains, arrivés début août, pilonnent les positions allemandes ; dans la ville close, des incendies se propagent de maison en maison pendant plusieurs jours, sans pompiers ni eau.",
  "Von Aulock capitule le 17 août 1944. L'île de Cézembre, au large, résiste jusqu'au 2 septembre sous les bombardements. Dans l'intra-muros, la plupart des maisons d'armateurs et la cathédrale sont en ruines.",
  "La reconstruction, conduite sous la direction de l'architecte Louis Arretche, dure jusqu'aux années 1970. Elle reprend les silhouettes, les hauteurs et le granit d'origine, mais avec des intérieurs modernes : la ville que l'on visite aujourd'hui est en grande partie une reconstruction d'après-guerre."],
 "Bataille de Saint-Malo"),
A("personnalites","Chateaubriand, enterré sur l'îlot du Grand Bé","1768-1848 · Îlot du Grand Bé",
 "Né à Saint-Malo en 1768, l'auteur des « Mémoires d'outre-tombe » a choisi d'être enterré sur l'îlot du Grand Bé, accessible à pied seulement à marée basse.",
 "François-René de Chateaubriand, né à Saint-Malo le 4 septembre 1768, repose depuis 1848 dans une tombe sans nom sur l'îlot du Grand Bé, face à la ville.",
 ["Fils d'un armateur malouin, il passe son enfance entre Saint-Malo et le château de Combourg. Écrivain, diplomate et ministre des Affaires étrangères sous la Restauration, il consacre la fin de sa vie aux « Mémoires d'outre-tombe », publiés après sa mort.",
  "De son vivant, il obtient de la ville une concession sur le Grand Bé. Mort à Paris le 4 juillet 1848, il y est inhumé le 19 juillet sous une simple croix de granit, sans inscription. La tombe se visite à pied à marée basse ; la mer recouvre le chemin deux fois par jour."],
 "François-René de Chateaubriand",
 timeline=T(("1768","Naissance à Saint-Malo."),("1802","Succès du « Génie du christianisme »."),("1822","Ministre des Affaires étrangères."),("1848","Mort à Paris, inhumé au Grand Bé.")),
 lat=48.6553,lon=-2.0331,access="Accessible à pied à marée basse uniquement, horaires des marées à consulter"),
A("personnalites","Robert Surcouf, corsaire de l'océan Indien","1773-1827 · Saint-Malo",
 "Né à Saint-Malo, Robert Surcouf a capturé des dizaines de navires anglais dans l'océan Indien, dont le Kent en 1800, avant de finir armateur fortuné.",
 "Robert Surcouf, né à Saint-Malo le 12 décembre 1773, est le plus célèbre des corsaires malouins, ces marins privés autorisés par l'État à attaquer les navires ennemis.",
 ["Embarqué à quinze ans, il opère à partir de 1795 depuis l'île de France, actuelle île Maurice. Muni d'une lettre de marque, il s'attaque aux navires de la Compagnie anglaise des Indes orientales.",
  "Le 7 octobre 1800, avec la Confiance et moins de deux cents hommes, il s'empare du Kent, un grand navire de la Compagnie bien plus armé et peuplé. Fortune faite, il devient armateur à Saint-Malo, où il arme des navires corsaires puis de commerce. Il meurt en 1827 à Saint-Servan ; sa statue sur les remparts pointe le doigt vers l'Angleterre."],
 "Robert Surcouf",
 timeline=T(("1773","Naissance à Saint-Malo."),("1795","Premières courses dans l'océan Indien."),("1800","Prise du Kent."),("1827","Mort à Saint-Servan."))),
A("sport","Première Route du Rhum, 98 secondes et un disparu","Novembre 1978 · Bassin Vauban",
 "Pour la première Route du Rhum, en 1978, Mike Birch arrive en Guadeloupe 98 secondes avant Michel Malinovsky. Alain Colas et son trimaran Manureva disparaissent en mer.",
 "La Route du Rhum, course en solitaire de Saint-Malo à Pointe-à-Pitre, est partie pour la première fois le 5 novembre 1978 ; elle a lieu tous les quatre ans.",
 ["La course est imaginée pour relancer les échanges entre la Bretagne et les Antilles et promouvoir le rhum. Trente-huit marins prennent le départ en 1978, sur des bateaux de toutes tailles.",
  "Le Canadien Mike Birch, sur un petit trimaran jaune, Olympus Photo, double dans les derniers milles le grand monocoque de Michel Malinovsky et l'emporte avec 98 secondes d'avance. Alain Colas, vainqueur de la Transat anglaise en 1976, envoie son dernier message le 16 novembre au large des Açores ; ni lui ni son trimaran Manureva ne sont jamais retrouvés."],
 "Route du Rhum",
 more=["La disparition d'Alain Colas a inspiré la chanson « Manureva », écrite par Serge Gainsbourg pour Alain Chamfort en 1979."]),
A("nature","Les marées géantes et l'usine de la Rance","1966 · Barrage de la Rance",
 "La baie de Saint-Malo connaît des marnages de plus de douze mètres, parmi les plus forts d'Europe. Depuis 1966, l'usine marémotrice de la Rance en tire de l'électricité.",
 "L'usine marémotrice de la Rance, inaugurée le 26 novembre 1966 par le général de Gaulle entre Saint-Malo et Dinard, a été la première centrale au monde à produire de l'électricité avec la marée.",
 ["Dans la baie de Saint-Malo, l'écart entre la basse mer et la pleine mer dépasse douze mètres lors des grandes marées. À chaque marée montante et descendante, des millions de mètres cubes d'eau entrent et sortent de l'estuaire de la Rance.",
  "Le barrage de 750 mètres retient cette eau et la fait passer dans 24 turbines d'une puissance totale de 240 mégawatts. Pendant quarante-cinq ans, l'usine est restée la plus puissante centrale marémotrice du monde, jusqu'à la mise en service de celle de Sihwa, en Corée du Sud, en 2011. Une route passe sur l'ouvrage et relie Saint-Malo à Dinard."],
 "Usine marémotrice de la Rance"),
]

# ---------------------------------------------------------------- ANGOULEME
angouleme=[
A("politique","D'un maire en fuite à Xavier Bonnefont","1977-2026 · Hôtel de ville",
 "L'ancien maire Jean-Michel Boucheron s'est enfui en Argentine avant d'être extradé en 1997. Xavier Bonnefont, maire depuis 2014, a été réélu en mars 2026 face à La France insoumise.",
 "Xavier Bonnefont, divers droite, maire d'Angoulême depuis 2014, a été réélu au second tour des municipales de mars 2026 avec 48,26 % des voix.",
 ["Le socialiste Jean-Michel Boucheron dirige la ville de 1977 à 1989 et devient brièvement secrétaire d'État aux Collectivités territoriales en 1988. Il laisse une ville lourdement endettée. Visé par des enquêtes pour malversations financières, il part en 1992 pour l'Argentine. Condamné par défaut en juillet 1994 à quatre ans de prison ferme, il est extradé en mars 1997 et incarcéré à son arrivée en France.",
  "En 2018, le tribunal correctionnel d'Angoulême le condamne en première instance à dix-huit mois de prison avec sursis pour fraude fiscale. Son successeur, Georges Chavanes, maire de 1989 à 1997, a été ministre du Commerce et de l'Artisanat dans le gouvernement Balladur.",
  "En mars 2026, la liste de Xavier Bonnefont devance celles d'Anne-Aziliz Petit-Louboutin, La France insoumise (32,18 %), et de Patrick Mardikian, divers gauche (19,56 %). Elle obtient 32 des 43 sièges."],
 "Xavier Bonnefont"),
A("patrimoine","Le Festival de la BD, de 1974 à l'annulation","1974-2026 · Centre-ville",
 "Créé en 1974, le Festival de la bande dessinée attirait plus de 200 000 visiteurs chaque hiver. L'édition 2026 a été annulée après un boycott de plus de 2 000 auteurs.",
 "Le Festival international de la bande dessinée d'Angoulême, créé en 1974, est le principal rendez-vous européen de la BD ; son édition de janvier 2026 a été annulée, une première hors pandémie.",
 ["Le festival naît en janvier 1974 de l'initiative de Francis Groux, Jean Mardikian et Claude Moliterni. Il installe Angoulême comme capitale de la bande dessinée : Grand Prix décerné à un auteur pour l'ensemble de son œuvre, Fauves pour les albums, puis Cité internationale de la bande dessinée et de l'image et murs peints dans toute la ville.",
  "Depuis 2007, l'organisation est déléguée à une société privée, 9e Art+. En 2025, une enquête de L'Humanité Magazine relance des critiques anciennes sur sa gestion, dont le licenciement d'une salariée qui avait signalé un viol présumé et l'arrivée d'un sponsor de restauration rapide. Plus de 2 000 professionnels, dont Anouk Ricard, Grand Prix 2025, signent un appel au boycott, puis les grands éditeurs se retirent.",
  "Le 20 novembre 2025, les financeurs publics, qui apportent environ la moitié d'un budget de six millions d'euros, demandent l'annulation. La société organisatrice annonce le 1er décembre que l'édition prévue du 29 janvier au 1er février 2026 n'aura pas lieu, et la chambre de commerce évoque une perte d'activité de plusieurs millions d'euros pour la ville."],
 "Festival international de la bande dessinée d'Angoulême"),
A("personnalites","Marguerite de Navarre, née au château d'Angoulême","1492-1549 · Hôtel de ville",
 "Sœur aînée de François Ier, auteure de « L'Heptaméron », protectrice des humanistes, Marguerite de Navarre est née au château d'Angoulême le 11 avril 1492.",
 "Marguerite d'Angoulême, future reine de Navarre, est née le 11 avril 1492 dans le château des comtes d'Angoulême, dont une partie est intégrée à l'actuel hôtel de ville.",
 ["Fille de Charles d'Orléans, comte d'Angoulême, et de Louise de Savoie, elle grandit avec son frère François, qui devient roi en 1515. Très instruite, elle joue un rôle politique auprès de lui, négociant notamment sa libération après la défaite de Pavie.",
  "Reine de Navarre par son mariage avec Henri d'Albret en 1527, elle protège à sa cour les poètes et les humanistes favorables à une réforme de l'Église, comme Clément Marot. Elle écrit des poèmes religieux et « L'Heptaméron », recueil de nouvelles publié après sa mort, en 1549. Elle est la grand-mère d'Henri IV."],
 "Marguerite de Navarre",
 timeline=T(("1492","Naissance au château d'Angoulême."),("1515","Son frère devient roi sous le nom de François Ier."),("1527","Mariage avec Henri d'Albret, roi de Navarre."),("1549","Mort à Odos, en Bigorre."))),
A("patrimoine","La cathédrale Saint-Pierre, modèle du Sacré-Cœur","XIIe siècle · Place Saint-Pierre",
 "Sa façade romane compte des dizaines de personnages sculptés autour du Christ. Son restaurateur, Paul Abadie, s'est inspiré de ses coupoles pour dessiner le Sacré-Cœur de Montmartre.",
 "La cathédrale Saint-Pierre d'Angoulême, bâtie au XIIe siècle sous l'évêque Girard II, est l'un des principaux édifices romans à coupoles du sud-ouest de la France.",
 ["La nef est couverte d'une file de coupoles, un type d'architecture propre à l'Aquitaine romane. La façade occidentale déploie un vaste programme sculpté autour du Christ en gloire, entouré d'anges, d'apôtres et d'élus.",
  "À partir de 1849, l'architecte Paul Abadie mène une restauration radicale : il reconstruit des parties entières et refait le clocher selon sa vision de l'art roman. Ces travaux, critiqués depuis, lui servent de laboratoire pour le Sacré-Cœur de Montmartre, dont il remporte le concours en 1874."],
 "Cathédrale Saint-Pierre d'Angoulême",
 lat=45.6463,lon=0.1530,access="Entrée libre en dehors des offices",protection="Monument historique classé (1840)"),
]

# ---------------------------------------------------------------- NIORT
niort=[
A("politique","Jérôme Baloge, réélu au premier tour avec 65 %","2014-2026 · Hôtel de ville",
 "Élu en 2014 face à la maire socialiste sortante, Jérôme Baloge a été réélu dès le premier tour en mars 2026 avec 65,08 % des voix.",
 "Jérôme Baloge, divers centre, maire de Niort depuis 2014, a été réélu au premier tour des municipales de mars 2026 avec 65,08 % des voix.",
 ["Longtemps gouvernée à gauche, Niort bascule en 2014 lorsque Jérôme Baloge bat la maire socialiste sortante, Geneviève Gaillard. Il préside aussi la communauté d'agglomération du Niortais.",
  "En mars 2026, sa liste devance très largement celle d'union de la gauche conduite par Sébastien Mathieu (25,84 %) et celle du Rassemblement national menée par Céline Bonnet-Derisbourg (9,08 %). Elle obtient 38 sièges sur 45, avec une participation de 55,49 %."],
 "Jérôme Baloge"),
A("histoire","Niort, capitale des mutuelles depuis la MAIF","1934 · Niort",
 "En 1934, un instituteur des Deux-Sèvres, Edmond Proust, fonde à Niort une mutuelle d'assurance automobile pour ses collègues. La MAAF et la MACIF suivront.",
 "Niort abrite les sièges de plusieurs grandes mutuelles d'assurance, dont la MAIF, fondée sur place en 1934 par l'instituteur Edmond Proust.",
 ["Dans les années 1930, les instituteurs ruraux achètent leurs premières automobiles mais jugent les primes des assureurs trop élevées. Edmond Proust, militant laïque et mutualiste, crée avec des collègues une mutuelle sans intermédiaire ni actionnaire : la Mutuelle assurance automobile des instituteurs de France.",
  "Le modèle essaime à Niort : la MAAF, pour les artisans, est créée en 1950, puis la MACIF, pour les salariés de l'industrie et du commerce, en 1960. L'assurance mutualiste emploie désormais des milliers de personnes dans l'agglomération, ce qui vaut à Niort le surnom de capitale des mutuelles."],
 "Mutuelle assurance des instituteurs de France"),
A("patrimoine","Le donjon de Niort, forteresse des Plantagenêt","XIIe siècle · Bords de Sèvre",
 "Construit à la fin du XIIe siècle par Henri II Plantagenêt et son fils Richard Cœur de Lion, le double donjon de Niort domine la Sèvre niortaise. Il a servi de prison jusqu'au XIXe siècle.",
 "Le donjon de Niort, élevé à la fin du XIIe siècle par les rois d'Angleterre, ducs d'Aquitaine, est l'un des rares exemples de double donjon roman conservés en France.",
 ["Henri II Plantagenêt, époux d'Aliénor d'Aquitaine, puis son fils Richard Cœur de Lion font construire deux tours carrées reliées entre elles, au bord de la Sèvre, pour tenir le Poitou face au roi de France. Le reste du château, une vaste enceinte, a disparu.",
  "Pris par les Français au XIIIe siècle, le donjon sert ensuite de prison jusqu'au XIXe siècle. Restauré, il abrite aujourd'hui un musée consacré à l'histoire de la ville et du château."],
 "Donjon de Niort",
 access="Musée, horaires à consulter",protection="Monument historique classé (1840)"),
A("personnalites","Madame de Maintenon, née à Niort fille d'un prisonnier","1635-1719 · Niort",
 "Françoise d'Aubigné, future épouse secrète de Louis XIV, est née à Niort le 27 novembre 1635, alors que son père y était emprisonné.",
 "Françoise d'Aubigné, devenue marquise de Maintenon, est née à Niort le 27 novembre 1635, pendant la détention de son père, Constant d'Aubigné, dans la prison de la ville.",
 ["Constant d'Aubigné, fils dévoyé du poète protestant Agrippa d'Aubigné, est emprisonné à Niort pour dettes et intrigues. Sa fille naît près de la prison ; elle passe une enfance pauvre entre le Poitou et les Antilles.",
  "Veuve du poète Paul Scarron, elle devient la gouvernante des enfants que Louis XIV a eus avec Madame de Montespan. Le roi la fait marquise de Maintenon et l'épouse secrètement vers 1683, après la mort de la reine. Elle fonde en 1686 la maison royale de Saint-Cyr pour l'éducation des jeunes filles nobles pauvres et y meurt en 1719."],
 "Françoise d'Aubigné",
 timeline=T(("1635","Naissance à Niort, son père en prison."),("1652","Mariage avec Paul Scarron."),("1675","Faite marquise de Maintenon."),("1683","Mariage secret avec Louis XIV."),("1719","Mort à Saint-Cyr."))),
A("nature","Le Marais poitevin, Venise verte aux portes de Niort","Marais mouillé · Sèvre niortaise",
 "À l'ouest de Niort commence le Marais poitevin, deuxième zone humide de France après la Camargue. Dans sa partie boisée, la Venise verte, on circule en barque entre les frênes têtards.",
 "Le Marais poitevin, qui s'étend de Niort à la baie de l'Aiguillon, est une zone humide d'environ 100 000 hectares, aménagée par l'homme depuis le Moyen Âge.",
 ["Ce golfe marin comblé par les alluvions a été asséché à partir du XIe siècle par les moines des abbayes voisines, puis par des ingénieurs hollandais au XVIIe siècle. Le marais desséché, côté mer, est voué aux cultures ; le marais mouillé, en amont, inondable l'hiver, garde ses prairies et ses canaux bordés de frênes taillés en têtard.",
  "Cette partie boisée, surnommée la Venise verte, se parcourt en barque à fond plat depuis Coulon ou Arçais. Le parc naturel régional, qui avait perdu son label dans les années 1990 à cause du drainage agricole et du recul des prairies, l'a retrouvé en 2014."],
 "Marais poitevin"),
]

cities=[("17300","La Rochelle","Charente-Maritime",46.1591,-1.1520,larochelle),
        ("44184","Saint-Nazaire","Loire-Atlantique",47.2735,-2.2138,saintnazaire),
        ("56121","Lorient","Morbihan",47.7483,-3.3700,lorient),
        ("29232","Quimper","Finistère",47.9960,-4.1024,quimper),
        ("56260","Vannes","Morbihan",47.6582,-2.7608,vannes),
        ("35288","Saint-Malo","Ille-et-Vilaine",48.6493,-2.0257,saintmalo),
        ("16015","Angoulême","Charente",45.6484,0.1562,angouleme),
        ("79191","Niort","Deux-Sèvres",46.3237,-0.4588,niort)]
idx=json.load(open('index.json'))
for insee,name,dept,lat,lon,arts in cities:
    path=f"communes/{insee}.json"
    if os.path.exists(path):
        p=json.load(open(path)); have={a.get("wiki") for a in p["anecdotes"]}
        p["anecdotes"]+=[a for a in arts if a.get("wiki") not in have]
    else:
        p={"id":insee,"insee":insee,"name":name,"dept":dept,"kind":"commune","lat":lat,"lon":lon,"anecdotes":arts}
    json.dump(p,open(path,'w'),ensure_ascii=False,indent=1)
    idx["communes"][insee]={"name":name,"count":len(p["anecdotes"]),"updated":"2026-10-07"}
    print(name,len(p["anecdotes"]))
json.dump(idx,open('index.json','w'),ensure_ascii=False,indent=1)
print(sum(v["count"] for v in idx["communes"].values()),"articles",len(idx["communes"]),"communes")
