import json, os
from urllib.parse import quote
W="https://fr.wikipedia.org/wiki/"
def wk(t): return quote(t.replace(" ","_"),safe="_(),-.")
def A(cat,title,label,teaser,lead,body,wiki,more=None,timeline=None,lat=None,lon=None,links=None,access=None,protection=None,status=None):
    w=wk(wiki)
    a={"category":cat,"title":title,"label":label}
    if status: a["status"]=status
    a.update({"teaser":teaser,"lead":lead,"text":lead,"body":body,"more":more or [],"timeline":timeline,"links":links,"wiki":w,"source":W+w,"lat":lat,"lon":lon,"access":access,"protection":protection})
    return a
def L(kind,title,url,note): return {"kind":kind,"title":title,"url":url,"note":note}
def T(*p): return [{"year":y,"text":t} for y,t in p]

# ---------------------------------------------------------------- PAU
pau=[
A("politique","François Bayrou perd Pau pour 344 voix","2014-2026 · Hôtel de ville",
 "Six mois après sa chute à Matignon, l'ancien Premier ministre est battu dans sa ville par le socialiste Jérôme Marbot, 42,45 % contre 41,14 %. Il est rejugé en appel dans l'affaire du MoDem.",
 "Jérôme Marbot, à la tête d'une liste d'union de la gauche, est maire de Pau depuis mars 2026 : il a battu au second tour le maire sortant François Bayrou, avec 344 voix d'avance.",
 ["Pau a longtemps été le fief du socialiste André Labarrère, maire de 1971 à sa mort en 2006 et ministre chargé des Relations avec le Parlement de 1981 à 1986. François Bayrou, élu député des Pyrénées-Atlantiques pour la première fois en 1986, trois fois candidat à l'élection présidentielle, prend la mairie en 2014.",
  "Nommé Premier ministre en décembre 2024, il conserve la ville et quitte Matignon le 8 septembre 2025, après le refus de confiance de l'Assemblée nationale. Aux municipales de mars 2026, il arrive en tête du premier tour avec 33,83 %, mais la gauche rassemblée derrière Jérôme Marbot l'emporte au second avec 11 174 voix contre 10 830 ; la liste du Rassemblement national de Margaux Taillefer obtient 16,41 %.",
  "Depuis 2017, Bayrou est visé par l'affaire des assistants d'eurodéputés de l'UDF et du MoDem, qui l'avait contraint à quitter le ministère de la Justice un mois après sa nomination. Relaxé au bénéfice du doute en première instance le 5 février 2024, il est rejugé en appel depuis le 9 septembre 2026 ; le parquet a requis deux ans de prison avec sursis et trois ans d'inéligibilité avec sursis."],
 "François Bayrou",
 status="Relaxé en première instance le 5 février 2024 ; procès en appel tenu en septembre-octobre 2026, décision attendue le 17 décembre 2026. Présumé innocent.",
 links=[L("article","Procès en appel de l'affaire du MoDem (Le Club des juristes)","https://www.leclubdesjuristes.com/?p=17620","Les réquisitions et la date de la décision")]),
A("personnalites","Henri IV, né au château de Pau","1553 · Château de Pau",
 "Le futur Henri IV naît le 13 décembre 1553 au château de Pau. Selon la tradition, son grand-père lui frotte les lèvres d'ail et de vin de Jurançon. Le château conserve son berceau, une carapace de tortue.",
 "Henri de Bourbon, futur roi de Navarre puis roi de France sous le nom d'Henri IV, est né le 13 décembre 1553 au château de Pau, résidence des rois de Navarre.",
 ["Sa mère, Jeanne d'Albret, accouche dans le château de son père, Henri II d'Albret. La tradition veut qu'elle ait chanté un cantique béarnais pendant l'accouchement pour avoir un fils qui ne soit « ni pleureur ni rechigné », et que le grand-père ait frotté les lèvres du nouveau-né avec une gousse d'ail et quelques gouttes de vin de Jurançon.",
  "Élevé dans le protestantisme, roi de Navarre en 1572, il hérite de la couronne de France en 1589 et se convertit au catholicisme en 1593 pour entrer dans Paris. Il signe en 1598 l'édit de Nantes, qui met fin aux guerres de Religion, avant d'être assassiné par Ravaillac le 14 mai 1610.",
  "Le château de Pau, devenu musée national, expose une carapace de tortue de mer présentée comme son berceau. Une statue du roi se dresse place Royale, face aux Pyrénées."],
 "Henri IV (roi de France)",
 timeline=T(("1553","Naissance au château de Pau."),("1572","Roi de Navarre ; il réchappe de la Saint-Barthélemy."),("1589","Roi de France."),("1598","Édit de Nantes."),("1610","Assassiné à Paris par Ravaillac.")),
 lat=43.2949,lon=-0.3757,access="Musée national du château de Pau, visites guidées",protection="Monument historique classé"),
A("personnalites","Bernadotte, le Palois devenu roi de Suède","1763-1844 · Maison natale",
 "Fils d'un procureur de Pau, Jean-Baptiste Bernadotte devient maréchal de Napoléon, puis roi de Suède en 1818. Ses descendants règnent toujours à Stockholm.",
 "Jean-Baptiste Bernadotte, né à Pau le 26 janvier 1763, simple soldat devenu maréchal d'Empire, a été élu prince héritier de Suède en 1810 et a régné à partir de 1818 sous le nom de Charles XIV Jean.",
 ["Engagé à dix-sept ans dans l'infanterie de marine, il gravit les grades pendant la Révolution et devient général en 1794. Napoléon le fait maréchal en 1804, malgré une rivalité ancienne entre les deux hommes.",
  "En 1810, la Suède, dont le roi n'a pas d'héritier, choisit ce maréchal français réputé pour sa modération envers les prisonniers suédois. Devenu prince héritier, il se retourne contre Napoléon et combat dans la coalition victorieuse à Leipzig en 1813. Roi de Suède et de Norvège en 1818, il fonde la dynastie Bernadotte, dont est issu l'actuel roi Charles XVI Gustave.",
  "Sa maison natale, dans le centre de Pau, est aujourd'hui un musée."],
 "Charles XIV Jean",
 timeline=T(("1763","Naissance à Pau."),("1804","Maréchal d'Empire."),("1810","Élu prince héritier de Suède."),("1818","Roi de Suède et de Norvège."),("1844","Mort à Stockholm.")),
 access="Musée Bernadotte, horaires à consulter"),
A("insolite","Wilbur Wright ouvre à Pau une école de pilotage","Janvier-mars 1909 · Lande du Pont-Long",
 "En 1909, l'Américain Wilbur Wright choisit Pau pour former les premiers pilotes français. Le roi d'Espagne Alphonse XIII vient le voir voler.",
 "De janvier à mars 1909, Wilbur Wright installe à Pau, sur la lande du Pont-Long, l'une des premières écoles de pilotage au monde.",
 ["Après ses démonstrations de 1908 au Mans, Wilbur Wright cherche un terrain pour l'hiver. La municipalité de Pau, station de villégiature fréquentée par les Britanniques et les Américains, lui offre un hangar et un terrain plat, abrité du vent par les Pyrénées.",
  "Il y forme plusieurs pilotes français, dont le comte Charles de Lambert et Paul Tissandier, qui figurent parmi les premiers pilotes brevetés en France. Les vols attirent des visiteurs prestigieux, dont le roi Alphonse XIII. Pau devient ensuite un centre de l'aviation militaire : l'école des troupes aéroportées y est aujourd'hui installée."],
 "Wilbur Wright"),
]

# ---------------------------------------------------------------- BAYONNE
bayonne=[
A("politique","Jean-René Etchegaray réélu au second tour à Bayonne","2014-2026 · Hôtel de ville",
 "Maire depuis 2014 et président de l'agglomération Pays basque, le centriste Jean-René Etchegaray a été réélu en mars 2026 avec 50,70 % des voix au second tour.",
 "Jean-René Etchegaray, divers centre, maire de Bayonne depuis 2014, a été réélu au second tour des municipales de mars 2026 avec 50,70 % des voix.",
 ["De 1959 à 2014, Bayonne a été dirigée par deux hommes de la même famille : Henri Grenet jusqu'en 1995, puis son fils Jean Grenet. Jean-René Etchegaray, avocat centriste, leur succède en 2014 et préside depuis 2017 la communauté d'agglomération Pays basque, qui regroupe 158 communes.",
  "En mars 2026, il obtient 42,1 % au premier tour, puis 50,70 % au second, face à la liste d'union de la gauche conduite par Jean-Claude Iriart (41,01 %) et à celle de Pascal Lesellier, classée à l'extrême droite (8,29 %). Sa liste détient 35 des 45 sièges du conseil municipal."],
 "Jean-René Etchegaray"),
A("faits_divers","La mort du chauffeur de bus Philippe Monguillot","5 juillet 2020 · Bayonne",
 "Le 5 juillet 2020, un chauffeur de bus de 59 ans est roué de coups après une altercation avec des passagers. Sa mort, cinq jours plus tard, provoque une émotion nationale.",
 "Le 5 juillet 2020 à Bayonne, Philippe Monguillot, chauffeur de bus de 59 ans, est frappé à la tête par deux jeunes hommes après une altercation à bord ; il meurt le 10 juillet à l'hôpital.",
 ["L'altercation éclate en soirée lorsque le chauffeur demande à des passagers de présenter un titre de transport et de porter le masque, alors obligatoire dans les transports en raison de l'épidémie de Covid-19. Philippe Monguillot est ensuite frappé à l'extérieur du bus et laissé en état de mort cérébrale. Sa famille décide d'arrêter les soins le 10 juillet.",
  "Les chauffeurs exercent leur droit de retrait, une marche blanche réunit des milliers de personnes et le ministre de l'Intérieur se rend à Bayonne. Les deux principaux auteurs, âgés de 22 et 23 ans au moment des faits, sont jugés en septembre 2023 par la cour d'assises des Pyrénées-Atlantiques, à Pau. Ils sont condamnés à quinze et treize ans de réclusion criminelle.",
  "La veuve du chauffeur, Véronique Monguillot, a dénoncé un verdict trop clément. Le procès d'un troisième homme, poursuivi pour avoir hébergé les auteurs après les faits, a été reporté en 2025."],
 "Mort de Philippe Monguillot",
 status="Les deux auteurs ont été condamnés en septembre 2023 à 15 et 13 ans de réclusion criminelle ; aucun appel n'a été signalé dans les sources consultées."),
A("patrimoine","Les fêtes de Bayonne, en blanc et rouge","Depuis 1932 · Petit et Grand Bayonne",
 "Créées en 1932 sur le modèle des Sanfermines de Pampelune, les fêtes de Bayonne réunissent chaque été, pendant cinq jours, des foules vêtues de blanc et rouge.",
 "Les fêtes de Bayonne, créées en 1932, se tiennent chaque année cinq jours à partir du mercredi précédant le premier dimanche d'août.",
 ["Des Bayonnais revenus des fêtes de San Fermín, à Pampelune, proposent en 1932 d'organiser des réjouissances semblables. Les fêtes reprennent les codes navarrais : tenue blanche, foulard et ceinture rouges, bandas, courses de vaches et corridas.",
  "Elles s'ouvrent par la remise des clés de la ville au roi Léon, un géant de carton, qui apparaît au balcon de l'hôtel de ville. L'affluence se compte chaque année en centaines de milliers de visiteurs."],
 "Fêtes de Bayonne"),
A("gastronomie","Jambon et chocolat, les deux spécialités de Bayonne","XVIIe siècle · Bords de l'Adour",
 "Le jambon de Bayonne, salé au sel des salines de l'Adour, bénéficie d'une IGP depuis 1998. Le chocolat est arrivé au XVIIe siècle avec les juifs chassés d'Espagne et du Portugal.",
 "Bayonne doit sa réputation gastronomique à deux produits : le jambon, séché dans le bassin de l'Adour, et le chocolat, introduit au XVIIe siècle par des familles juives venues de la péninsule Ibérique.",
 ["Le jambon, longtemps expédié par le port de Bayonne, est frotté au sel de Salies-de-Béarn puis séché plusieurs mois. Il est protégé depuis 1998 par une indication géographique protégée, qui en fixe la zone de production dans le Sud-Ouest.",
  "Les familles juives réfugiées d'Espagne et du Portugal, installées dans le quartier Saint-Esprit, apportent le savoir-faire du cacao venu des Amériques. Les chocolatiers bayonnais se multiplient au XVIIIe siècle, et la ville, souvent présentée comme la première capitale française du chocolat, compte encore plusieurs maisons historiques autour de la rue du Port-Neuf."],
 "Jambon de Bayonne"),
]

# ---------------------------------------------------------------- BIARRITZ
biarritz=[
A("politique","Serge Blanco, l'arrière du XV devenu maire","Mars 2026 · Hôtel de ville",
 "Pour sa première campagne, l'ancien arrière du XV de France, 93 sélections, a battu la maire sortante Maider Arosteguy avec 41,92 % des voix au second tour.",
 "Serge Blanco, divers centre, est maire de Biarritz depuis mars 2026, élu au second tour d'une triangulaire avec 41,92 % des voix.",
 ["Né à Caracas en 1958, arrivé à Biarritz à deux ans après la mort de son père, Serge Blanco a joué toute sa carrière au Biarritz olympique et compte 93 sélections en équipe de France. Il a présidé la Ligue nationale de rugby de 1998 à 2008 et le Biarritz olympique à deux reprises. Sa holding hôtelière a été placée en liquidation judiciaire en janvier 2020.",
  "Candidat à la mairie en décembre 2025, il devance la maire sortante Maider Arosteguy, Les Républicains, de douze voix au premier tour, puis l'emporte au second avec 41,92 %, contre 32,21 % à la maire sortante et 25,87 % à la liste de gauche d'Ana Ezcurra. Il obtient 25 des 35 sièges.",
  "Avant lui, Biarritz a été dirigée par Didier Borotra, centriste, de 1991 à 2014, puis par Michel Veunac jusqu'en 2020."],
 "Serge Blanco"),
A("patrimoine","La villa d'Eugénie devenue l'Hôtel du Palais","1854 · Grande Plage",
 "En 1854, Napoléon III fait construire face à la Grande Plage une résidence d'été pour l'impératrice Eugénie. La villa, devenue un palace en 1893, a fait de Biarritz une station royale.",
 "L'Hôtel du Palais, à Biarritz, est l'ancienne villa Eugénie, construite en 1854-1855 pour l'impératrice Eugénie, épouse de Napoléon III, qui venait en villégiature sur la côte basque depuis l'enfance.",
 ["Eugénie de Montijo, née à Grenade, connaît Biarritz depuis ses séjours de jeune fille. Devenue impératrice, elle convainc Napoléon III d'y faire bâtir une résidence en forme de E, face à l'océan. La cour y séjourne chaque été et le petit port de pêche devient en quelques années une station fréquentée par les têtes couronnées d'Europe.",
  "Après la chute de l'Empire, la villa est vendue et transformée en hôtel en 1893. Ravagée par un incendie en 1903, elle est reconstruite dans un style proche de l'original. La ville de Biarritz en devient propriétaire au milieu du XXe siècle. C'est là que sont reçus les chefs d'État du G7 en août 2019."],
 "Hôtel du Palais",
 lat=43.4853,lon=-1.5577),
A("histoire","Le sommet du G7 sous haute sécurité","24-26 août 2019 · Hôtel du Palais",
 "Du 24 au 26 août 2019, Biarritz accueille les dirigeants du G7 sous la protection de plus de 13 000 policiers et gendarmes. Le ministre iranien des Affaires étrangères y fait une apparition surprise.",
 "Le 45e sommet du G7 s'est tenu à Biarritz du 24 au 26 août 2019, sous la présidence d'Emmanuel Macron, dans une ville placée sous un dispositif de sécurité exceptionnel.",
 ["Les chefs d'État et de gouvernement des États-Unis, du Canada, du Japon, du Royaume-Uni, de l'Allemagne, de l'Italie et de la France se réunissent à l'Hôtel du Palais. Une partie de la ville est fermée, les plages et les commerces du centre sont inaccessibles, et un contre-sommet se tient à Hendaye et Irun, de l'autre côté de la frontière.",
  "Le 25 août, Emmanuel Macron fait venir à Biarritz le ministre iranien des Affaires étrangères, Mohammad Javad Zarif, pour tenter une médiation sur le nucléaire iranien, sans résultat durable. Le sommet est aussi marqué par les incendies de l'Amazonie, pour lesquels les participants annoncent une aide d'urgence."],
 "Sommet du G7 2019"),
A("sport","1957, la première planche de surf à Biarritz","1957 · Côte des Basques",
 "En 1957, le scénariste américain Peter Viertel fait venir une planche de Californie et surfe sur la Côte des Basques. Biarritz devient le berceau du surf en Europe.",
 "Le surf est arrivé en France en 1957 à Biarritz, avec le scénariste américain Peter Viertel, venu en Espagne pour le tournage du film « Le soleil se lève aussi ».",
 ["Peter Viertel, qui adapte pour Henry King le roman d'Ernest Hemingway, séjourne à Biarritz pendant le tournage. Frappé par la qualité des vagues de la Côte des Basques, il se fait envoyer une planche de Californie et surfe devant des Biarrots intrigués.",
  "Quelques jeunes de la ville, dont le scientifique Joël de Rosnay, l'imitent et fabriquent leurs propres planches. Les premiers clubs naissent à la fin des années 1950, et Biarritz accueille les premières compétitions internationales en Europe. La côte basque est devenue depuis un centre de l'industrie et des compétitions de surf."],
 "Côte des Basques",
 links=[L("film","« Le soleil se lève aussi » (1957), de Henry King","https://fr.wikipedia.org/wiki/Le_soleil_se_l%C3%A8ve_aussi_(film)","Le tournage qui a amené Peter Viertel sur la côte basque")]),
]

# ---------------------------------------------------------------- TARBES
tarbes=[
A("politique","Pascal Claverie devance le Rassemblement national à Tarbes","2001-2026 · Hôtel de ville",
 "Distancé au premier tour, le centriste Pascal Claverie a remporté la mairie en mars 2026 avec 38,85 % des voix, devant le candidat du Rassemblement national, arrivé en tête au premier tour.",
 "Pascal Claverie, divers centre, est maire de Tarbes depuis mars 2026, élu au second tour avec 38,85 % des voix dans une triangulaire.",
 ["Gérard Trémège, divers droite, dirigeait la ville depuis 2001. En mars 2026, la liste du Rassemblement national conduite par Éric Peyrègne arrive en tête du premier tour avec 23,8 %, devant Michel Garnier, divers droite (19,6 %), et Pascal Claverie (17,5 %).",
  "Au second tour, Pascal Claverie l'emporte avec 5 142 voix, contre 4 726 au Rassemblement national (35,71 %) et 3 368 à Michel Garnier (25,45 %). Sa liste obtient 30 des 43 sièges du conseil municipal."],
 "Gérard Trémège"),
A("personnalites","Ferdinand Foch, le maréchal né à Tarbes","1851-1929 · Maison natale",
 "Né à Tarbes le 2 octobre 1851, Ferdinand Foch commande les armées alliées en 1918 et reçoit la capitulation allemande à Rethondes. Sa maison natale est un musée.",
 "Ferdinand Foch, né à Tarbes le 2 octobre 1851, a été le commandant en chef des armées alliées sur le front de l'Ouest en 1918.",
 ["Fils d'un fonctionnaire, il entre à Polytechnique et fait carrière dans l'artillerie, puis enseigne à l'École de guerre, où il théorise l'offensive. En 1914, il commande la 9e armée pendant la bataille de la Marne.",
  "En mars 1918, face à l'offensive allemande, les Alliés lui confient la coordination de toutes leurs armées. Il conduit les contre-offensives de l'été et de l'automne, et c'est dans son wagon, en forêt de Compiègne, que l'armistice est signé le 11 novembre 1918. Maréchal de France, il meurt en 1929 et repose aux Invalides.",
  "Sa maison natale, rue de la Victoire, est devenue un musée."],
 "Ferdinand Foch",
 timeline=T(("1851","Naissance à Tarbes."),("1914","Commandant de la 9e armée sur la Marne."),("1918","Commandant en chef des armées alliées, maréchal de France."),("1929","Mort à Paris, inhumé aux Invalides.")),
 access="Musée de la maison natale, horaires à consulter"),
A("personnalites","Théophile Gautier et son gilet rouge","1811-1872 · Tarbes",
 "Né à Tarbes en 1811, Théophile Gautier fait scandale en 1830 avec son gilet rouge à la première d'« Hernani ». Il écrira « Le Capitaine Fracasse » et « Émaux et Camées ».",
 "Théophile Gautier, poète et romancier, est né à Tarbes le 30 août 1811, avant de partir pour Paris avec sa famille à l'âge de trois ans.",
 ["Il se fait connaître le 25 février 1830 à la première d'« Hernani » de Victor Hugo, où il mène la jeunesse romantique dans un gilet rouge resté célèbre. Il publie ensuite « Mademoiselle de Maupin », dont la préface défend l'art pour l'art.",
  "Critique, voyageur, il publie en 1852 le recueil « Émaux et Camées » et en 1863 « Le Capitaine Fracasse ». Baudelaire lui dédie « Les Fleurs du mal ». Il meurt en 1872 ; le lycée de Tarbes porte son nom."],
 "Théophile Gautier"),
A("patrimoine","Le haras de Tarbes, créé par Napoléon","1806 · Haras national",
 "Fondé en 1806 sur ordre de Napoléon, le haras de Tarbes a fourni des chevaux à la cavalerie et a donné naissance à l'anglo-arabe, une race née du croisement entre arabe et pur-sang anglais.",
 "Le haras national de Tarbes a été créé en 1806 par un décret de Napoléon pour élever des chevaux destinés à la cavalerie légère.",
 ["Les Pyrénées sont alors réputées pour leurs chevaux nerveux et endurants, appréciés par les hussards. Le haras y développe le cheval tarbais, puis, au XIXe siècle, l'anglo-arabe, issu de croisements entre étalons arabes et juments de pur-sang anglais, devenu une race de selle de référence.",
  "Le parc de huit hectares, en plein centre-ville, accueille toujours des étalons et se visite. Les écuries du XIXe siècle et la sellerie ont été conservées."],
 "Haras national de Tarbes",
 access="Parc ouvert au public, visites guidées des écuries"),
]

# ---------------------------------------------------------------- AGEN
agen=[
A("politique","Laurent Bruneau met fin à l'ère Dionis","2008-2026 · Hôtel de ville",
 "L'avocat Laurent Bruneau, à la tête d'une liste d'union de la gauche, a battu en mars 2026 le maire centriste Jean Dionis du Séjour, en place depuis 2008, avec 39,05 % des voix.",
 "Laurent Bruneau, union de la gauche, est maire d'Agen depuis mars 2026, élu au second tour d'une triangulaire avec 39,05 % des voix.",
 ["Jean Dionis du Séjour, député centriste de 2002 à 2012 puis rallié au MoDem, dirigeait Agen depuis 2008 et avait été réélu dès le premier tour en 2020 avec 61,41 %.",
  "En mars 2026, la liste d'union de la gauche de Laurent Bruneau arrive en tête du premier tour avec 34,5 %, devant le maire sortant (32,3 %) et la liste d'union de l'extrême droite de Sébastien Delbosq (30,6 %). Au second tour, Laurent Bruneau obtient 39,05 %, contre 34,33 % à Jean Dionis et 26,62 % au Rassemblement national. Sa liste détient 27 des 39 sièges."],
 "Jean Dionis du Séjour"),
A("gastronomie","Le pruneau d'Agen, expédié par la Garonne","Moyen Âge-2002 · Port d'Agen",
 "Le pruneau d'Agen n'est pas produit à Agen même : il porte le nom du port d'où il était expédié par la Garonne vers Bordeaux, puis le monde. Il bénéficie d'une IGP depuis 2002.",
 "Le pruneau d'Agen est une prune d'ente séchée, cultivée surtout dans la vallée du Lot ; il doit son nom au port d'Agen, d'où il était chargé sur les bateaux de la Garonne.",
 ["Selon la tradition, des moines de l'abbaye de Clairac auraient greffé au Moyen Âge des pruniers locaux avec une variété rapportée de Damas, donnant la prune d'ente, du vieux mot « enter », greffer. Séchée au four, elle se conserve longtemps, ce qui en fait une provision de marine.",
  "Les pruneaux de la région descendent la Garonne depuis Agen jusqu'à Bordeaux, d'où ils sont exportés : le nom de la ville s'impose sur les marchés. L'indication géographique protégée, obtenue en 2002, couvre une zone de production centrée sur le Lot-et-Garonne. Chaque année, Agen organise le Grand Pruneau Show."],
 "Pruneau d'Agen"),
A("patrimoine","Le pont-canal d'Agen, un canal au-dessus de la Garonne","XIXe siècle · Canal de Garonne",
 "Avec ses vingt-trois arches de pierre et plus de 500 mètres de long, le pont-canal d'Agen fait passer les péniches du canal de Garonne au-dessus du fleuve.",
 "Le pont-canal d'Agen, achevé au milieu du XIXe siècle, porte le canal latéral à la Garonne au-dessus du fleuve sur 539 mètres et vingt-trois arches.",
 ["Le canal latéral à la Garonne prolonge le canal du Midi de Toulouse jusqu'à Castets-en-Dorthe, pour éviter aux bateaux les crues et les basses eaux du fleuve. À Agen, il doit franchir la Garonne : les ingénieurs construisent un pont de pierre qui porte un bac en eau.",
  "C'est l'un des plus longs ponts-canaux de France. Les piétons et les cyclistes l'empruntent par le chemin de halage, qui fait partie de la véloroute du canal des Deux-Mers."],
 "Pont-canal d'Agen",
 access="Chemin de halage en accès libre"),
A("sport","Le SU Agen, huit titres de champion de France","1930-1988 · Stade Armandie",
 "Le Sporting union Agen a été huit fois champion de France de rugby, de 1930 à 1988. Son dirigeant Albert Ferrasse a présidé la Fédération française de rugby pendant vingt-trois ans.",
 "Le Sporting union Agen, club de rugby fondé en 1908, a remporté huit titres de champion de France entre 1930 et 1988, au stade Armandie.",
 ["Agen gagne son premier titre en 1930, puis en 1945, 1962, 1965, 1966, 1976, 1982 et 1988. Le club fournit de nombreux internationaux, dont l'ailier Philippe Sella, recordman des sélections en équipe de France à la fin de sa carrière.",
  "Son ancien joueur et dirigeant Albert Ferrasse préside la Fédération française de rugby de 1968 à 1991 et fait d'Agen une capitale administrative du rugby français. Le club alterne depuis les années 2000 entre le Top 14 et la Pro D2."],
 "Sporting union Agen Lot-et-Garonne"),
]

# ---------------------------------------------------------------- MONTAUBAN
montauban=[
A("politique","Montauban, de Brigitte Barèges à Didier Lallemand","2001-2026 · Hôtel de ville",
 "Maire pendant plus de vingt ans, Brigitte Barèges a été relaxée en appel en 2021, puis déclarée inéligible en 2025. Son candidat, Didier Lallemand, soutenu par le RN et l'UDR, a pris la ville en 2026.",
 "Didier Lallemand, à la tête d'une liste d'union de l'extrême droite soutenue par le Rassemblement national et l'UDR, est maire de Montauban depuis mars 2026, élu avec 37,83 % des voix.",
 ["Brigitte Barèges dirige Montauban à partir de 2001. Condamnée le 9 février 2021 par le tribunal correctionnel de Toulouse à cinq ans d'inéligibilité avec exécution immédiate pour détournement de fonds publics, dans une affaire d'emploi présumé fictif lié à sa communication, elle perd ses mandats. La cour d'appel de Toulouse la relaxe le 14 décembre 2021 et le parquet ne se pourvoit pas en cassation : elle retrouve la mairie.",
  "Élue députée en 2024 sous l'étiquette de l'UDR d'Éric Ciotti, elle cède la mairie à Marie-Claude Berly. Le 11 juillet 2025, le Conseil constitutionnel la déclare inéligible pour un an pour des irrégularités dans le financement de sa campagne législative, ce qui lui fait perdre son siège de députée.",
  "Directrice de campagne de Didier Lallemand en 2026, elle voit son candidat l'emporter au second tour avec 37,83 %, devant Arnaud Hilion, union de la gauche (34,41 %), et Thierry Deville, divers droite, son ancien premier adjoint (27,76 %). La liste de Didier Lallemand obtient 34 des 49 sièges."],
 "Brigitte Barèges",
 status="Brigitte Barèges : relaxe définitive le 14 décembre 2021 (pas de pourvoi) ; inéligibilité d'un an prononcée par le Conseil constitutionnel le 11 juillet 2025, arrivée à échéance en juillet 2026."),
A("faits_divers","15 mars 2012, deux parachutistes tués par Mohamed Merah","15 mars 2012 · Caserne du 17e RGP",
 "Quatre jours après un premier meurtre à Toulouse, Mohamed Merah tue à Montauban deux parachutistes du 17e régiment du génie et en blesse grièvement un troisième, devant un distributeur de billets.",
 "Le 15 mars 2012 à Montauban, Mohamed Merah abat Abel Chennouf, 25 ans, et Mohamed Legouad, 23 ans, parachutistes du 17e régiment du génie parachutiste, et blesse grièvement leur camarade Loïc Liber.",
 ["Le 11 mars, Merah a tué à Toulouse le militaire Imad Ibn Ziaten. Quatre jours plus tard, il circule en scooter près de la caserne du 17e RGP, à Montauban, et ouvre le feu sur trois soldats en uniforme qui retirent de l'argent. Loïc Liber survit, tétraplégique.",
  "Le 19 mars, Merah tue trois enfants et un enseignant devant l'école juive Ozar Hatorah de Toulouse. Localisé grâce à l'adresse IP utilisée pour contacter une victime, il est tué par le RAID le 22 mars, après plus de trente heures de siège à son domicile. Ce sont les premiers attentats djihadistes meurtriers en France depuis la vague d'attentats de 1995-1996.",
  "Son frère Abdelkader Merah est condamné en appel le 18 avril 2019 à trente ans de réclusion criminelle pour complicité des sept assassinats ; la Cour de cassation rejette son pourvoi le 22 avril 2020, rendant la peine définitive."],
 "Affaire Mohammed Merah",
 status="Mohamed Merah, mort en 2012, n'a pas été jugé ; Abdelkader Merah a été définitivement condamné à 30 ans de réclusion (pourvoi rejeté le 22 avril 2020).",
 links=[L("article","Abdelkader Merah définitivement condamné (Europe 1)","https://www.europe1.fr/node/159362","Le rejet du pourvoi en cassation")]),
A("histoire","1621, Montauban résiste à Louis XIII","Août-novembre 1621 · Remparts",
 "En 1621, la place forte protestante tient trois mois face à l'armée royale de Louis XIII, qui lève le siège. Elle ne se soumet qu'en 1629, après la chute de La Rochelle.",
 "D'août à novembre 1621, l'armée de Louis XIII assiège Montauban, l'une des principales places fortes protestantes du royaume, sans parvenir à la prendre.",
 ["Fondée en 1144, Montauban adopte massivement la Réforme au XVIe siècle et devient une place de sûreté protestante. En 1621, quand les protestants se soulèvent, le roi et son favori, le connétable de Luynes, mettent le siège devant la ville avec une armée nombreuse.",
  "Défendue par ses habitants et par le duc de Rohan qui y fait entrer des renforts, la ville repousse les assauts. Décimée par les maladies et le mauvais temps, l'armée royale lève le siège en novembre ; Luynes meurt quelques semaines plus tard. Après la reddition de La Rochelle, Montauban se soumet en 1629 : Richelieu y entre et fait raser ses fortifications."],
 "Siège de Montauban (1621)"),
A("personnalites","Ingres, le peintre au violon de Montauban","1780-1867 · Musée Ingres-Bourdelle",
 "Né à Montauban en 1780, Jean-Auguste-Dominique Ingres a légué à sa ville des milliers de dessins. Sa passion pour le violon a donné l'expression « violon d'Ingres ».",
 "Jean-Auguste-Dominique Ingres, né à Montauban le 29 août 1780, est l'un des grands peintres français du XIXe siècle ; le musée de sa ville natale conserve l'essentiel de ses dessins.",
 ["Fils d'un peintre et musicien, il joue du violon dès l'enfance et tient le second violon à l'orchestre du Capitole de Toulouse avant de partir pour Paris, dans l'atelier de David. Prix de Rome en 1801, il passe de longues années en Italie et peint « La Grande Odalisque » ou « Le Bain turc ».",
  "Son attachement au violon, qu'il pratique toute sa vie, a donné l'expression « violon d'Ingres », désignant une passion en dehors du métier. À sa mort en 1867, il lègue à Montauban plus de 4 000 dessins, des tableaux et son violon, exposés au musée Ingres-Bourdelle, dans l'ancien palais épiscopal, qui associe le peintre au sculpteur Antoine Bourdelle, autre enfant de la ville."],
 "Jean-Auguste-Dominique Ingres",
 timeline=T(("1780","Naissance à Montauban."),("1801","Prix de Rome."),("1814","« La Grande Odalisque »."),("1867","Mort à Paris ; legs à sa ville natale.")),
 access="Musée Ingres-Bourdelle, horaires à consulter"),
A("personnalites","Olympe de Gouges, l'autrice des droits de la femme","1748-1793 · Montauban",
 "Née à Montauban en 1748, Marie Gouze, devenue Olympe de Gouges, publie en 1791 la Déclaration des droits de la femme et de la citoyenne. Elle est guillotinée en 1793.",
 "Olympe de Gouges, née Marie Gouze à Montauban le 7 mai 1748, est l'autrice de la Déclaration des droits de la femme et de la citoyenne, publiée en 1791.",
 ["Fille d'une famille modeste de Montauban, veuve jeune, elle s'installe à Paris, prend le nom d'Olympe de Gouges et écrit pour le théâtre. Elle dénonce l'esclavage des Noirs dans plusieurs pièces.",
  "En 1791, elle répond à la Déclaration des droits de l'homme par un texte qui réclame pour les femmes les mêmes droits que les hommes. Opposée à la Terreur et proche des Girondins, elle est arrêtée pour ses écrits et guillotinée le 3 novembre 1793."],
 "Olympe de Gouges"),
A("insolite","On ne devrait jamais quitter Montauban","1963 · Les Tontons flingueurs",
 "Dans « Les Tontons flingueurs » de Georges Lautner (1963), Lino Ventura joue Fernand Naudin, un truand rangé à Montauban. Sa réplique sur sa ville est devenue proverbiale, alors que le film n'y a pas été tourné.",
 "La réplique « On ne devrait jamais quitter Montauban », dite par Lino Ventura dans « Les Tontons flingueurs » en 1963, a fait connaître la ville à des générations de spectateurs.",
 ["Dans le film de Georges Lautner, dialogué par Michel Audiard, Fernand Naudin, ancien truand reconverti dans le commerce de matériel agricole à Montauban, est appelé à Paris par un vieil ami mourant qui lui confie ses affaires et sa fille. Pris dans des règlements de comptes, il regrette sa tranquillité de province.",
  "Le film, mal accueilli par une partie de la critique à sa sortie, est devenu un classique du cinéma populaire français."],
 "Les Tontons flingueurs",
 links=[L("film","« Les Tontons flingueurs » (1963), de Georges Lautner","https://fr.wikipedia.org/wiki/Les_Tontons_flingueurs","Dialogues de Michel Audiard, avec Lino Ventura")]),
]

# ---------------------------------------------------------------- PERIGUEUX
perigueux=[
A("politique","Périgueux, la ville d'Yves Guéna et de Xavier Darcos","1971-2026 · Hôtel de ville",
 "Deux ministres, Yves Guéna et Xavier Darcos, ont dirigé Périgueux pendant près de quarante ans. En mars 2026, la ville est repassée à droite avec Michel Cadet, élu avec 53,21 % des voix.",
 "Michel Cadet, divers droite, est maire de Périgueux depuis mars 2026, élu au second tour avec 53,21 % des voix face à la liste d'union de la gauche d'Emeric Lavitola.",
 ["Gaulliste historique, Yves Guéna dirige Périgueux de 1971 à 1997. Plusieurs fois ministre sous de Gaulle et Pompidou, il termine sa carrière comme président du Conseil constitutionnel, de 2000 à 2004. Son successeur, Xavier Darcos, maire de 1997 à 2008, est ministre de l'Éducation nationale de 2007 à 2009, puis du Travail.",
  "La ville alterne ensuite : le socialiste Michel Moyrand de 2008 à 2014, Antoine Audi, divers droite, de 2014 à 2020, puis la socialiste Delphine Labails. En mars 2026, Michel Cadet l'emporte en duel avec 5 416 voix contre 4 763 et obtient 27 des 35 sièges."],
 "Yves Guéna"),
A("patrimoine","Saint-Front, la cathédrale aux cinq coupoles","XIIe-XIXe siècles · Place de la Clautre",
 "Avec son plan en croix grecque et ses cinq coupoles, la cathédrale Saint-Front rappelle Saint-Marc de Venise. Sa restauration par Paul Abadie a inspiré le Sacré-Cœur de Montmartre.",
 "La cathédrale Saint-Front de Périgueux, élevée au XIIe siècle sur le tombeau de l'évangélisateur du Périgord, est l'un des grands édifices à coupoles d'Europe occidentale.",
 ["Son plan en croix grecque, couvert de cinq coupoles sur pendentifs, est inhabituel en France et évoque la basilique Saint-Marc de Venise. L'église est une étape majeure sur la route de Compostelle partant de Vézelay.",
  "Très dégradée, elle est restaurée et en partie reconstruite à partir de 1852 par l'architecte Paul Abadie, qui y ajoute des lanternons et des clochetons. Il s'en inspire ensuite pour le Sacré-Cœur de Montmartre. La cathédrale est inscrite depuis 1998 au patrimoine mondial de l'Unesco au titre des chemins de Saint-Jacques-de-Compostelle."],
 "Cathédrale Saint-Front de Périgueux",
 lat=45.1843,lon=0.7225,access="Entrée libre en dehors des offices",protection="Monument historique classé, patrimoine mondial de l'Unesco"),
A("histoire","Vesunna, la cité gallo-romaine sous Périgueux","Ier-IIIe siècles · Tour de Vésone",
 "Sous Périgueux s'étend Vesunna, capitale gallo-romaine des Pétrocores. La tour de Vésone, haute de plus de vingt mètres, est le vestige du temple de la déesse tutélaire.",
 "Périgueux est née de Vesunna, ville gallo-romaine fondée au Ier siècle, dont subsistent la tour de Vésone, des arènes et une riche maison mise au jour au XXe siècle.",
 ["Les Pétrocores, peuple gaulois qui a donné son nom au Périgord, s'installent dans la plaine de l'Isle sous la domination romaine. La ville s'organise autour d'un grand sanctuaire dédié à Vesunna, la déesse de la source ; la cella circulaire du temple, la tour de Vésone, est encore debout, ouverte par une brèche que la légende attribue à la fuite de la déesse.",
  "Au IIIe siècle, menacée par les invasions, la ville se replie dans une enceinte faite de blocs récupérés sur les monuments. En 2003, le musée Vesunna, dessiné par Jean Nouvel, est ouvert au-dessus des vestiges d'une maison romaine, la domus des Bouquets, dont les peintures murales ont été conservées."],
 "Tour de Vésone",
 access="Jardin de la tour en accès libre ; musée Vesunna, horaires à consulter",protection="Monument historique classé"),
]

# ---------------------------------------------------------------- POITIERS
poitiers=[
A("politique","Anthony Brottier bat l'écologiste Léonore Moncond'huy","2020-2026 · Hôtel de ville",
 "Élue en 2020 à trente ans, l'écologiste Léonore Moncond'huy a perdu Poitiers en mars 2026 face au centriste Anthony Brottier, élu avec 47,32 % des voix.",
 "Anthony Brottier, divers centre, est maire de Poitiers depuis mars 2026, élu au second tour avec 47,32 % des voix face à la maire sortante Léonore Moncond'huy (40,79 %).",
 ["Poitiers a été dirigée par des socialistes de 1977 à 2020 : Jacques Santrot jusqu'en 2008, puis Alain Claeys. En 2020, Léonore Moncond'huy, à la tête de la liste écologiste et citoyenne Poitiers collectif, l'emporte à trente ans et devient l'une des figures de la vague verte dans les grandes villes.",
  "En mars 2026, sa liste, élargie au second tour à celle de Poitiers en commun, ne recueille que 40,79 %. Anthony Brottier obtient 12 086 voix et 40 des 53 sièges ; la liste du Rassemblement national de Charles Rangheard réunit 7,01 %.",
  "Poitiers est aussi la ville natale de Jean-Pierre Raffarin, président de la région Poitou-Charentes de 1988 à 2002, puis Premier ministre de 2002 à 2005."],
 "Léonore Moncond'huy"),
A("faits_divers","La Séquestrée de Poitiers, vingt-cinq ans enfermée","Mai 1901 · Rue de la Visitation",
 "En mai 1901, sur dénonciation anonyme, la police découvre Blanche Monnier, 52 ans, enfermée depuis vingt-cinq ans dans une chambre obscure de la maison familiale. Elle ne pèse plus que 25 kilos.",
 "Le 23 mai 1901, la police de Poitiers découvre Blanche Monnier, fille d'une famille bourgeoise de la ville, enfermée depuis environ vingt-cinq ans dans sa chambre, rue de la Visitation.",
 ["Une lettre anonyme adressée au procureur général signale qu'une femme est séquestrée chez Mme Monnier, veuve respectée de la bonne société poitevine. Les policiers forcent une fenêtre condamnée et trouvent Blanche, décharnée, allongée dans ses excréments, au milieu de déchets de nourriture. Elle avait disparu de la vie publique dans les années 1870, peut-être après une relation refusée par sa mère.",
  "Sa mère, arrêtée, meurt quinze jours plus tard. Son frère Marcel, ancien sous-préfet, est condamné en première instance pour complicité, puis acquitté en appel : la cour estime que la victime n'était pas retenue de force. Blanche Monnier finit sa vie dans un hôpital psychiatrique de Blois.",
  "André Gide consacre à l'affaire un livre, « La Séquestrée de Poitiers », publié en 1930."],
 "Blanche Monnier",
 links=[L("livre","« La Séquestrée de Poitiers » (1930), d'André Gide","https://fr.wikipedia.org/wiki/La_S%C3%A9questr%C3%A9e_de_Poitiers","Le récit de l'affaire à partir du dossier judiciaire")]),
A("histoire","Charles Martel arrête l'armée omeyyade en 732","Octobre 732 · Moussais-la-Bataille",
 "En octobre 732, entre Tours et Poitiers, les Francs de Charles Martel battent l'armée d'Abd al-Rahman, gouverneur d'al-Andalus, qui est tué. La bataille a longtemps été érigée en mythe national.",
 "La bataille de Poitiers, datée traditionnellement du 25 octobre 732, oppose les Francs de Charles Martel à l'armée omeyyade d'Abd al-Rahman al-Ghafiqi, venue d'Espagne.",
 ["Après avoir conquis l'Espagne, les troupes musulmanes d'al-Andalus lancent des raids en Gaule. En 732, Abd al-Rahman bat le duc d'Aquitaine, pille Bordeaux et remonte vers l'abbaye Saint-Martin de Tours. Charles Martel, maire du palais des rois mérovingiens, l'attend au nord de Poitiers, probablement près de Moussais-la-Bataille.",
  "Abd al-Rahman est tué et son armée se retire de nuit. La victoire renforce le pouvoir de Charles Martel, dont le petit-fils sera Charlemagne. Les historiens relativisent aujourd'hui sa portée militaire, mais la bataille a été très tôt présentée comme un coup d'arrêt décisif à l'expansion musulmane en Europe."],
 "Bataille de Poitiers (732)"),
A("patrimoine","Notre-Dame-la-Grande et sa façade sculptée","XIIe siècle · Place Charles-de-Gaulle",
 "La façade romane de Notre-Dame-la-Grande, couverte de sculptures, retrouve chaque été ses couleurs d'origine grâce à des projections lumineuses.",
 "L'église Notre-Dame-la-Grande, au cœur de Poitiers, possède l'une des façades romanes les plus richement sculptées de France, achevée au XIIe siècle.",
 ["La façade se lit comme un livre d'images : Adam et Ève, les prophètes, l'Annonciation, la Nativité, les apôtres et, au sommet, le Christ en gloire. À l'époque romane, ces sculptures étaient peintes de couleurs vives.",
  "Une restauration achevée en 1995 a permis d'en retrouver des traces. Depuis, des projections, les « Polychromies », restituent chaque soir d'été les couleurs présumées de la façade. À quelques rues, le baptistère Saint-Jean, élevé au IVe siècle, compte parmi les plus anciens édifices chrétiens de France."],
 "Église Notre-Dame-la-Grande de Poitiers",
 lat=46.5832,lon=0.3448,access="Entrée libre ; projections en soirée l'été",protection="Monument historique classé"),
A("personnalites","Michel Foucault, enfant de Poitiers","1926-1984 · Poitiers",
 "Né à Poitiers en 1926, fils d'un chirurgien de la ville, Michel Foucault est devenu l'un des philosophes français les plus lus au monde, avec « Surveiller et punir » et « Histoire de la folie ».",
 "Michel Foucault, philosophe, est né à Poitiers le 15 octobre 1926 dans une famille de médecins ; il a étudié au lycée Henri-IV de la ville avant de rejoindre Paris.",
 ["Son père, chirurgien et professeur à l'école de médecine de Poitiers, le destine à la médecine. Il choisit la philosophie, entre à l'École normale supérieure en 1946 et s'intéresse à la psychologie et à l'histoire des institutions.",
  "Ses livres, « Histoire de la folie à l'âge classique » (1961), « Les Mots et les Choses » (1966), « Surveiller et punir » (1975), analysent les liens entre savoir et pouvoir à travers l'asile, la prison ou la sexualité. Professeur au Collège de France à partir de 1970, il meurt à Paris le 25 juin 1984."],
 "Michel Foucault",
 timeline=T(("1926","Naissance à Poitiers."),("1961","« Histoire de la folie à l'âge classique »."),("1970","Élu au Collège de France."),("1975","« Surveiller et punir »."),("1984","Mort à Paris."))),
]

cities=[("64445","Pau","Pyrénées-Atlantiques",43.2951,-0.3708,pau),
        ("64102","Bayonne","Pyrénées-Atlantiques",43.4929,-1.4748,bayonne),
        ("64122","Biarritz","Pyrénées-Atlantiques",43.4832,-1.5586,biarritz),
        ("65440","Tarbes","Hautes-Pyrénées",43.2328,0.0781,tarbes),
        ("47001","Agen","Lot-et-Garonne",44.2033,0.6163,agen),
        ("82121","Montauban","Tarn-et-Garonne",44.0176,1.3550,montauban),
        ("24322","Périgueux","Dordogne",45.1847,0.7214,perigueux),
        ("86194","Poitiers","Vienne",46.5802,0.3404,poitiers)]
idx=json.load(open('index.json'))
for insee,name,dept,lat,lon,arts in cities:
    path=f"communes/{insee}.json"
    if os.path.exists(path):
        p=json.load(open(path)); have={a.get("wiki") for a in p["anecdotes"]}
        p["anecdotes"]+=[a for a in arts if a.get("wiki") not in have]
    else:
        p={"id":insee,"insee":insee,"name":name,"dept":dept,"kind":"commune","lat":lat,"lon":lon,"anecdotes":arts}
    json.dump(p,open(path,'w'),ensure_ascii=False,indent=1)
    idx["communes"][insee]={"name":name,"count":len(p["anecdotes"]),"updated":"2026-10-07"}
    print(name,len(p["anecdotes"]))
json.dump(idx,open('index.json','w'),ensure_ascii=False,indent=1)
print(sum(v["count"] for v in idx["communes"].values()),"articles",len(idx["communes"]),"communes")
